### ISSUE TITLE
CUDA 9.0 build error.

### ISSUE THREAD

**Issue by EthanZhangYi** [NVIDIA/apex#1031]
An error occurred when I built apex (master-latest), as shown below.
It occurred when nvcc compile [csrc/mlp_cuda.cu](https://github.com/NVIDIA/apex/blob/master/csrc/mlp_cuda.cu)
![image](https://user-images.githubusercontent.com/13479831/104469095-24ef2b80-55f3-11eb-9b49-9e6ddc526b02.png)
Can anyone give some help?

**Comment by ptrblck** [comment]
This error is raised by PyTorch, as it needs CUDA>=9.2 at the moment.
Since CUDA9.2 will be removed soon as the min. CUDA version in PyTorch, I would recommend to update to at least 10.1 or 11.x.

Closing this issue, as it's unrelated to apex.
