### ISSUE TITLE
Cannot install on pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel

### ISSUE THREAD

**Issue by emepetres** [NVIDIA/apex#1036]
Hi,

Following the Quick Start or the dockerfile example to install apex into _pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel_ leads to the issue #957 , that I tried to fix by [installing cublas manually](https://github.com/NVIDIA/apex/issues/957#issuecomment-768173053)

However I'm still not able to install it because the [build is crashing](https://gist.github.com/emepetres/43dd1618ab925ced59380fe1793b8c32#file-build-log).

Any idea how to solve it?

Thanks

**Comment by rsdmse** [comment]
Incidentally, I had to rebuild apex using the exact same base image today and I'm getting similar errors. I had no problem with this last July so I backtracked to the commit number around that time: `a0d99fdb2cfcc418809dde975f51097c3d6010ca`

I didn't investigate further when this broke. My guess is that it only works for a very specific set of CUDA versions, but there's no documentation on which commit number corresponds to which CUDA version.
