### ISSUE TITLE
rtx3080   RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by qq260612718** [NVIDIA/apex#1051]
My experimental environment is cuda11.0 RTX3080 pytorch1.7.1
When I try to **install apex,**, the following problems occur:
**nvcc fatal: Unsupported gpu architecture ‘compute_86’**
I took this method of reducing the computing power, which showed that apex was successfully installed.
**export TORCH_CUDA_ARCH_LIST="7.5"**
But when I run the code, the following situation appears:
**RuntimeError: CUDA error: no kernel image is available for execution on the device.**
Can someone help me?I tried cuda10.0 and 10.2 lower versions and still have problems.

**Comment by ptrblck** [comment]
You would have to use `TORCH_CUDA_ARCH_LIST="8.0"` or `="8.6"` to run apex on the 3080.
These architectures are supported in CUDA11, so your local 10.x toolkits won't work.

That being said, we recommend to use the native mixed-precision implementation as described [here](https://github.com/NVIDIA/apex/issues/818).
