### ISSUE TITLE
RuntimeError: value cannot be converted to type at::Half without overflow: -1e+09

### ISSUE THREAD

**Issue by xwjim** [NVIDIA/apex#1052]
My experimental environment is cuda11.0 RTX1080Ti pytorch1.7.1
when i try to run the code, the following problem occur:

File "/home/wxu/github/docre/code/models/MPR.py", line 169, in forward
    scores_mask = scores.masked_fill(~path_mask.unsqueeze(-1),-1e9)
RuntimeError: value cannot be converted to type at::Half without overflow: -1e+09
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

I try to change the masked value -1e9 and I found -1e4 is OK.
I just wonder if there is a better solution to solve the problem.

**Comment by Daemon-ser** [comment]
Same problem here. Have you solved it ?

**Comment by Jiang-X-Pro** [comment]
Same problem here. Have you solved it ?

**Comment by xwjim** [comment]
> Same problem here. Have you solved it ?

Maybe you can try xxx = float("-inf")
