### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by tz3** [NVIDIA/apex#106]
I've got the following errors during installation on p3.2 aws ami (deep learning ubuntu version 20)
 
``` python setup.py install --cuda_ext``` 
 the command above raised the following error
```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
csrc/flatten_unflatten.cpp:1:29: fatal error: torch/extension.h: No such file or directory
```

``` python setup.py install --cpp_ext ``` 
also with another flag
```
csrc/flatten_unflatten.cpp:1:29: fatal error: torch/extension.h: No such file or directory
```

**Comment by gcp** [comment]
Version 20 or version 2.0?

Version 2.0 comes with PyTorch 0.3, which is out of date. You want to update to PyTorch 1.0.

**Comment by tz3** [comment]
@gcp thank you for the suggestion, it solved my problem.
FYI: I meant Deep Learning AMI (Ubuntu) Version 20.0, it comes with 0.4 version of PyTorch
