### ISSUE TITLE
FastLayerNorm ext not found after install on master

### ISSUE THREAD

**Issue by sshleifer** [NVIDIA/apex#1072]
I ran 
```bash
git pull
rm -rf build
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
which worked, after commenting out the minor version check, but then `from apex.contrib.layer_norm import FastLayerNorm` failed. Has anyone run into this or similar?

[logs](https://gist.github.com/sshleifer/5bc1c1d2c0e24e3446a377cec008df4c)
```python
In [1]: from apex.contrib.layer_norm import FastLayerNorm
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3e19fe80091c> in <module>
----> 1 from apex.contrib.layer_norm import FastLayerNorm

~/apex/apex/contrib/layer_norm/__init__.py in <module>
----> 1 from .layer_norm import FastLayerNorm

~/apex/apex/contrib/layer_norm/layer_norm.py in <module>
      2 from torch.nn import init
      3
----> 4 import fast_layer_norm
      5
      6 class FastLayerNormFN(torch.autograd.Function):

ModuleNotFoundError: No module named 'fast_layer_norm'
```

**Comment by tbmihailov** [comment]
You need to use global-option="--fast_layer_norm" to install apex with fast_layer_norm.
`
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--fast_layer_norm" ./
`

**Comment by sshleifer** [comment]
Thanks @tbmihailov !

**Comment by ElinLiu0** [comment]
> ```python
> from apex.contrib.layer_norm import FastLayerNorm
> ```

Hi there,same command,error again :(

**Comment by ElinLiu0** [comment]
> You need to use global-option="--fast_layer_norm" to install apex with fast_layer_norm. `pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--fast_layer_norm" ./`

Hi there,same command but also same error again 
```python
ModuleNotFoundError: No module named 'fast_layer_norm'
```
