### ISSUE TITLE
Failed to install apex on CUDA 10.1 torch 1.6.0

### ISSUE THREAD

**Issue by Ema1997** [NVIDIA/apex#1089]
Hi, 
I use the following code to install the apex:
`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`
and I faced some error as below:
![image](https://user-images.githubusercontent.com/19912756/115991019-e527df00-a5f8-11eb-8d0e-9eb4ab18afdf.png)
![image](https://user-images.githubusercontent.com/19912756/115991034-fa9d0900-a5f8-11eb-81df-f2ee5f400391.png)

My CUDA version is 10.1, torch is 1.6.0+cu101 and torchvision is 0.7.0+cu101.

How can I deal with these errors?

**Comment by Ema1997** [comment]
#1091 https://github.com/NVIDIA/apex/issues/1091

The command
`git reset --hard a651e2c24ecf97cbf367fd3f330df36760e1c597`
solved the problem.

**Comment by joyceshao7** [comment]
Thank you so much! It works even for CUDA 10.1 torch 1.8.0.
