### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by yuanlixian** [NVIDIA/apex#1102]
Tried to install APEX but failed with the same error under CUDA 9.2 or CUDA 11.0.
Tried `git reset --hard a651` and looked at the similar install errors but still failed.
The error was like this:

![Screenshot from 2021-05-10 11-09-11](https://user-images.githubusercontent.com/9656584/117602731-f984e380-b183-11eb-80bc-514d08927ac0.png)

Anyone can help me with the solution? Many thanks.

**Comment by vinthony** [comment]
downgrading the version of PyTorch from 1.6x or 1.7x to 1.4 helps me.

**Comment by duerwen** [comment]
I had the same error

**Comment by yuanlixian** [comment]
> downgrading the version of PyTorch from 1.6x or 1.7x to 1.4 helps me.

Thanks for the help. I downgraded the PyTorch version from 1.5x to 1.4.0 and it worked. 
In case others want to know the configurations, I had Python 3.6.6 (Anaconda), CUDA 9.2 and Pytorch 1.4.0. 

I'm closing this comment since it solved my problem.

**Comment by lhambrid** [comment]
I used 
`pip install torch==1.4.0 torchvision==0.5.0`
per the pytorch website and the problem persists.

**Comment by github-eliviate** [comment]
> I used `pip install torch==1.4.0 torchvision==0.5.0` per the pytorch website and the problem persists.
cannot install apex

**Comment by yusirhhh** [comment]
I had this error too
