### ISSUE TITLE
Segmentation fault using fused_layer_norm

### ISSUE THREAD

**Issue by jcyk** [NVIDIA/apex#111]
hi !
Using  fused_layer_norm leads to Segmentation fault.

I only see this error line.

**Comment by ngimel** [comment]
Can you please provide a minimum script reproducing this error?

**Comment by jcyk** [comment]
Sorry. I made some mistakes. Thx!

**Comment by Albert-xy** [comment]
> Sorry. I made some mistakes. Thx!

I have also meet the same problem, can you say where do you made a mistake, maybe it also can help me.

Thanks.

**Comment by mcarilli** [comment]
A clean rebuild of Apex fixed this issue for some other people https://github.com/NVIDIA/apex/issues/156#issuecomment-465301976.
