### ISSUE TITLE
SyncBN Error

### ISSUE THREAD

**Issue by Spritea** [NVIDIA/apex#115]
Hi~

Nice work! But when I use the SyncBN feature with Pytorch's original `torch.nn.DataParallel`, I met an error and didn't know the reason really. My Pytorch version is 0.4.0.
Here is my part code.
```
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model=apex.parallel.convert_syncbn_model(model)
    model=model.to(device)
    model = torch.nn.DataParallel(model, device_ids=[0,1])
```
Error below.
```
File "/home/ali/anaconda3/envs/pt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ali/anaconda3/envs/pt/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/parallel/sync_batchnorm.py", line 68, in forward
TypeError: get_world_size() takes 0 positional arguments but 1 was given
```
Thanks.

**Comment by ptrblck** [comment]
As far as I know the `group` argument to `distributed.get_world_size()` was added after `0.4.1`.
[get_world_size() in 0.4.1](https://pytorch.org/docs/0.4.1/distributed.html?highlight=get_world_size#torch.distributed.get_world_size)
[get_world_size() in 1.0.0](https://pytorch.org/docs/stable/distributed.html#torch.distributed.get_world_size)

Could you try to update to PyTorch `1.0` and try it again?
You can find the install instructions on [the website](https://pytorch.org/get-started/locally/).

**Comment by mcarilli** [comment]
@Spritea Currently, SyncBN only supports training with 1 GPU per process.  DataParallel is not supported, you'll have to use apex.parallel.DistributedDataParallel or torch.nn.parallel.DistributedDataParallel.

**Comment by Spritea** [comment]
Thanks for the reply~
@ptrblck I changed the Pytorch version to 1.0 stable and reinstall apex. I tried my code again **without change**, and it reported a new error below.
```
File "/home/cws/anaconda3/envs/pt10/lib/python3.6/site-packages/torch/cuda/comm.py", line 40, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: get_device is not implemented for tensors with CPU backend (get_device_slow at /opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/ATen/core/TensorImpl.h:873)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f992eafbcc5 in /home/cws/anaconda3/envs/pt10/lib/python3.6/site-packages/torch/lib/libc10.so)
```
I guess @mcarilli is more reasonable, so I would try `torch.nn.parallel.DistributedDataParallel` ASAP.

**Comment by Spritea** [comment]
So I looked through this [file](https://github.com/NVIDIA/apex/blob/master/examples/distributed/main.py), and I guess if I want to use native `torch.nn.parallel.DistributedDataParallel`, I only need to comment thses code below. If I want to use `apex.parallel.DistributedDataParallel`, just leave them there. Is that right?
```
#=====START: ADDED FOR DISTRIBUTED======
'''
Wrap model in our version of DistributedDataParallel.
This must be done AFTER the model is converted to cuda.
'''

if args.distributed:
    model = DDP(model)
#=====END:   ADDED FOR DISTRIBUTED======
```

**Comment by Spritea** [comment]
My apologize :stuck_out_tongue_closed_eyes:Both of you are right. 

I tried this [file](https://github.com/NVIDIA/apex/blob/master/examples/distributed/main.py) on 1 node with 2 GPUs. At first, I tried Pytorch 0.4.0 with `torch.nn.parallel.DistributedDataParallel` only, it works. But when I added SyncBN like `apex.parallel.convert_syncbn_model`, it reported the same error as https://github.com/NVIDIA/apex/issues/115#issue-396269425. 

Then I changed to Pytorch1.0, both `torch.nn.parallel.DistributedDataParallel` and SyncBN `apex.parallel.convert_syncbn_model` work. Besides, `apex.parallel.DistributedDataParallel` and SyncBN work with Pytorch1.0.

To conclude, 

- If you need `torch.nn.parallel.DistributedDataParallel` only, then Pytorch0.4.0 is OK.

- If you need SyncBN, due to https://github.com/NVIDIA/apex/issues/115#issuecomment-452127004 , you have to use it with `torch.nn.parallel.DistributedDataParallel` or `apex.parallel.DistributedDataParallel`, then you need Pytorch0.4.1 or higher(Although I tried Pytorch1.0 only, Pytorch0.4.1 should work).
