### ISSUE TITLE
TypeError: Class advice impossible in Python3

### ISSUE THREAD

**Issue by lynnna-xu** [NVIDIA/apex#116]
TypeError Traceback (most recent call last)
in ()
----> 1 from pytorch_pretrained_bert import BertTokenizer

/opt/conda/envs/py3/lib/python3.6/site-packages/pytorch_pretrained_bert/init.py in ()
1 version = "0.4.0"
2 from .tokenization import BertTokenizer, BasicTokenizer, WordpieceTokenizer
----> 3 from .modeling import (BertConfig, BertModel, BertForPreTraining,
4 BertForMaskedLM, BertForNextSentencePrediction,
5 BertForSequenceClassification, BertForMultipleChoice,

/opt/conda/envs/py3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py in ()
152
153 try:
--> 154 from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
155 except ImportError:
156 print("Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.")

/opt/conda/envs/py3/lib/python3.6/site-packages/apex/init.py in ()
16 from apex.exceptions import (ApexAuthSecret,
17 ApexSessionSecret)
---> 18 from apex.interfaces import (ApexImplementation,
19 IApex)
20 from apex.lib.libapex import (groupfinder,

/opt/conda/envs/py3/lib/python3.6/site-packages/apex/interfaces.py in ()
8 pass
9
---> 10 class ApexImplementation(object):
11 """ Class so that we can tell if Apex is installed from other
12 applications

/opt/conda/envs/py3/lib/python3.6/site-packages/apex/interfaces.py in ApexImplementation()
12 applications
13 """
---> 14 implements(IApex)

/opt/conda/envs/py3/lib/python3.6/site-packages/zope/interface/declarations.py in implements(*interfaces)
481 # the coverage for this block there. :(
482 if PYTHON3:
--> 483 raise TypeError(_ADVICE_ERROR % 'implementer')
484 _implements("implements", interfaces, classImplements)
485

TypeError: Class advice impossible in Python3. Use the @Implementer class decorator instead.

Hi, I came across this error after running import pytorch_pretrained_bert. My configurations are as follows:
torch version 1.0.0
python version 3.6
cuda 9.2

**Comment by lynnna-xu** [comment]
I uninstalled the old version of apex and reinstalled a new version. It worked. Thanks.

git clone https://www.github.com/nvidia/apex
cd apex
python setup.py install

**Comment by demeiyan** [comment]
> I uninstalled the old version of apex and reinstalled a new version. It worked. Thanks.
> 
> git clone https://www.github.com/nvidia/apex
> cd apex
> python setup.py install

I install follow your steps but it don't work.

**Comment by ptrblck** [comment]
@demeiyan 
Could you make sure to uninstall all previous `apex` versions and try to reinstall it again?

**Comment by duyvuleo** [comment]
It works in my case. Thanks @lynnna-xu .

**Comment by jakubLangr** [comment]
Hi I do not think this issue should be closed at all.

I have just replicated this issue on:
* Mac OS X (10.14.6)
* Ubuntu 16.04 running nvidia's official image
* AWS Deep Learning AMI 22.0

**Comment by ptrblck** [comment]
@jakubLangr 
Could you post your error message?

**Comment by jakubLangr** [comment]
@ptrblck done as per above.

**Comment by ptrblck** [comment]
@jakubLangr Thanks for the error logs.
Have you installed `apex` from `pip`, as both containers seem to point to [this library](https://pypi.org/project/apex/), which implements some authentication functions.
Could you uninstall all `apex` versions and try to rebuild?

**Comment by jakubLangr** [comment]
Hi @ptrblck apologies I kept running into different errors when installing `apex` from the nVidia repo. It should have raised some flags in my head when an installation of something this low level goes so smoothly, something is wrong. Also I appreciate you don't control pypi but this naming is a tad bit confusing :) 

Will do some more investigating today.

**Comment by simonibs** [comment]
I got this issue with python3, but fixed by following @lynnna-xu with 

```
pip3 uninstall apex

git clone https://www.github.com/nvidia/apex
cd apex
python3 setup.py install
```

**Comment by zzj0402** [comment]
```bash
pip3 uninstall apex && git clone https://www.github.com/nvidia/apex && cd apex && python3 setup.py install
```
Just to make it one line ^^

**Comment by spacewaterbear** [comment]
It's appearing that the lib changed its name to pytorch extension => https://pypi.org/project/pytorch-extension/

**Comment by YutongWang1216** [comment]
> It's appearing that the lib changed its name to pytorch extension => https://pypi.org/project/pytorch-extension/

That solves the problem perfectly! Thanks a lot 😊

**Comment by edwardzjl** [comment]
> It's appearing that the lib changed its name to pytorch extension => https://pypi.org/project/pytorch-extension/

I don't think it's an official release.

**Comment by Hangsiin** [comment]
> It's appearing that the lib changed its name to pytorch extension => https://pypi.org/project/pytorch-extension/

thanks. I struggled with this issue for 2 days... it worked perfectly.
