### ISSUE TITLE
apex.optimizers.FP16_Optimizer doesn't have state_dict() and load_state_dict()

### ISSUE THREAD

**Issue by donglixp** [NVIDIA/apex#120]
Thanks for the great package!

The class apex.fp16_utils.FP16_Optimizer has the methods have state_dict() and load_state_dict() for storing and recovering optimizer states. But apex.optimizers.FP16_Optimizer doesn't. These two methods are important to recover from a stored training checkpoint.

**Comment by donglixp** [comment]
I create a PR in https://github.com/NVIDIA/apex/pull/123

**Comment by mcarilli** [comment]
@FDecaYed How were you saving and restoring your model and optimizer when you were using FusedAdam?  Is there a public example script you can point me to (maybe the mlperf submission)? 

@donglixp Thank you for the PR!  I want to check with @FDecaYed to make sure it's compatible with what he was doing.  In the near future, I hope to unify the different FP16_Optimizer interfaces.  There's really no reason we should have two of them.

**Comment by FDecaYed** [comment]
@donglixp Sorry this is something I missed. Thanks for your contribution. Their is another TODO on my list which is a way to save out unflattened master weight. I didn't really got to do it. 
@mcarilli We don't have a good example of doing it. User apparently can do it manually but that is similar to implements their own save/load dict.
Also I agree with you if we want to support all functionality pytorch optimizers have in these wrappers, then we should probably think of unify. There are parts they share in common but also parts quite different.

**Comment by donglixp** [comment]
@donglixp @FDecaYed It would be great to unify the interfaces! apex.fp16_utils.FP16_Optimizer is more general, but the class apex.optimizers.FP16_Optimizer is more memory-saving than apex.fp16_utils.FP16_Optimizer now.

**Comment by vince62s** [comment]
Question for you guys.
If the intention is to unify the interface and use th fp16_utils as the mainstream one, would that hurt to merge #123 ?
In our tests, using fusedadam in fp16_utils is 1) cumbersome 2) much slower.

Thanks for your feedback.

**Comment by donglixp** [comment]
@vince62s fp16_utils is slower and needs more gpu memory, but it's more flexible to plug in any optimizer.
