### ISSUE TITLE
"from torch.cuda import amp" and "from apex import amp" are conflict

### ISSUE THREAD

**Issue by newyorkthink** [NVIDIA/apex#1213]
yolov3 and yolov5 have from torch.cuda import amp

i insert from apex import amp have error

![image](https://user-images.githubusercontent.com/87791643/141244760-bfefbaab-d0d1-4aa5-ac84-3ac62d9fddd0.png)

![image](https://user-images.githubusercontent.com/87791643/141244733-fbfea077-30c1-4583-be73-14607cfc7e11.png)

**Comment by ptrblck** [comment]
Closing based on https://github.com/NVIDIA/apex/issues/1214#issuecomment-1203619859
