### ISSUE TITLE
from apex import amp instead from torch.cuda import amp error

### ISSUE THREAD

**Issue by newyorkthink** [NVIDIA/apex#1214]
![image](https://user-images.githubusercontent.com/87791643/141245025-0e5c4348-afe3-4e8a-ace0-dcb5dda7a372.png)

**Comment by ptrblck** [comment]
`apex.amp` is deprecated and you should use the native `torch.cuda.amp` implementation as described [here](https://github.com/NVIDIA/apex/issues/818). Closing.
