### ISSUE TITLE
How can I solve it？

### ISSUE THREAD

**Issue by Roll77-luo** [NVIDIA/apex#1215]
When using apex mixed precision training, a convolution module in my code needs to be used twice, which leads to an error:Index
![1](https://user-images.githubusercontent.com/84185631/141316912-ff39ed40-e37f-45ef-a735-3e3fa7151b6b.PNG)
 error: tuple index out of range. How should I solve it?

**Comment by ChunhanLi** [comment]
I met same IndexError when do prediction. If I removed apex mixed precesion training, prediction is fine.

**Comment by Siu-Keung** [comment]
Same problem while training model under mixed-precision mode.

**Comment by Siu-Keung** [comment]
> When using apex mixed precision training, a convolution module in my code needs to be used twice, which leads to an error:Index ![1](https://user-images.githubusercontent.com/84185631/141316912-ff39ed40-e37f-45ef-a735-3e3fa7151b6b.PNG) error: tuple index out of range. How should I solve it?

Fixed by downgrading pytorch's version from 1.10 to 1.8.1

**Comment by Rolling-Plain** [comment]
I met the same question when my torch version was 1.10.0
There is my solution

reinstall the whole environment
install torch=1.9.0
install apex

（I didn't use version 1.8. X because an inherent error may be reported in subsequent tasks

**Comment by ptrblck** [comment]
Please use the native mixed-precision training util. via `torch.cuda.amp` as described [here](https://github.com/NVIDIA/apex/issues/818) which is supported in the current PyTorch release. Closing
