### ISSUE TITLE
Crash while compiling with CUDA10.2 and --fast_layer_normal

### ISSUE THREAD

**Issue by li-yi-dong** [NVIDIA/apex#1257]
I tried to compile with --fast_layer_normal and CUDA10.2, I got such an error:

/usr/local/cuda/bin/nvcc -I/apex-master/csrc -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/python3.6.13/include/python3.6m -c apex/contrib/csrc/optimizers/fused_lamb_cuda_kernel.cu -o build/temp.linux-x86_64-3.6/apex/contrib/csrc/optimizers/fused_lamb_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=fused_lamb_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -std=c++14
#7 1269.7     /usr/local/cuda/bin/nvcc -I/apex-master/csrc -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/python3.6.13/include/python3.6m -c csrc/multi_tensor_l2norm_kernel.cu -o build/temp.linux-x86_64-3.6/csrc/multi_tensor_l2norm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=fused_lamb_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -std=c++14
#7 1289.5     g++ -pthread -shared -B /opt/conda/envs/python3.6.13/compiler_compat -L/opt/conda/envs/python3.6.13/lib -Wl,-rpath=/opt/conda/envs/python3.6.13/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/apex/contrib/csrc/optimizers/fused_lamb_cuda.o build/temp.linux-x86_64-3.6/apex/contrib/csrc/optimizers/fused_lamb_cuda_kernel.o build/temp.linux-x86_64-3.6/csrc/multi_tensor_l2norm_kernel.o -L/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.6/fused_lamb_cuda.cpython-36m-x86_64-linux-gnu.so
#7 1289.8     building 'fast_layer_norm' extension
#7 1289.8     creating build/temp.linux-x86_64-3.6/apex/contrib/csrc/layer_norm
#7 1289.8     gcc -pthread -B /opt/conda/envs/python3.6.13/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/apex-master/apex/contrib/csrc/layer_norm -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/python3.6.13/include/python3.6m -c apex/contrib/csrc/layer_norm/ln_api.cpp -o build/temp.linux-x86_64-3.6/apex/contrib/csrc/layer_norm/ln_api.o -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=fast_layer_norm -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
#7 1289.8     cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
#7 1289.9     In file included from /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/ATen/Parallel.h:140:0,
#7 1289.9                      from /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
#7 1289.9                      from /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
#7 1289.9                      from /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
#7 1289.9                      from /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
#7 1289.9                      from /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
#7 1289.9                      from apex/contrib/csrc/layer_norm/ln_api.cpp:1:
#7 1289.9     /opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/ATen/ParallelOpenMP.h:83:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
#7 1289.9      #pragma omp parallel for if ((end - begin) >= grain_size)
#7 1289.9
#7 1290.0     In file included from apex/contrib/csrc/layer_norm/ln_api.cpp:4:0:
#7 1290.0     apex/contrib/csrc/layer_norm/ln.h:5:10: fatal error: cuda_bf16.h: No such file or directory
#7 1290.0      #include <cuda_bf16.h>
#7 1290.0               ^~~~~~~~~~~~~
#7 1290.0     compilation terminated.
#7 1290.0     error: command 'gcc' failed with exit status 1
#7 1290.1     Running setup.py install for apex: finished with status 'error'

It seems that CUDA10.2 do not has `cuda_bf16.h`, I think there should be better version check instead of crash after a long compilation.

**Comment by ptrblck** [comment]
I agree that a better error check would be good and sorry to hear that the error was raised after a long compilation.
We will drop CUDA10.x support soon, so won't add an error check. Closing.
