### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribtue 'amp'

### ISSUE THREAD

**Issue by ChunmineHe0224** [NVIDIA/apex#1260]
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Using DynConv 8,8,2
Using DynConv 8,8,2
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    from engine import Engine
  File "/home/hechunming/DoDNet++_MICCAI2022_2/a_DynConv/../engine.py", line 13, in <module>
    from apex.parallel import DistributedDataParallel, SyncBatchNorm
  File "/home/hechunming/.conda/envs/DoDNet/lib/python3.8/site-packages/apex-0.1-py3.8.egg/apex/__init__.py", line 23, in <module>
    from . import transformer
  File "/home/hechunming/.conda/envs/DoDNet/lib/python3.8/site-packages/apex-0.1-py3.8.egg/apex/transformer/__init__.py", line 1, in <module>
    from apex.transformer import amp
  File "/home/hechunming/.conda/envs/DoDNet/lib/python3.8/site-packages/apex-0.1-py3.8.egg/apex/transformer/amp/__init__.py", line 1, in <module>
    from apex.transformer.amp.grad_scaler import GradScaler
  File "/home/hechunming/.conda/envs/DoDNet/lib/python3.8/site-packages/apex-0.1-py3.8.egg/apex/transformer/amp/grad_scaler.py", line 8, in <module>
    class GradScaler(torch.cuda.amp.GradScaler):
AttributeError: module 'torch.cuda' has no attribute 'amp'

By the way, the version of the torch is 1.4.0.

**Comment by JASUEXIII** [comment]
Similar Error occurred in my program,any idea about how to solve it?   :)

**Comment by Y1nFaChu** [comment]
> 

any idea about how to solve it?

**Comment by cardboardcode** [comment]
Encountered the same issue. 

## Dirty Workaround :warning:

What worked for me is to run the following command:
```bash
pip install torch==1.7.1
```
The command above upgrades **torch**`1.4.0` to **torch**`1.7.1`. 

## Why? :question:
Based on this link (https://blog.csdn.net/qq_34211771/article/details/120625282) after googling about, apparently this issue is due to the fact that `torch.cuda` only having the **amp** module introduced after **torch**`1.6.0`. 

Here's an translated abstract from the web link which made me believe it to be so:

### Abstract: Original
```
经过不断的尝试，终于找到了问题的原因。原因在于torch.cuda.amp是在torch1.6版本之后才引入的，而我所使用的是torch1.4版本，自然就会报错。
我的是使用下面命令，安装1.7.1版本后问题解决。具体自己的对应cuda与版本需要查看官网pytorch进行选择对应的安装。
```
### Abstract: Translated
```
After countless attempts, I finally found the source of the error. The cause of it originates from the fact that torch.cuda.amp was introduced after torch1.6 while I was using torch1.4, resulting in the error.
I used the command below, installed 1.7.1 to rectify the issue. Moving forward, one needs to be mindful of the cuda and pytorch compatibility matrix during the installation process.
```

Hope this helps.

**Comment by ptrblck** [comment]
Your PyTorch installation might be too old as `torch.cuda.amp` was introduced in `1.5.0`. Closing.

**Comment by aoguangcheng** [comment]
I trained the DODnet by myself in an environment installed Pytorch1.4.0-GPU version successfully.But now, I need to switch to another machine to train the DODnet，it occurs this problem aftere I install a new conda environment.

**Comment by smallkaka** [comment]
关于DODnet，能请教一些问题吗

**Comment by smallkaka** [comment]
> 关于DODnet，可以教一些问题吗
DODnet
