### ISSUE TITLE
type name is not allowed

### ISSUE THREAD

**Issue by snowyrain** [NVIDIA/apex#1263]
csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(186): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(208): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(208): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(208): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(209): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(209): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(209): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(210): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(210): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(210): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(211): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(211): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(211): error: expected an expression

    csrc/multi_tensor_l2norm_kernel_mp.cu(213): error: a pointer to a bound function may only be used to call the function

    csrc/multi_tensor_l2norm_kernel_mp.cu(213): error: type name is not allowed

    csrc/multi_tensor_l2norm_kernel_mp.cu(213): error: expected an expression

    27 errors detected in the compilation of "/tmp/tmpxft_00014f58_00000000-6_multi_tensor_l2norm_kernel_mp.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/hadoop-hmart-hotelmining/.conda/envs/vilbert/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-i3evi1f1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-i3evi1f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-12qete_t/install-record.txt --single-version-externally-managed --compile --install-headers /home/hadoop-hmart-hotelmining/.conda/envs/vilbert/include/python3.6m/apex Check the logs for full command output.

**Comment by uthynauta** [comment]
Same error in Google Colab, had you found the solution?

CUDA 10.0 / Ubuntu 18.04

**Comment by vokshin** [comment]
Same problem

CUDA 11.6 / Ubuntu 20.04

**Comment by lfwin** [comment]
Same error with:
docker pull pytorch/pytorch:nightly-devel-cuda10.0-cudnn7,
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

Ubuntu 20.04, my GPU card is 3090, and already have cuda 11.3 installed.

**Comment by superhero-7** [comment]
Some error!
Does anyone solve this problem?

**Comment by vokshin** [comment]
Yes, I seem to have solved this problem.

Initially, I needed a specific version of apex, but I used the latest version of pytorch.

After I changed the version of pytorch to an older one, the problem disappeared.

I also installed drivers with cuda version 11.4.

**Comment by superhero-7** [comment]
I seem to have solved this probem too.
My cuda version is 10.0, torch version is 1.2.0, Ubuntu 16.04, **GCC vesion is gcc-6;**

I do like bellow initially:
git clone https://github.com/NVIDIA/apex.git
cd apex
python setup.py install --cuda_ext --cpp_ext
and I got the some error as above.

The I suspect the reason of this error is the code of the apex may need a special gcc version,and the I find a helpful link:
https://github.com/microsoft/Oscar/issues/31
And I follow above link,turn back to a earliy version of apex,do like this:
git clone https://github.com/NVIDIA/apex.git
cd apex
git checkout f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0
python setup.py install --cuda_ext --cpp_ext

And I install apex successfully!
Hope this can help someone struggle with the same error which give me a bad night!!!

**Comment by loveleaves** [comment]
> I seem to have solved this probem too. My cuda version is 10.0, torch version is 1.2.0, Ubuntu 16.04, **GCC vesion is gcc-6;**
> 
> I do like bellow initially: git clone https://github.com/NVIDIA/apex.git cd apex python setup.py install --cuda_ext --cpp_ext and I got the some error as above.
> 
> The I suspect the reason of this error is the code of the apex may need a special gcc version,and the I find a helpful link: [microsoft/Oscar#31](https://github.com/microsoft/Oscar/issues/31) And I follow above link,turn back to a earliy version of apex,do like this: git clone https://github.com/NVIDIA/apex.git cd apex git checkout [f3a960f](https://github.com/NVIDIA/apex/commit/f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0) python setup.py install --cuda_ext --cpp_ext
> 
> And I install apex successfully! Hope this can help someone struggle with the same error which give me a bad night!!!

Thank you! It works!
CUDA 10.0 / Ubuntu 20.04

**Comment by ptrblck** [comment]
Based on the latest comments a commit was found which seems to work with the old CUDA toolkit version.
In case you are running into build issues, please use the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Closing
