### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by ardagun** [NVIDIA/apex#1269]
I got this Runtime Error when I run this code in cmd;
python setup.py install --cuda_ext --cpp_ext

cuda toolkit= 10.2 
python=3.9
gcc=6.3
torch=1.9.0
Windows
 
Any ideas about the solution?

**Comment by zws98** [comment]
Have u solved the problem?

**Comment by ptrblck** [comment]
Unfortunately, not enough information are given in the issue.
As described [here](https://github.com/NVIDIA/apex#experimental-windows) the Windows support is experimental and we recommend to use Linux/Ubuntu with either a source build or via the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Closing
