### ISSUE TITLE
[feature request] implement RMSNorm fused cuda kernel

### ISSUE THREAD

**Issue by stas00** [NVIDIA/apex#1271]
It was identified that the very popular HF Transformers t5-models have a bottleneck of using a custom RMSNorm where normally the efficient LayerNorm is used: https://github.com/huggingface/transformers/issues/14608#issuecomment-1001257392 - in a big part due to inefficient manual up/down casting when using with mixed precision.

Could apex please implement RMSNorm fused cuda kernel and then we could swap it in and give users a much faster experience?

I was trying to hack around it here https://github.com/huggingface/transformers/pull/14656 but I'm not getting any faster with normal pytorch components.

T5 uses a layer_norm which only scales and doesn't shift, which is also known as Root Mean Square Layer Normalization https://arxiv.org/abs/1910.07467 thus varience is calculated w/o mean and there is no bias. Additionally we want to make sure that the accumulation for half-precision inputs is done in fp32, so the original code, which might be easier to understand was:
```
variance = hidden_states.to(torch.float32).pow(2).mean(-1, keepdim=True)
hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
if self.weight.dtype in [torch.float16, torch.bfloat16]:
    hidden_states = hidden_states.to(self.weight.dtype)
```

Here is the full layer as it is now that we want to replace:

https://github.com/huggingface/transformers/blob/3fc221d077a789bbb0c69bf81cff3d976604ed46/src/transformers/models/t5/modeling_t5.py#L237-L255

Here is a good reference implementation of RMSNorm https://github.com/bzhangGo/rmsnorm/blob/master/rmsnorm_torch.py

Thank you!

**Comment by eqy** [comment]
Thanks for opening this issue! I'll take a look at this and report back.

**Comment by stas00** [comment]
was implemented here https://github.com/NVIDIA/apex/pull/1274 - Thank you!
