### ISSUE TITLE
How to use/install an earlier apex GitHub commit?

### ISSUE THREAD

**Issue by phosseini** [NVIDIA/apex#1272]
There is a package I want to use that is implemented based on [fairseq](https://github.com/pytorch/fairseq) toolkit. The package requirement says:

"Please use an earlier commit of Apex - [NVIDIA/apex@4a8c4ac](https://github.com/NVIDIA/apex/commit/4a8c4ac088b6f84a10569ee89db3a938b48922b4)"

Even though I know how to install Apex, I'm not sure if I understand what it means to use an earlier commit of apex and how exactly I can use the commit (e.g., how can I install a commit of a package)? Does it just mean a specific version of apex? And if so, how can I find that specific version from a commit?

**Comment by crcrpar** [comment]
```
$ git clone https://github.com/nvidia/apex
$ cd apex
$ git checkout <commit hash>
$ pip install ... # whatever install command
```

**Comment by phosseini** [comment]
@crcrpar That's all I needed, thanks!
