### ISSUE TITLE
Upload a new version to Conda Forge?

### ISSUE THREAD

**Issue by ebetica** [NVIDIA/apex#1275]
The [version on conda-forge](https://anaconda.org/conda-forge/nvidia-apex/labels) no longer works with the latest versions of PyTorch as it doesn't have [this bugfix](https://github.com/NVIDIA/apex/pull/1049).

**Comment by ptrblck** [comment]
We do not build or upload `apex` to `conda-forge` and this package is thus not supported by us.
Closing.
