### ISSUE TITLE
fp16_optimizer error 

### ISSUE THREAD

**Issue by seongwook-ham** [NVIDIA/apex#129]
![image](https://user-images.githubusercontent.com/21188737/51461394-4c62e300-1da1-11e9-8759-cef0bda7d428.png)

i see very weird phenomeon.
when i run code with sgd,fp16_optimizer and crossentropy loss, following error is printed 

....
Grad overflow on iteration 16
Using dynamic loss scale of 65536.0
17
Traceback (most recent call last):
  File "train_apex.py", line 748, in <module>
    main()
  File "train_apex.py", line 429, in main
    train_time=train(train_loader, model, criterion, optimizer, epoch)
  File "train_apex.py", line 592, in train
    optimizer.step()
  File "/home/hsw-server-ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/optimizers/fp16_optimizer.py", line 160, in step
    grad_norms=norm_groups)
TypeError: step() got an unexpected keyword argument 'grads'

when gradient is being dynamically rescaled, it does not throw error.
 but when gradient overflow is not happend, error is printed.
what error is this?

**Comment by BorisLestsov** [comment]
How did you resolve this issue? I have the same problem.

**Comment by che85** [comment]
I have the same problem. Don't just close issues without commenting on what happened or what you figured out. That doesn't help anyone.

**Comment by che85** [comment]
@BorisLestsov I am not sure which optimizer you are using, but when using the FusedAdam (https://github.com/NVIDIA/apex/blob/master/apex/optimizers/fused_adam.py#L5) it seems to work. 

I tried to use Adam from pytorch, but that's when I ran into the above explained issue.

**Comment by MrRace** [comment]
same problem! New API can not solve the problem，sad!

**Comment by ptrblck** [comment]
`FP16_Optimizer` is deprecated and shouldn't be used anymore.
You can find a transition guide [here](https://nvidia.github.io/apex/amp.html#for-users-of-the-old-fp16-optimizer).

**Comment by seongwook-ham** [comment]
i know but nn dataparallel do not works well with apex amp.
in inference(for quantization issue) and many case(training) we have to use nn dataparallel with apex not distirubuted data parallel.
but amp with nn dataparallel throw error in many case option o2 o3
