### ISSUE TITLE
Could not find `torch.distributed.make_nccl_premul_sum`

### ISSUE THREAD

**Issue by waynehpc** [NVIDIA/apex#1298]
Hey guys,
  I can't find the definition of `torch.distributed.make_nccl_premul_sum`, neither in pytorch/pytorch repo nor apex repo，thanks！
@seryilmaz 
https://github.com/NVIDIA/apex/blob/a47d1a76e705dcb8c886e82205b142c27d6c432e/apex/contrib/optimizers/distributed_fused_lamb.py#L604

**Comment by waynehpc** [comment]
@kexinyu @thorjohnsen @ptrblck

**Comment by ptrblck** [comment]
You would need to use the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) for this feature, while @crcrpar is working on the upstream integration in https://github.com/pytorch/pytorch/pull/81272. Closing

**Comment by waynehpc** [comment]
> You would need to use the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) for this feature, while @crcrpar is working on the upstream integration in [pytorch/pytorch#81272](https://github.com/pytorch/pytorch/pull/81272). Closin

thanks for replying
