### ISSUE TITLE
Error while installing apex on conda environment 

### ISSUE THREAD

**Issue by EliudNGARUIYA** [NVIDIA/apex#1318]
I'm trying to install apex using the following command ` C:\ap\apex>pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .` 
I get the following output:

`C:\Anaconda\envs\layoutlm\lib\site-packages\pip\_internal\commands\install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.2.4 from C:\Anaconda\envs\layoutlm\lib\site-packages\pip (python 3.7)
Processing c:\ap\apex
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Running command python setup.py egg_info

    torch.__version__  = 1.4.0

    running egg_info
    creating C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info
    writing C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info\PKG-INFO
    writing dependency_links to C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info\dependency_links.txt
    writing top-level names to C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info\top_level.txt
    writing manifest file 'C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'C:\Users\NGARUI~1\AppData\Local\Temp\pip-pip-egg-info-l09rz6fj\apex.egg-info\SOURCES.txt'
    C:\Users\NGARUI~1\AppData\Local\Temp\pip-req-build-a64x0_ma\setup.py:109: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Anaconda\envs\layoutlm\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
    Running command 'C:\Anaconda\envs\layoutlm\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NGARUI~1\\AppData\\Local\\Temp\\pip-req-build-a64x0_ma\\setup.py'"'"'; __file__='"'"'C:\\Users\\NGARUI~1\\AppData\\Local\\Temp\\pip-req-build-a64x0_ma\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\NGARUI~1\AppData\Local\Temp\pip-record-lcl2hqvo\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Anaconda\envs\layoutlm\Include\apex'

    torch.__version__  = 1.4.0

    C:\Users\NGARUI~1\AppData\Local\Temp\pip-req-build-a64x0_ma\setup.py:109: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\NGARUI~1\AppData\Local\Temp\pip-req-build-a64x0_ma\setup.py", line 177, in <module>
        check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
      File "C:\Users\NGARUI~1\AppData\Local\Temp\pip-req-build-a64x0_ma\setup.py", line 26, in check_cuda_torch_binary_vs_bare_metal
        raw_output, bare_metal_major, bare_metal_minor = get_cuda_bare_metal_version(cuda_dir)
      File "C:\Users\NGARUI~1\AppData\Local\Temp\pip-req-build-a64x0_ma\setup.py", line 15, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
      File "C:\Anaconda\envs\layoutlm\lib\subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "C:\Anaconda\envs\layoutlm\lib\subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Anaconda\envs\layoutlm\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Anaconda\envs\layoutlm\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: 'C:\Anaconda\envs\layoutlm\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NGARUI~1\\AppData\\Local\\Temp\\pip-req-build-a64x0_ma\\setup.py'"'"'; __file__='"'"'C:\\Users\\NGARUI~1\\AppData\\Local\\Temp\\pip-req-build-a64x0_ma\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\NGARUI~1\AppData\Local\Temp\pip-record-lcl2hqvo\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Anaconda\envs\layoutlm\Include\apex' Check the logs for full command output.
`
Any help will be much appreciated

**Comment by ShenJoe** [comment]
hi, did you solve this problem? I encounter the same one.

**Comment by EliudNGARUIYA** [comment]
> 

I didn't really solve it. I figured using Linux would eliminate the error. So I just changed my environment from Windows to Ubuntu 20.04 and it worked, so changing my environment solved the problem

**Comment by dhkim0225** [comment]
Install cuda-nvcc via conda.
https://anaconda.org/nvidia/cuda-nvcc

Be aware of the version.
