### ISSUE TITLE
FP16 BatchNorm with affine=False error

### ISSUE THREAD

**Issue by h6197627** [NVIDIA/apex#133]
Model converted with network_to_half function fails during forward pass if it has batch normalization layers without affine transformation:

> Traceback (most recent call last):
  File "/home/user/PyTorch/classification.py", line 308, in step
    output = self.model(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/PyTorch/models/ResNet.py", line 124, in forward
    x = self.bn2(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: expected scalar type Half but found Float

Currently I fix it with such hack applied between network_to_half and forward calls:
```
for module in self.model.modules():
    if isinstance(module, torch.nn.modules.batchnorm._BatchNorm):
        # Hack to fix BN fprop without affine transformation
        if module.weight is None:
            module.weight = nn.Parameter(torch.ones(module.running_var.shape, dtype=module.running_var.dtype, device=module.running_var.device), requires_grad=False)
        if module.bias is None:
            module.bias = nn.Parameter(torch.zeros(module.running_var.shape, dtype=module.running_var.dtype, device=module.running_var.device), requires_grad=False)
```

**Comment by mcarilli** [comment]
Should be fixed by https://github.com/NVIDIA/apex/pull/137, reopen if it doesn't work

**Comment by h6197627** [comment]
@mcarilli, yes, it works now, thanks!
However, considering [Nvidia guide](https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html): "**values computed by large reductions should be left in FP32. Examples of this include statistics (mean and variance) computed by batch-normalization**", I am interested does applying my hack is better in terms of training stability than this fix?
Thanks for info!

**Comment by zym1010** [comment]
I'm curious about this as well. seems that #137 sacrifices the stability of no-affine BN.

**Comment by zym1010** [comment]
well, this looks more like a PyTorch bug to me. @h6197627 

1. affine-enabled batchnorm supports cuDNN, and accepts either float or half input.
2. no-affine batchnorm does not support cuDNN, and would fail if module type is float and input type is half.

**Comment by ngimel** [comment]
pytorch implementation of batch normalization converts fp16 values on read, and computes mean and variance in fp32 precision, converting them back on write. That sacrifices very little precision (the difference between computed fp32 mean/var value and nearest representable fp16 value) and is not prone to overflows any more than fp32 computation would be, so pytorch batch norm should be pretty stable. 
I don't remember off the top of my head if cudnn supports affine=False batch norm, if it does, then pytorch could be modified to use it. PRs welcome.

**Comment by h6197627** [comment]
@zym1010, I see. Probably cudnnBatchNormalizationForwardTraining / cudnnBatchNormalizationForwardInference functions do not support running without scale and bias params (for example by passing nullptrs), so it fallback to PyTorch implementation.
However, PyTorch is not declaring mixed precision support, so it is definitely not a bug from PyTorch perspective.
@ngimel, thanks for shedding a light on this question!

**Comment by zym1010** [comment]
@ngimel thx for the explanation! it would be nice to have this explanation around the code, though.
