### ISSUE TITLE
How to install apex using Dockerfile

### ISSUE THREAD

**Issue by pratikchhapolika** [NVIDIA/apex#1341]
I am using this link to install apex:

https://stackoverflow.com/questions/56850711/importerror-please-install-apex-from-https-www-github-com-nvidia-apex-to-use

Here is my Dockerfile code:

    FROM us-docker.pkg.dev/vertex-ai/training/tf-gpu.2-8:latest
    USER root
    CMD python --version
    COPY *.txt /
    RUN git clone https://github.com/NVIDIA/apex
    RUN pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex
    RUN pip3 install accelerate nvidia-ml-py3
    RUN pip3 install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org torch==1.11.0+cu113 torchvision==0.12.0+cu113 
    RUN pip3 install -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org
    COPY *.py /root/
    RUN chmod +x /root/docker_fetch.py
    RUN python3 /root/docker_fetch.py
    # CMD ["python","/root/docker_fetch.py"]
    
    ENTRYPOINT ["/bin/bash"]

Error:

    Step 5/13 : RUN git clone https://github.com/NVIDIA/apex
     ---> Using cache
     ---> 905fc5c65def
    Step 6/13 : RUN pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex
     ---> Running in 87be0839d011
    WARNING: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
    Using pip 22.0.2 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
    Processing /apex
      Preparing metadata (setup.py): started
      Running command python setup.py egg_info
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      full command: /opt/conda/bin/python3.7 -c '
      exec(compile('"'"''"'"''"'"'
      # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
      #
      # - It imports setuptools before invoking setup.py, to enable projects that directly
      #   import from `distutils.core` to work with newer packaging standards.
      # - It provides a clear error message when setuptools is not installed.
      # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
      #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
      #     manifest_maker: standard file '"'"'-c'"'"' not found".
      # - It generates a shim setup.py, for handling setup.cfg-only projects.
      import os, sys, tokenize
      
      try:
          import setuptools
      except ImportError as error:
          print(
              "ERROR: Can not execute `setup.py` since setuptools is not available in "
              "the build environment.",
              file=sys.stderr,
          )
          sys.exit(1)
      
      __file__ = %r
      sys.argv[0] = __file__
      
      if os.path.exists(__file__):
          filename = __file__
          with tokenize.open(__file__) as f:
              setup_py_code = f.read()
      else:
          filename = "<auto-generated setuptools caller>"
          setup_py_code = "from setuptools import setup; setup()"
      
      exec(compile(setup_py_code, filename, "exec"))
      '"'"''"'"''"'"' % ('"'"'/apex/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-o58nirue
      cwd: /apex/
      Preparing metadata (setup.py): finished with status 'error'
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

What is the way out to get apex installed in Docker image?

**Comment by crcrpar** [comment]
I haven't used `us-docker.pkg.dev/vertex-ai/training/tf-gpu.2-8:latest` ever, but the error message indicates the container environment lacks `setuptools`. Did you check your environment has the package?

**Comment by ptrblck** [comment]
In case you are running into build issues, please use the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Closing as no follow-up.
