### ISSUE TITLE
  The following problems occurred when I installed apex

### ISSUE THREAD

**Issue by libingDY** [NVIDIA/apex#1345]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /usr/local/cuda/bin/nvcc -I/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/torch/include -I/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/torch/include/TH -I/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/libing/anaconda3/envs/HVPR/include/python3.7m -c csrc/layer_norm_cuda_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/layer_norm_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -maxrregcount=50 -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=fused_layer_norm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
    csrc/layer_norm_cuda_kernel.cu:4:10: fatal error: ATen/cuda/DeviceUtils.cuh: 没有那个文件或目录
     #include "ATen/cuda/DeviceUtils.cuh"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/libing/anaconda3/envs/HVPR/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-43wye0xe/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-43wye0xe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-1osdfj0q/install-record.txt --single-version-externally-managed --compile --install-headers /home/libing/anaconda3/envs/HVPR/include/python3.7m/apex Check the logs for full command output.

My environment is as follows:
cuda 10.1
pytorch 1.4

**Comment by Ericmututu** [comment]
I meet the same problem, have you solved it ? @[libingDY](https://github.com/libingDY)

**Comment by crcrpar** [comment]
I think that PyTorch is a bit too old to build current apex

**Comment by autumn-city** [comment]
i met the same question, have you solved it?

**Comment by autumn-city** [comment]
> I think that PyTorch is a bit too old to build current apex

Is there any way to allow me to build the old version apex?

**Comment by crcrpar** [comment]
I'd give it a shot to an old commit

**Comment by liu-huilin** [comment]
I meet the same problem too, have you soved it? The Version  of Pytorch is 1.9.0 , and my environment is Ubuntu 20.04.2 LTS

**Comment by ptrblck** [comment]
As @crcrpar said, an older apex commit should work with old PyTorch releases.
In case you are running into build issues, please use the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Closing
