### ISSUE TITLE
Upstream LANS optimizer implementation to Apex

### ISSUE THREAD

**Issue by szhengac** [NVIDIA/apex#1350]
Hi,

I opening this issue to see if Apex is willing take a PR from me on upstreaming the implementation of LANS optimizer https://arxiv.org/pdf/2006.13484.pdf. We have been using this optimizer for several projects at Amazon. It gave me a headache recently due to frequent changes on Pytorch and I had to resolve the conflicts to rebase the branch. If Apex is willing to merge it, I can offload the burden of maintaining our customized branch. Please let me know what do you think. Thanks!

**Comment by ptrblck** [comment]
Closing per https://github.com/NVIDIA/apex/pull/1362#issuecomment-1189924956
