### ISSUE TITLE
Where is the mma_smem_layout.xlsx file?

### ISSUE THREAD

**Issue by terU3760** [NVIDIA/apex#1352]
The comment in the file [smem_tile.h](https://github.com/NVIDIA/apex/blob/master/apex/contrib/csrc/fmha/src/fmha/smem_tile.h) mentioned the file: doc/mma_smem_layout.xlsx. Where is it? Is it an internal document?

**Comment by yjk21** [comment]
Yes, that's unfortunately not publicly available.
But you can find the what the idea behind this is, e.g. [here](https://developer.download.nvidia.com/video/gputechconf/gtc/2020/presentations/s21745-developing-cuda-kernels-to-push-tensor-cores-to-the-absolute-limit-on-nvidia-a100.pdf)
