### ISSUE TITLE
DistributedFusedLamb cannot run using NGC PyTorch 22.03

### ISSUE THREAD

**Issue by sneaxiy** [NVIDIA/apex#1354]
**Describe the Bug**

**Minimal Steps/Code to Reproduce the Bug**
Use NGC PyTorch 22.03 container to run `DistributedFusedLamb` optimizer. The API of `torch.distributed.make_nccl_premul_sum` has been removed in NGC PyTorch 22.03.

**Expected Behavior**
`DistributedFusedLamb` cannot be used in NGC 22.03 PyTorch Container because of the removal of `torch.distributed.make_nccl_premul_sum`.

https://github.com/NVIDIA/apex/blob/master/apex/contrib/optimizers/distributed_fused_lamb.py#L604

**Environment**
NGC 22.03 PyTorch Container

**Comment by ptrblck** [comment]
Thanks for reporting the issue!
The next 22.04 container release will add the missing `torch.distributed.make_nccl_premul_sum` again and should work with this optimizer.
Closing this issue. Please reopen it if you are hitting the issue in the next release.
