### ISSUE TITLE
error: [Errno 2] No such file or directory: 'build\\bdist.win-amd64\\egg\\apex\\contrib\\sparsity\\permutation_search_kernels\\__pycache__\\call_permutation_search _kernels.cpython-38.pyc.2347378509744'

### ISSUE THREAD

**Issue by starstarb** [NVIDIA/apex#1375]
**Describe the Bug**
 I  use         --python setup.py install   but got this error

error: [Errno 2] No such file or directory: 'build\\bdist.win-amd64\\egg\\apex\\contrib\\sparsity\\permutation_search_kernels\\__pycache__\\call_permutation_search _kernels.cpython-38.pyc.2347378509744'

**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**

**Environment**

**Comment by ptrblck** [comment]
Windows support is experimental as described [here](https://github.com/NVIDIA/apex#experimental-windows).
If you are hitting issues with the build steps, we recommend to use the NGC containers, which ship with a pre-built apex.

**Comment by FrenchOldDriver1995** [comment]
cmd+R regedit, change LongPathsEnabled 0 to 1. 
the error's reason is that the file name 'call_permutation...' exceeded the longest file name length.
