### ISSUE TITLE
hey，i have a question：i dont know why the gpu memoty usage is 3 mb or almost 100mb,while gpu util is 0 when i close the program.

### ISSUE THREAD

**Issue by forever10086** [NVIDIA/apex#1377]
**Describe the Bug**

**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**

**Environment**

**Comment by ptrblck** [comment]
Insufficient information in the bug to be actionable. Closing for now, but feel free to reopen it with more information.
