### ISSUE TITLE
Disable TF32 for numerical check of test_pipeline_parallel_fwd_bwd.py

### ISSUE THREAD

**Issue by crcrpar** [NVIDIA/apex#1381]
Numerical check is added in https://github.com/NVIDIA/apex/commit/68440264f3fc564fa53b5a2f286d313774fcfe49.
It turned out that this check requires float32.

cc @Aidyn-A @eqy 

https://github.com/NVIDIA/apex/blob/68440264f3fc564fa53b5a2f286d313774fcfe49/tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py#L143-L150

**Comment by eqy** [comment]
I will check to see if this can be done with the `allow_tf32` flag that already exists.
