### ISSUE TITLE
AMP on .conv3d

### ISSUE THREAD

**Issue by DidierDeschamps** [NVIDIA/apex#140]
Hi,

I am experiencing problems using amp from apex on 3D convolutionnal layers.
I don't think it's working correctly for me.

I didn't observe any improvments using the amp rather than without it.
I ran my model on two titan V one run with amp_handle = amp.init(enabled=True) and one with amp_handle = amp.init(enabled=False).

Alternatively is there a way to plot or log when the FP16 has been used with amp ?

Best

**Comment by mangotree3** [comment]
@mcarilli I have the same question/problem

**Comment by ngimel** [comment]
cudnn (and hence pytorch) does not yet support hmma in 3d convolutions, so you are not going to see noticeable speed-up on them.

**Comment by mkolod** [comment]
BTW by hmma, @ngimel means Tensor Core kernels.

**Comment by DidierDeschamps** [comment]
Thank you for your answer,

Didier Deschamps
