### ISSUE TITLE
how to invoke amp.initialize() and amp.scale_loss() from different module

### ISSUE THREAD

**Issue by kehuanfeng** [NVIDIA/apex#1408]
In some case, building model and training cycle are implemented from seperate modules, so is it possible to invoke amp.initialize() and amp.scale_loss() from seperate modules?

As of now, it reports the following error,

```
RuntimeError: Invoked 'with amp.scale_loss`, but internal Amp state has not been initialized.  model, optimizer = amp.initialize(model, optimizer, opt_level=...) must be called before `with amp.scale_loss`.
```

Can we have a handle which holds the amp state so that we can pass it to the other modules?

**Comment by onceone** [comment]
resolve it now ?
