### ISSUE TITLE
Pytorch 1.11 and 1.12 support

### ISSUE THREAD

**Issue by vince62s** [NVIDIA/apex#1427]
At the moment we are unable to compile with pytorch 1.11 or 1.12

We are stuck to 1.10

Any plan to update ?

Thanks.

**Comment by ptrblck** [comment]
`apex` is compatible with the latest PyTorch releases.
If you have trouble building it from source, we recommend to use the latest PyTorch NGC container from [here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) which comes with the latest PyTorch and apex builds (as well as latest CUDA stack).

**Comment by vince62s** [comment]
sorry my mistake.

**Comment by crcrpar** [comment]
Just so you know, I tried building apex inside `pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel` and I was able to build most extensions while I could not `--nccl_p2p`, `--fast_bottleneck `, and --peer_memory` due to the container's NCCL and cuDNN don't meet the condition of those extensions.

**Comment by ptrblck** [comment]
@vince62s Let us know if this also works for you or please reopen the issue with the error log from your build.

**Comment by vince62s** [comment]
not sure what you mean, I said it was my mistake, I can compile with 1.12 (I was on a previous commit when it failed).
