### ISSUE TITLE
cpp_extension.py:346: UserWarning: Error checking compiler version for cl

### ISSUE THREAD

**Issue by mayii2001** [NVIDIA/apex#1436]
i have install python3.9；torch.__version__  = 1.12.0；cuda11.3；vs studio2019；and added the path of MSVC into the environment variables  path：“C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64”
I just cannot figure out what`s going wrong. It took me a whole afternoon.
 I want to resolve the problem of “No module named 'fused_layer_norm_cuda'” and the Internet told me to get apex of cuda version. Now I stuck again.

**Describe the Bug**
Installing collected packages: apex
  Running command Running setup.py install for apex
  torch.__version__  = 1.12.0
  Compiling cuda extensions with
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2021 NVIDIA Corporation
  Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
  Cuda compilation tools, release 11.3, V11.3.58
  Build cuda_11.3.r11.3/compiler.29745058_0
  from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3/bin

  running install
  D:\evns\transformers\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  running build_ext
  D:\evns\transformers\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  building 'apex_C' extension
  Emitting ninja build file C:\Users\lulum\apex\build\temp.win-amd64-cpython-39\Release\build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  ninja: no work to do.
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\evns\transformers\lib\site-packages\torch\lib /LIBPATH:D:\evns\transformers\libs /LIBPATH:D:\evns\transformers /LIBPATH:D:\evns\transformers\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_apex_C C:\Users\lulum\apex\build\temp.win-amd64-cpython-39\Release\csrc/flatten_unflatten.obj /OUT:build\lib.win-amd64-cpython-39\apex_C.cp39-win_amd64.pyd /IMPLIB:C:\Users\lulum\apex\build\temp.win-amd64-cpython-39\Release\csrc\apex_C.cp39-win_amd64.lib

**Comment by mayii2001** [comment]
fuck it. I reinstall the pytorch1.12 and it is ok. I don`t get why

**Comment by ptrblck** [comment]
Closing as it seems the issue was resolved.
