### ISSUE TITLE
Supported architecture for apex 

### ISSUE THREAD

**Issue by kaggar11** [NVIDIA/apex#1443]
I want to use the apex.contrib.sparsity support for pruning an already trained model for faster inference. Does this support work on architectures other than the NVIDIA Ampere architecture?

**Comment by ptrblck** [comment]
From the [docs](https://github.com/NVIDIA/apex/tree/master/apex/contrib/sparsity#generate-a-sparse-network):
> The following approach serves as a guiding example on how to generate a pruned model that can use Sparse Tensor Cores in the NVIDIA Ampere Architecture. ...

So it seems you need to use an Ampere GPU.

Closing.
