### ISSUE TITLE
[python perf_test_multihead_attn.py bug] fast_multihead_attn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda4blas19_cublasGetErrorEnumE14cublasStatus_t

### ISSUE THREAD

**Issue by songkq** [NVIDIA/apex#1452]
**Describe the Bug**

**Minimal Steps/Code to Reproduce the Bug**
 
`git clone https://github.com/NVIDIA/apex`
`cd apex`
`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--fast_multihead_attn" ./`
`cd apex/contrib/examples/multihead_attn`
`python perf_test_multihead_attn.py`

**Expected Behavior**

Fast Multihead Attention with C++ Implementation
`import fast_multihead_attn`
`ImportError: /workspace/anaconda3/envs/torch1.8.1/lib/python3.6/site-packages/fast_multihead_attn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda4blas19_cublasGetErrorEnumE14cublasStatus_t`

**Environment**

CentOS Linux 7
python3.6.8
gcc-9.2.0
cuda-11.1
cudnn8.2
PyTorch1.8.1
RTX3090

**Comment by crcrpar** [comment]
@songkq it'd be resolved by updating PyTorch.
If it's not feasible, use apex's commit before https://github.com/NVIDIA/apex/pull/1192

**Comment by songkq** [comment]
@crcrpar Thanks for your advices. I have solved the problem by git checkout 1d5f7e55d612da739915f2f63c08b887e960b0e0.
