### ISSUE TITLE
multiple weird sub processes

### ISSUE THREAD

**Issue by hongsukchoi** [NVIDIA/apex#1464]
When I use apex for pytorch data parallel training, multiple sub processes are spawned at GPU
![Screenshot from 2022-08-24 17-56-43](https://user-images.githubusercontent.com/31090011/186531074-d80369c3-3013-4809-9225-6bb00de68401.png)
 
The subprocesses are from pytorch dataloader. But I don't know why they are taking GPU memory. It takes too much memory. 

It happens when running https://github.com/ethnhe/FFB6D.
I didn't have this problem about a month ago. I tried resetting the code to the version of a month ago. Still didn't work. 

Ubuntu 18.04 , the latest pytorch, cuda-11.3, python3.6.9
Tested in two different Ubuntu 18.04 computers. In Ubuntu 20.04, it works.

**Comment by ptrblck** [comment]
`apex.DDP` is deprecated so please use the native `DDP` util.
