### ISSUE TITLE
Use apex with horovod

### ISSUE THREAD

**Issue by lliimsft** [NVIDIA/apex#147]
Hi,

I am wondering if there is any working sample to use `FP16_Optimizer` with horovod for pytorch?  As horovod [`_DistributedOptimizer`](https://github.com/uber/horovod/blob/master/horovod/torch/__init__.py#L42) is derived from `torch.optim.Optimizer`, it is not straightforward to warp it outside `FP16_Optimizer`. 

Any hint would be appreciated. Thanks!

**Comment by ngimel** [comment]
Pytorch has great native distributed support, so we don't work on apex interop with horovod.
