### ISSUE TITLE
amp.initialize(model, opt)  stuck

### ISSUE THREAD

**Issue by empty2enrich** [NVIDIA/apex#1484]
The single-GPU training is normal, but the child process is stuck in amp.initialize during multi-GPU training.

**Minimal Steps/Code to Reproduce the Bug**

        print(f'{self.local_rank}, start init' + '-' * 80)
        self.model, self.optimizer = amp.initialize(self.model, self.optimizer, opt_level='O1')
        print(f'{self.local_rank}, start ddp' + '-' * 80)
        self.model = apex.parallel.DistributedDataParallel(self.model)
        print(f'{self.local_rank}, end ddp' + '-' * 80)

**Expected Behavior**

**Environment**

**Comment by ptrblck** [comment]
`apex.amp` and `apex.DDP` are deprecated, so please use the native PyTorch utils.
