### ISSUE TITLE
RuntimeError: expected scalar but found half float

### ISSUE THREAD

**Issue by avishaked** [NVIDIA/apex#1504]
**While running dream textures in Blender getting a RuntimeError: expected scalar type Half but found Float**

**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**
<I expected to get a AI image texture produced by Dream Texture>

**Environment**
<OS - Windows 11, Python 3.10 (64 bit), NVIDIA GeForce GTX 1660 SUPER. CUDA Cores 1408 -->

**Comment by crcrpar** [comment]
could you be more specific?
I don't get how this is really related to apex

**Comment by avishaked** [comment]
Thanks for your reply.
Nothing to do with apex.
I’ve downloaded from GitHub the “Dream Textures” add-on for Blender 3D
software and installed it.
This add-on allows generating an AI texture images.
While generating an image, there is a Runtime error, which I described and
attached the screenshot of the error.
I need help to solve this problem, please.
Regards
Avi

בתאריך יום ה׳, 6 באוק׳ 2022 ב-0:49 מאת Masaki Kozuki <
***@***.***>:

**Comment by crcrpar** [comment]
As unrelated to apex.
