### ISSUE TITLE
Unknown CUDA arch (9.0) or GPU not supported

### ISSUE THREAD

**Issue by petronny** [NVIDIA/apex#1527]
**Describe the Bug**
When building apex with cuda 11.8 and pytorch 1.12.1, it raises `Unknown CUDA arch (9.0) or GPU not supported`.
And 9.0 does not be listed in https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L1735 . The highest one it 8.9.

**Minimal Steps/Code to Reproduce the Bug**
 
Full build log in a clean archlinux chroot: https://github.com/arch4edu/cactus/actions/runs/3361976764/jobs/5573083014
PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-apex-git

**Comment by ptrblck** [comment]
The issue is expected, since `torch==1.12.1` was released before sm_90 was announced and supported.
Closing

**Comment by kwea123** [comment]
It is easy to solve, just replace the `cpp_extension.py` to the latest. It doesn't throw any error and everything works.

**Comment by morrisalp** [comment]
Note that [this commit](https://github.com/pytorch/pytorch/pull/87736/commits/d523b461b682292f102b2f666bca8bf296e649d0) isn't in the latest stable version torch v1.13.1.
