### ISSUE TITLE
Get error when installing apex from the source

### ISSUE THREAD

**Issue by MHVali** [NVIDIA/apex#1538]
Hi,

I am trying to install apex in my virtual env using the commands you put to install apex from the source. However, I got the following error attached in the picture. Could you please help me resolve this issue?

Error I get: https://drive.google.com/file/d/1GMUqBTfNbNkVAOTR-LWhLdz-z0qOoKcp/view?usp=share_link

Based on the description of the error, it might misses an installation command to install the requirements file like "requirements.txt". I also noticed that the "setup.py" file doesn't have any command related to installation of the "requirements.txt" or "requirements_dev.txt". Am I right?

**Comment by ptrblck** [comment]
Your file is not accessible. Feel free to reopen the issue if you can share more information about the issue you are seeing.
