### ISSUE TITLE
Unable to build apex: "fatal error: cusolverDn.h: No such file or directory"

### ISSUE THREAD

**Issue by vgoklani** [NVIDIA/apex#1572]
We are trying to build `apex` straight from the `pytorch` nightly Docker image primarily to use the pytorch2 compiler:

    ghcr.io/pytorch/pytorch-nightly

Unfortunately the apex build is failing:

    fatal error: cusolverDn.h: No such file or directory

What's the best way of install all the missing CUDA dependencies? It's not clear why the pytorch team would not include them with the nightly image. Thanks

**Comment by godfrey-cw** [comment]
I'm getting the same issue, specifically on the line:
```txt
~/.conda/envs/$MY_ENV/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
```

**Comment by PhoenixZ810** [comment]
> I'm getting the same issue, specifically on the line:
> 
> ```
> ~/.conda/envs/$MY_ENV/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
> ```
I have the same problem. Have you solved it?

**Comment by darshana1406** [comment]
[https://discuss.pytorch.org/t/not-able-to-include-cusolverdn-h/169122](url)
