### ISSUE TITLE
Error when affine flag set to False in apex.parallel.SyncBatchNorm

### ISSUE THREAD

**Issue by mathildecaron31** [NVIDIA/apex#158]
Hi,

I'm having an issue when setting the affine flag to False in apex.parallel.SyncBatchNorm:

This minimal code:
```
import apex
import torch

model = apex.parallel.SyncBatchNorm(100, affine=False).cuda()

data = torch.FloatTensor(torch.randn(4, 100, 14, 14)).cuda()

output = model(data)
```

raises the following error:
`
Traceback (most recent call last):                                             
  File "minimal.py", line 96, in <module>                                      
    main()                                                                     
  File "minimal.py", line 44, in main                                          
    output = model(data)                                                       
  File "~/.conda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)                                    
  File "~/.conda/envs/torch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/optimized_sync_batchnorm.py", line 80, in forward
    return SyncBatchnormFunction.apply(input, self.weight, self.bias, self.running_mean, self.running_var, self.eps, self.training or not self.track_running_stats, exponential_average_factor, self.process_group, self.channel_last)
  File "~/.conda/envs/torch/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/optimized_sync_batchnorm_kernel.py", line 61, in forward
    out = syncbn.batchnorm_forward(input, mean, inv_std, weight, bias)         
TypeError: batchnorm_forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor) -> at::Tensor
`

My environment is the following:

Ubuntu 18.04
Cuda 9.0
Pytorch version 1.0
I installed apex with `--cuda_ext`

This code is working just fine when the affine flag is set to True (default).

Thank you so much in advance for your help.

**Comment by mcarilli** [comment]
@jjsjann123 have you seen this error?

**Comment by jjsjann123** [comment]
This should be supported, let me take a look

**Comment by jjsjann123** [comment]
I can't repro this with ToT apex.
I recently fixed a bug with SyncBatchNorm affine=False ~ at the end of January. I can repro this bug with commit `aed3086aadd`.

Try to merge ToT apex, or cherry pick https://github.com/NVIDIA/apex/pull/143

**Comment by mcarilli** [comment]
Merged https://github.com/NVIDIA/apex/pull/143.
