### ISSUE TITLE
Installation failed    cc1plus: fatal error: cuda_runtime.h

### ISSUE THREAD

**Issue by wpumain** [NVIDIA/apex#1591]
I want to install apes in anaconda's virtual environment.
My installation environment is:
cuda-nvcc                 11.3.58
cudatoolkit               11.3        
pytorch                     1.10.0    
torchvision               0.11.1

When I execute the Apex installation command, the following error occurs:

cc1plus: fatal error: cuda_runtime.h:No file or directory
compilation terminated.
error: command '/home/wpp/anaconda3/envs/RK-Net/bin/nvcc' failed with exit status 1
Running setup.py install for apex ... error

What may be the reason for the installation failure?

**Comment by ptrblck** [comment]
Your CUDA toolkit seems to be missing some header, which should be located in e.g.
```
/usr/local/cuda-11.3/targets/x86_64-linux/include/cuda_runtime.h
```
or another folder in case you have changed the install location.

In case you have trouble building apex from source we recommend using the NGC containers from [here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) which come with a pre-built PyTorch and apex release.

**Comment by ptrblck** [comment]
Installing the `cuda` conda binary is not sufficient and you would need to install a full CUDA toolkit: https://developer.nvidia.com/cuda-downloads

**Comment by wpumain** [comment]
But with this installation from https://developer.nvidia.com/cuda-downloads, cuda will be installed in the base environment instead of the virtual environment of conda?

**Comment by 18979705623** [comment]
I encountered the same problem when installing apex, did you solve it? And can you give me some help?

**Comment by HaikuoLi** [comment]
> I ran:
> 
> ```
> conda install nvidia::cuda-cudart-dev
> ```
> 
> to add this include to my conda environment.

Thank you! It works quite well this way!

**Comment by RobotWJL** [comment]
> > I ran:
> > ```
> > conda install nvidia::cuda-cudart-dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to add this include to my conda environment.
> 
> Thank you! It works quite well this 
感谢！是有效的，本人是cuda11.7.1的，在进行自动安装时是安装cuda12.x的包，因此在https://anaconda.org/nvidia/cuda-cudart-dev进行了选择，选择对应的版本并进行安装，最终有效解决。感谢

**Comment by FogSue** [comment]
> > > I ran:
> > > ```
> > > conda install nvidia::cuda-cudart-dev
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to add this include to my conda environment.
> > 
> > 
> > Thank you! It works quite well this
> > 感谢！是有效的，本人是cuda11.7.1的，在进行自动安装时是安装cuda12.x的包，因此在[https://anaconda.org/nvidia/cuda-cudart-dev进行了选择，选择对应的版本并进行安装，最终有效解决。感谢](https://anaconda.org/nvidia/cuda-cudart-dev%E8%BF%9B%E8%A1%8C%E4%BA%86%E9%80%89%E6%8B%A9%EF%BC%8C%E9%80%89%E6%8B%A9%E5%AF%B9%E5%BA%94%E7%9A%84%E7%89%88%E6%9C%AC%E5%B9%B6%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85%EF%BC%8C%E6%9C%80%E7%BB%88%E6%9C%89%E6%95%88%E8%A7%A3%E5%86%B3%E3%80%82%E6%84%9F%E8%B0%A2)

您好，我也需要下载历史版本（12.1.1），但访问被拒绝（You don't have permission to view this page.），请问安装历史版本的命令是什么？

**Comment by FogSue** [comment]
> > > I ran:
> > > ```
> > > conda install nvidia::cuda-cudart-dev
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to add this include to my conda environment.
> > 
> > 
> > Thank you! It works quite well this
> > 感谢！是有效的，本人是cuda11.7.1的，在进行自动安装时是安装cuda12.x的包，因此在[https://anaconda.org/nvidia/cuda-cudart-dev进行了选择，选择对应的版本并进行安装，最终有效解决。感谢](https://anaconda.org/nvidia/cuda-cudart-dev%E8%BF%9B%E8%A1%8C%E4%BA%86%E9%80%89%E6%8B%A9%EF%BC%8C%E9%80%89%E6%8B%A9%E5%AF%B9%E5%BA%94%E7%9A%84%E7%89%88%E6%9C%AC%E5%B9%B6%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85%EF%BC%8C%E6%9C%80%E7%BB%88%E6%9C%89%E6%95%88%E8%A7%A3%E5%86%B3%E3%80%82%E6%84%9F%E8%B0%A2)

已解决，谢谢！

**Comment by ai-nikolai** [comment]
> conda install nvidia::cuda-cudart-dev

@sherwoac this seems to not have worked anymore... (as of October 2025). Do you know how this could still work; or how to best check?
