### ISSUE TITLE
HELP!!!!, RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by qqqqhhqq** [NVIDIA/apex#1592]
![image](https://user-images.githubusercontent.com/42577899/219263729-3fd9c5b2-c681-481f-8a54-b7e6183a7257.png)

**Comment by ptrblck** [comment]
Based on the error message it seems you might have built `apex` for another GPU architecture.
In case you have trouble building apex from source we recommend using the NGC containers from [here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) which come with a pre-built PyTorch and apex release.

Closing
