### ISSUE TITLE
Dockerfile doesn't work

### ISSUE THREAD

**Issue by zifeis** [NVIDIA/apex#16]
Hi,

I noticed that the url inside Dockerfile is not accessible:

FROM gitlab-dl.nvidia.com:5005/dgx/pytorch:18.04-py3-devel

Could you help to fix it? Thanks

Best,
Vincent

**Comment by mcarilli** [comment]
Hi zifeis, 

Thank you for catching this.  I intended the Dockerfile to be a template where you filled in the FROM line with whatever base image you wanted.  I was testing it with one of our internal images, and forgot to revert my own FROM.  

I've updated the examples/docker directory with more comprehensive information on working with Apex and docker.  Let me know if this doesn't provide what you need.

Regards,
Michael

**Comment by cliffwoolley** [comment]
See also https://github.com/NVIDIA/apex/pull/17

**Comment by mcarilli** [comment]
Also, Apex is now Python-only, so it should install within containers that do not have nvcc.
