### ISSUE TITLE
SyncBN for nn.DataParallel

### ISSUE THREAD

**Issue by FabianIsensee** [NVIDIA/apex#160]
Hi,
I would very much like to use SyncBN, but would like to avoid going through the hassle of learning how to use DDP on my local computer. Is it possible to get your SyncBN implementation working with nn.DataParallel? If not I think this could be a nice addition to apex :-)
Best,
Fabian

**Comment by mcarilli** [comment]
@jjsjann123 Does syncbn currently support DataParallel?

In general, though, I must warn you we find DistributedDataParallel preferable...

**Comment by jjsjann123** [comment]
Our implementation does not support DataParallel yet.
We rely on torch distributed for synchronization between processes, currently we are not planning to extend that to support DP.

**Comment by FabianIsensee** [comment]
HI, thank you so much for the clarification! I can see the benefits of DPP and will convert my models to use this instead of nn.DataParallel.
SyncBN seems to be very tightly integrated with torch.distributed, so I can understand this decision. Once again, thanks! You are doing great work!
Best,
Fabian
