### ISSUE TITLE
No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by alvin-leong** [NVIDIA/apex#161]
I am using apex on Google Colab. It managed to install with cuda and cpp.

However, I am encountering this problem when calling fused_layer_norm_cuda: "No module named 'fused_layer_norm_cuda'"

**Comment by alvin-leong** [comment]
Here is my Colab notebook: https://colab.research.google.com/drive/1mzz-uyc1tq0rgm5sF5JC9s3hxlMmuHVp

As you can see, the installation seems fine.

However, you can scroll all the way down where it reports this error.

**Comment by FelixAbrahamsson** [comment]
Are you sure you have Cuda 9 installed? I had the same problem because I had Cuda 8 installed on my machine, but Cuda 9 via Pytorch (at least I think that's why).

**Comment by agemagician** [comment]
I actually have the same problem. I have cuda 9 and working:

 ```
 File "/home/agemagician/anaconda3/envs/tensorflow/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 126, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/home/agemagician/anaconda3/envs/tensorflow/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
```

**Comment by agemagician** [comment]
When I tried the solution here:
https://github.com/NVIDIA/apex/issues/156#issuecomment-465301976

But now I got a different error:

```
  File "/home/agemagician/anaconda3/envs/tensorflow/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/normalization/fused_layer_norm.py", line 126, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/home/agemagician/anaconda3/envs/tensorflow/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/agemagician/anaconda3/envs/tensorflow/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
```

**Comment by thomwolf** [comment]
I am also facing this issue on a clean install. Python 3.6, pytorch 1.0.1.post2 (installed with conda). GPU V100.

**Comment by thomwolf** [comment]
Ok got it `nvcc` was missing and the install was not installing cuda extensions (check for a message at the very beginning of the installation).
Be sure to have the CUDA Toolkit installed: https://developer.nvidia.com/cuda-downloads

**Comment by agemagician** [comment]
I actually have it:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88
```

But still have the error.

**Comment by knrd** [comment]
I have also facing same problem (`ModuleNotFoundError: No module named 'fused_layer_norm_cuda'`) on https://colab.research.google.com/

I have successfully installed apex:
```
! git clone https://github.com/NVIDIA/apex.git
% cd apex
! python setup.py install --cuda_ext --cpp_ext
! pip install .
%cd ..
```

and I'm able to load `FusedLayerNorm`:
```
! nvcc --version
import apex
from apex.normalization.fused_layer_norm import FusedLayerNorm
print(dir(FusedLayerNorm))
```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_get_name', '_load_from_state_dict', '_named_members', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_slow_forward', '_tracing_name', '_version', 'add_module', 'apply', 'buffers', 'children', 'cpu', 'cuda', 'double', 'dump_patches', 'eval', 'extra_repr', 'float', 'forward', 'half', 'load_state_dict', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'parameters', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_parameter', 'reset_parameters', 'share_memory', 'state_dict', 'to', 'train', 'type', 'zero_grad']
```

but I'm getting error regarding `fused_layer_norm_cuda`:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-33-dec9113144dd> in <module>()
----> 1 model = BertForTokenClassification.from_pretrained("bert-base-uncased", num_labels=len(tag2idx))

/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in from_pretrained(cls, pretrained_model_name_or_path, state_dict, cache_dir, from_tf, *inputs, **kwargs)
    579         logger.info("Model config {}".format(config))
    580         # Instantiate model.
--> 581         model = cls(config, *inputs, **kwargs)
    582         if state_dict is None and not from_tf:
    583             weights_path = os.path.join(serialization_dir, WEIGHTS_NAME)

/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config, num_labels)
   1097         super(BertForTokenClassification, self).__init__(config)
   1098         self.num_labels = num_labels
-> 1099         self.bert = BertModel(config)
   1100         self.dropout = nn.Dropout(config.hidden_dropout_prob)
   1101         self.classifier = nn.Linear(config.hidden_size, num_labels)

/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config)
    683     def __init__(self, config):
    684         super(BertModel, self).__init__(config)
--> 685         self.embeddings = BertEmbeddings(config)
    686         self.encoder = BertEncoder(config)
    687         self.pooler = BertPooler(config)

/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config)
    245         # self.LayerNorm is not snake-cased to stick with TensorFlow model variable name and be able to load
    246         # any TensorFlow checkpoint file
--> 247         self.LayerNorm = BertLayerNorm(config.hidden_size, eps=1e-12)
    248         self.dropout = nn.Dropout(config.hidden_dropout_prob)
    249 

/usr/local/lib/python3.6/dist-packages/apex/normalization/fused_layer_norm.py in __init__(self, normalized_shape, eps, elementwise_affine)
    124 
    125         global fused_layer_norm_cuda
--> 126         fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
    127 
    128         if isinstance(normalized_shape, numbers.Integral):

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
```

**Comment by AlexanderYogurt** [comment]
I got this error as well.

My nvcc:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by mcarilli** [comment]
@knrd In your install command:
```
! git clone https://github.com/NVIDIA/apex.git
% cd apex
! python setup.py install --cuda_ext --cpp_ext
! pip install .
%cd ..
```
why are you doing a `pip install .`?  I believe the `pip install .` will silently rerun the setup.py but without the --cuda_ext and --cpp_ext options, which I suspect is the source of your error.

Try a clean reinstall as described in https://github.com/NVIDIA/apex/issues/156#issuecomment-465301976, then reinstall with simply `python setup.py install --cuda_ext --cpp_ext` (don't additionally do the `pip install .`).  If you prefer to use pip over setuptools, you can use this command INSTEAD: 
```
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
(thanks to @syed-ahmed for this snippet).

@alvin-leong @AlexanderYogurt could this also be the source of your errors?

**Comment by alvin-leong** [comment]
I did not do

`! pip install .`

So that was not the cause of my problem.

However, I did try to install using pip instad of setuptools:

`!pip install -e "/content/apex" --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"`

It worked! Thanks!

**Comment by perrystephenson** [comment]
Just dropped in to say that using the `pip` installer solved the problem for me too. 

Running on Ubuntu via Databricks, just in case anyone else is having trouble this is how I got it working:

```
%sh
/databricks/python3/bin/pip install --upgrade --force-reinstall torch torchvision

cd /path/to/apex
rm -rf build
/databricks/python3/bin/pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

/databricks/python3/bin/pip install pytorch-pretrained-bert
```

**Comment by zzj0402** [comment]
```git clone https://github.com/NVIDIA/apex.git && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .```

**Comment by sandycancode** [comment]
Was constantly running into

> I am using apex on Google Colab. It managed to install with cuda and cpp.
> 
> However, I am encountering this problem when calling fused_layer_norm_cuda: "No module named 'fused_layer_norm_cuda'"

I faced the exact same issue in Colab even after following the solution [here](https://github.com/NVIDIA/apex/issues/161#issuecomment-466611317), after which I figured out (atleast in my case) that the issue was due to the CUDA version dissimilarity between PyTorch(9.2) and Colab(10.1). I then reinstalled PyTorch with CUDA 10.1 using this command 

`pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

And then it worked fine!!

**Comment by Two222** [comment]
> I'm also facing the same problem (`ModuleNotFoundError: No module named 'fused_layer_norm_cuda'`) on https://colab.research.google.com/
> 
> I have successfully installed apex:
> 
> ```
> ! git clone https://github.com/NVIDIA/apex.git
> % cd apex
> ! python setup.py install --cuda_ext --cpp_ext
> ! pip install .
> %cd ..
> ```
> 
> and I'm able to load `FusedLayerNorm`:
> 
> ```
> ! nvcc --version
> import apex
> from apex.normalization.fused_layer_norm import FusedLayerNorm
> print(dir(FusedLayerNorm))
> ```
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130
> ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_get_name', '_load_from_state_dict', '_named_members', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_slow_forward', '_tracing_name', '_version', 'add_module', 'apply', 'buffers', 'children', 'cpu', 'cuda', 'double', 'dump_patches', 'eval', 'extra_repr', 'float', 'forward', 'half', 'load_state_dict', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'parameters', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_parameter', 'reset_parameters', 'share_memory', 'state_dict', 'to', 'train', 'type', 'zero_grad']
> ```
> 
> but I'm getting error regarding `fused_layer_norm_cuda`:
> 
> ```
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-33-dec9113144dd> in <module>()
> ----> 1 model = BertForTokenClassification.from_pretrained("bert-base-uncased", num_labels=len(tag2idx))
> 
> /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in from_pretrained(cls, pretrained_model_name_or_path, state_dict, cache_dir, from_tf, *inputs, **kwargs)
>     579         logger.info("Model config {}".format(config))
>     580         # Instantiate model.
> --> 581         model = cls(config, *inputs, **kwargs)
>     582         if state_dict is None and not from_tf:
>     583             weights_path = os.path.join(serialization_dir, WEIGHTS_NAME)
> 
> /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config, num_labels)
>    1097         super(BertForTokenClassification, self).__init__(config)
>    1098         self.num_labels = num_labels
> -> 1099         self.bert = BertModel(config)
>    1100         self.dropout = nn.Dropout(config.hidden_dropout_prob)
>    1101         self.classifier = nn.Linear(config.hidden_size, num_labels)
> 
> /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config)
>     683     def __init__(self, config):
>     684         super(BertModel, self).__init__(config)
> --> 685         self.embeddings = BertEmbeddings(config)
>     686         self.encoder = BertEncoder(config)
>     687         self.pooler = BertPooler(config)
> 
> /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config)
>     245         # self.LayerNorm is not snake-cased to stick with TensorFlow model variable name and be able to load
>     246         # any TensorFlow checkpoint file
> --> 247         self.LayerNorm = BertLayerNorm(config.hidden_size, eps=1e-12)
>     248         self.dropout = nn.Dropout(config.hidden_dropout_prob)
>     249 
> 
> /usr/local/lib/python3.6/dist-packages/apex/normalization/fused_layer_norm.py in __init__(self, normalized_shape, eps, elementwise_affine)
>     124 
>     125         global fused_layer_norm_cuda
> --> 126         fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
>     127 
>     128         if isinstance(normalized_shape, numbers.Integral):
> 
> /usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
>     124                 break
>     125             level += 1
> --> 126     return _bootstrap._gcd_import(name[level:], package, level)
>     127 
>     128 
> 
> /usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)
> 
> /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)
> 
> /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)
> 
> ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
> ```

@knrd hello,have solved this problem?

**Comment by YutongWang1216** [comment]
Copied from [https://github.com/NVIDIA/apex/issues/116](https://github.com/NVIDIA/apex/issues/116):

> It's appearing that the lib changed its name to pytorch extension => https://pypi.org/project/pytorch-extension/

So it can be solved by running this:
`pip install pytorch-extension`

**Comment by charlesxu90** [comment]
Install apex following the official README solves this problem.

```shell
git clone https://github.com/NVIDIA/apex
cd apex
# if pip >= 23.1 (ref: https://pip.pypa.io/en/stable/news/#v23-1) which supports multiple `--config-settings` with the same key... 
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./

```

**Comment by rongaoli** [comment]
> 复制自#116：
> 
> > 看来该库已名为更 pytorch 扩展 => https://pypi.org/project/pytorch-extension/
> 
> 所以可以通过运行以下命令来解决： `pip install pytorch-extension`

It works

**Comment by Pinging-ZJU** [comment]
I solved this problem by rolling back the code version to the old one (23.05). 

git checkout 0da3ffb

pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

**Comment by ajindal1** [comment]
Starting to seeing this issue after updating the version from 23.05 to 23.08. Realized that my pip version is greater than 23.1 and hence needed to update my installation command. The installation command which resolved the issue for me and is present on the README page is:
# if pip >= 23.1 (ref: https://pip.pypa.io/en/stable/news/#v23-1) which supports multiple `--config-settings` with the same key... 
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
# otherwise
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./

Another thing which I noticed recently was that without adding --no-build-isolation flag I was getting packaging module not found error, this was the issue when I updated my version from 23.05 to 23.08.

**Comment by cs-wangfeng** [comment]
> Starting to seeing this issue after updating the version from 23.05 to 23.08. Realized that my pip version is greater than 23.1 and hence needed to update my installation command. The installation command which resolved the issue for me and is present on the README page is:
> 
> ```
> # if pip >= 23.1 (ref: https://pip.pypa.io/en/stable/news/#v23-1) which supports multiple `--config-settings` with the same key... 
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
> # otherwise
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```
> 
> Another thing which I noticed recently was that without adding --no-build-isolation flag I was getting packaging module not found error, this was the issue when I updated my version from 23.05 to 23.08.

My pip version is 23.3.1, so I used `pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./` and managed to install apex.
However, when I run code that utilizes the apex library, I get these error info:
```shell
Traceback (most recent call last):
  File ".../VALOR/./train.py", line 88, in <module>
    main(args)
  File ".../VALOR/./train.py", line 55, in main
    model = VALOR.from_pretrained(opts,checkpoint)
  File ".../VALOR/model/modeling.py", line 109, in from_pretrained
    model = cls(opts, *inputs, **kwargs)
  File ".../VALOR/model/pretrain.py", line 67, in __init__
    super().__init__(opts)
  File ".../VALOR/model/modeling.py", line 328, in __init__
    self.load_ast_model(base_cfg,config)
  File ".../VALOR/model/modeling.py", line 609, in load_ast_model
    self.audio_encoder = TransformerEncoder(model_cfg_audio, mode='prenorm')
  File ".../VALOR/model/transformer.py", line 149, in __init__
    layer = TransformerLayer(config, mode)
  File ".../VALOR/model/transformer.py", line 62, in __init__
    self.layernorm1 = LayerNorm(config.hidden_size, eps=1e-12)
  File ".../anaconda3/envs/valor1/lib/python3.9/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File ".../anaconda3/envs/valor1/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
```
The software versions in my conda environment are as follows:
```shell
# packages in environment at .../anaconda3/envs/valor1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
apex                      0.1                      pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
boto3                     1.34.34                  pypi_0    pypi
botocore                  1.34.34                  pypi_0    pypi
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cudatoolkit               11.3.1               h2bc3f7f_2    defaults
cycler                    0.12.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
easydict                  1.11                     pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.47.2                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                      pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
ipdb                      0.13.13                  pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    https://repo.anaconda.com/pkgs/main
lerc                      4.0.0                h27087fc_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libpng                    1.6.42               h2797004_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuv                     1.46.0               hd590300_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.12.4               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               17.0.6               h4dfa4b3_0    conda-forge
matplotlib                3.8.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mkl                       2021.4.0           h8d4b97c_729    conda-forge
mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
mkl_random                1.2.2            py39hde0f152_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.24.3           py39h14f4228_0    defaults
numpy-base                1.24.3           py39h31eccc5_0    defaults
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   1.1.1w               h7f8727e_0    https://repo.anaconda.com/pkgs/main
packaging                 23.2                     pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pillow                    9.4.0            py39h2320bf1_1    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.43                   pypi_0    pypi
protobuf                  4.25.2                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.9.12               h12debd9_1    https://repo.anaconda.com/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.1          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
regex                     2023.12.25               pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
s3transfer                0.10.0                   pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.44.2               h2c6b66d_0    conda-forge
stack-data                0.6.3                    pypi_0    pypi
tbb                       2021.11.0            h00ab1b0_1    conda-forge
tensorboardx              2.6.2.2                  pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torchaudio                0.10.1               py39_cu113    pytorch
torchvision               0.11.2               py39_cu113    pytorch
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.14.1                   pypi_0    pypi
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h04d1e81_0    https://repo.anaconda.com/pkgs/main
urllib3                   1.26.18                  pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by Wuziyi616** [comment]
The `pip install` command in the README doesn't work for me. Somehow I have to use `python setup.py install --cuda_ext --cpp_ext` to recognize the `--cuda_ext` flag and detect my `nvcc`. Just in case anyone meets the same situation.

**Comment by DBtxy** [comment]
> > I'm also facing the same problem (`ModuleNotFoundError: No module named 'fused_layer_norm_cuda'`) on https://colab.research.google.com/
> > I have successfully installed apex:
> > ```
> > ! git clone https://github.com/NVIDIA/apex.git
> > % cd apex
> > ! python setup.py install --cuda_ext --cpp_ext
> > ! pip install .
> > %cd ..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I'm able to load `FusedLayerNorm`:
> > ```
> > ! nvcc --version
> > import apex
> > from apex.normalization.fused_layer_norm import FusedLayerNorm
> > print(dir(FusedLayerNorm))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2018 NVIDIA Corporation
> > Built on Sat_Aug_25_21:08:01_CDT_2018
> > Cuda compilation tools, release 10.0, V10.0.130
> > ['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_get_name', '_load_from_state_dict', '_named_members', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_slow_forward', '_tracing_name', '_version', 'add_module', 'apply', 'buffers', 'children', 'cpu', 'cuda', 'double', 'dump_patches', 'eval', 'extra_repr', 'float', 'forward', 'half', 'load_state_dict', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'parameters', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_parameter', 'reset_parameters', 'share_memory', 'state_dict', 'to', 'train', 'type', 'zero_grad']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but I'm getting error regarding `fused_layer_norm_cuda`:
> > ```
> > ---------------------------------------------------------------------------
> > ModuleNotFoundError                       Traceback (most recent call last)
> > <ipython-input-33-dec9113144dd> in <module>()
> > ----> 1 model = BertForTokenClassification.from_pretrained("bert-base-uncased", num_labels=len(tag2idx))
> > 
> > /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in from_pretrained(cls, pretrained_model_name_or_path, state_dict, cache_dir, from_tf, *inputs, **kwargs)
> >     579         logger.info("Model config {}".format(config))
> >     580         # Instantiate model.
> > --> 581         model = cls(config, *inputs, **kwargs)
> >     582         if state_dict is None and not from_tf:
> >     583             weights_path = os.path.join(serialization_dir, WEIGHTS_NAME)
> > 
> > /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config, num_labels)
> >    1097         super(BertForTokenClassification, self).__init__(config)
> >    1098         self.num_labels = num_labels
> > -> 1099         self.bert = BertModel(config)
> >    1100         self.dropout = nn.Dropout(config.hidden_dropout_prob)
> >    1101         self.classifier = nn.Linear(config.hidden_size, num_labels)
> > 
> > /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config)
> >     683     def __init__(self, config):
> >     684         super(BertModel, self).__init__(config)
> > --> 685         self.embeddings = BertEmbeddings(config)
> >     686         self.encoder = BertEncoder(config)
> >     687         self.pooler = BertPooler(config)
> > 
> > /usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py in __init__(self, config)
> >     245         # self.LayerNorm is not snake-cased to stick with TensorFlow model variable name and be able to load
> >     246         # any TensorFlow checkpoint file
> > --> 247         self.LayerNorm = BertLayerNorm(config.hidden_size, eps=1e-12)
> >     248         self.dropout = nn.Dropout(config.hidden_dropout_prob)
> >     249 
> > 
> > /usr/local/lib/python3.6/dist-packages/apex/normalization/fused_layer_norm.py in __init__(self, normalized_shape, eps, elementwise_affine)
> >     124 
> >     125         global fused_layer_norm_cuda
> > --> 126         fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
> >     127 
> >     128         if isinstance(normalized_shape, numbers.Integral):
> > 
> > /usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
> >     124                 break
> >     125             level += 1
> > --> 126     return _bootstrap._gcd_import(name[level:], package, level)
> >     127 
> >     128 
> > 
> > /usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)
> > 
> > /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)
> > 
> > /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)
> > 
> > ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
> > ```
> 
> [@knrd](https://github.com/knrd) hello,have solved this problem?

Is there any solution?

**Comment by xyzjin** [comment]
pip install -v --no-build-isolation --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

**Comment by adkkml** [comment]
> Copied from [#116](https://github.com/NVIDIA/apex/issues/116):
> 
> > It's appearing that the lib changed its name to pytorch extension => https://pypi.org/project/pytorch-extension/
> 
> So it can be solved by running this: `pip install pytorch-extension`

if install this the Apex is gone (requested to be install Apex again)?
