### ISSUE TITLE
Does torch 2.0 is supported with apex.contrib.sparsity in current release?

### ISSUE THREAD

**Issue by pjh4993** [NVIDIA/apex#1629]
**Describe the Bug**

Version check of torch in apex/contrib/sparsity/permutation_lib.py:812 only matched with torch version under 2.0
```
print("[build_fx_graph] The torch version is: {}, version major is: {}, version minor is: {}, version minimum is: {}".format(torch_version, torch_version_major, torch_version_minor, torch_version_minimum))
if torch_version_major >= 1 and torch_version_minor >= 8:
    print("[build_fx_graph] The Torch.FX is supported.")
else:    # Torch.FX is introduced in torch 1.8.0
    print("[build_fx_graph] The Torch.FX is not supported. So cannot build the Torch.FX graph.")
    success = False
    network_fx_graph = {}
    return network_fx_graph, success
```

Is this behavior is intended to block using with torch2.0? I'm having some issues around [find_real_parents](https://github.com/NVIDIA/apex/blob/57057e2fcf1c084c0fcc818f55c0ff6ea1b24ae2/apex/contrib/sparsity/permutation_lib.py#L744) function in permutation_lib.py while using torch2.0. It seems current implementation fails to find real parent node. I'll open new issue about this later. 

**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**

**Environment**

Linux : ubuntu20.04
NVIDIA driver : 525.85.12
GPU : A100 80GB

[pip3] numpy==1.23.5
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0+cu118
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118

**Comment by crcrpar** [comment]
hi @pjh4993, FYI, there's on-going pull request where I'm asking the same: https://github.com/NVIDIA/apex/pull/1628#discussion_r1151314097
