### ISSUE TITLE
Using FusedAdam without fp16 optimizer

### ISSUE THREAD

**Issue by thomwolf** [NVIDIA/apex#164]
`FusedAdam.step()` expects to receive not-None `grad_norms` when a parameters' group has a `max_grad_norm` value (see [here](https://github.com/NVIDIA/apex/blob/master/apex/optimizers/fused_adam.py#L102)).

These `grad_norms` are computed by the FP16 otpimizer [here](https://github.com/NVIDIA/apex/blob/69907b807886846b6cf7320b5b1e104b2d18c1ae/apex/optimizers/fp16_optimizer.py#L158) when we use the FP16 Optimizer in conjonction with FusedAdam.

It would be nice to have a fallback in `FusedAdam` so that this optimizer can be used without fp16.

Currently this fails as:
```bash
clip = ((grad_norm / scale) + 1e-6) / group['max_grad_norm']
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by ngimel** [comment]
But if you are not computing grad_norms, your group['max_grad_norm'] should be 0 and you never should enter this conditional? So what you want is checking both that `group['max_grad_norm']` is >0, and that `grad_norm` is not `None`?

**Comment by thomwolf** [comment]
So in this case (FusedAdam + fp32), I should do gradient clipping manually, right?

**Comment by ngimel** [comment]
You could compute grad_norm manually and pass it to FusedAdam so that it could do the clipping - that should be faster than separate gradient clipping.

**Comment by thomwolf** [comment]
Got it, thanks @ngimel!

**Comment by arianhosseini** [comment]
I'm getting this error using the FudesAdam with fp16 optimizer. Any idea why?
