### ISSUE TITLE
PyTorch FSDP compatibility with Apex

### ISSUE THREAD

**Issue by conceptofmind** [NVIDIA/apex#1655]
Hi all,

I was wondering if you could confirm that PyTorch FSDP, `from torch.distributed.fsdp import FullyShardedDataParallel as FSDP`, was compatible with Apex's Tensor and Sequence Parallelism. So that one could use Column and Row Linear with Sequence Parallelism enabled in conjunction with the FSDP model wrapper.

Thank you,

Enrico

**Comment by crcrpar** [comment]
I personally have never tried that combo.

There's PyTorch tensor parallelism: https://pytorch.org/docs/stable/distributed.tensor.parallel.html, just fyi

**Comment by conceptofmind** [comment]
> I personally have never tried that combo.
> 
> There's PyTorch tensor parallelism: https://pytorch.org/docs/stable/distributed.tensor.parallel.html, just FYI

Thank you for the response.

I did review the PyTorch documentation on TP before posting and saw they had an experimental API. They do not have out-of-box support for sequence parallelism and parallel vocab embeddings. It is a bit unclear from their documentation what will be compatible. I will make a post on the PyTorch forum as well.

I will leave this issue open until I can further validate/invalidate the approach.

Best,

Enrico

**Comment by conceptofmind** [comment]
TP and FSDP do work together properly when utilizing the correct wrapper in PyTorch.
