### ISSUE TITLE
Implicit Cuda sync in fp16 not present in fp32 

### ISSUE THREAD

**Issue by Delaunay** [NVIDIA/apex#172]
## Short

I think there might be a an implicit sync when training the model in fp16. 
I am not sure if this is the expected behavior or if it is a bug.

## Description of the issue

`amp_sync.py` is a  script that computes the runtime on the CPU side of the forward, backward and gradient update pass of a single batch. `torch.cuda.current_stream().synchronize()` is called before the end timer iff `--sync` is passed.

* `python amp_sync.py --fp16 --sync` => 0.041 sec
* `python amp_sync.py --sync` => 0.046 sec
* `python amp_sync.py --fp16` =>  **0.041 sec** (no explicit sync but still waited for the GPU to finish)
* `python amp_sync.py` => 0.006 sec (no explicit sync so time is super short)

The issue is particularly visible on a GPU that do not have tensor cores.

## Expected behavior

`python amp_sync.py --fp16`  runtime should be as low as `python amp_sync.py`

[amp_sync.py.txt](https://github.com/NVIDIA/apex/files/2916104/amp_sync.py.txt)

**Comment by mcarilli** [comment]
Well spotted :)  The sync or syncs (there may be several) are required for dynamic loss scaling:  We need to communicate to the host whether the gradients have overflowed on the device, so the Python logic on the host can make the decision to either carry out an optimizer step (if no infs/nans were detected) or skip the step and reduce the loss scale (if infs/nans were detected).

The Amp 1.0 API (which I'm merging into master later today) should require only one sync per backward pass when using dynamic loss scaling.  Also, the new API permits you to use static loss scaling whenever you want.  Static loss scaling never requires syncs.

In theory, it IS possible to do dynamic loss scaling without host syncs.  In the next couple weeks, I'll start adding custom optimizers that communicate with the existing custom inf/nan checking kernels through device memory. The optimizer kernels will internally make the decision whether to skip the step, so the host can fire off everything blindly, and trust that the kernels will do the right thing.
