### ISSUE TITLE
is it possible to update `conda-forge/nvidia-apex` to a recent tag?

### ISSUE THREAD

**Issue by stas00** [NVIDIA/apex#1730]
**Describe the Bug**

I see that the 22.03 apex conda-forge packages released are using a soon to be 2 year old `apex`: https://anaconda.org/conda-forge/nvidia-apex/files
yet, someone rebuilds them every 3 months or so. Any reason not to update 
https://github.com/conda-forge/nvidia-apex-feedstock/blob/main/recipe/meta.yaml#L1
to 23.08 and continue updating it with new releases?

I realize that these [tag versions](https://github.com/NVIDIA/apex/tags) correspond to the nvidia pytorch docker image versions, e.g. nvcr.io/nvidia/pytorch:23.08-py3

Thank you.

**Comment by ptrblck** [comment]
We did not create the `conda-forge` package and do not maintain it. I also don't know how it was built and which GPUs are supported so you might want to ask someone at `conda-forge`.

**Comment by stas00** [comment]
Thank you for clarifying, @ptrblck!
