### ISSUE TITLE
Convergence question

### ISSUE THREAD

**Issue by ando-khachatryan** [NVIDIA/apex#175]
Hi, 
I am trying to port my code (https://github.com/ando-khachatryan/HiDDeN) into mixed-precision.
The architecture of the model is encoder-decoder and a discriminator (gan). I tried both amp and FP16Optimizer and get the around the same speedup, and the same problem: the model starts to diverge after a couple of epochs. It seems that the problem is that the gradients coming from discriminator (loss is BCEWithLogitsLoss) are exploding. I have tried both static and dynamic loss scaling, with the same results.

Without apex the network trains fine.

**Comment by mcarilli** [comment]
Deduplicating to https://github.com/NVIDIA/apex/issues/179.
