### ISSUE TITLE
An runtime error: core dumped

### ISSUE THREAD

**Issue by lemonhu** [NVIDIA/apex#177]
When I use fp16 technology, the following error occurs：

> terminate called after throwing an instance of 'std::runtime_error'
  what():  arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/THC/generic/THCTensorMathReduce.cu:208
Aborted (core dumped)

Thank you for your reply.

**Comment by mcarilli** [comment]
It's hard to tell from this alone what the error might be.  Do you have a minimal repro, or a more complete backtrace?

**Comment by lemonhu** [comment]
Sometimes when I run it again, there is no such problem, it’s weird.
Thank you for your reply.
