### ISSUE TITLE
[Questing] For apex sparsity model, when i export trt engine with flag sparsity=enable or force, only partial layer picked sparse implementation.

### ISSUE THREAD

**Issue by Bobo-y** [NVIDIA/apex#1780]
![image](https://github.com/NVIDIA/apex/assets/9928596/537f5052-76c0-481a-9f2f-328e1127aab9)
 above layer all traing with sparsity mask, but when convert to trt engine, only 3 layer can run with sparsity.

![image](https://github.com/NVIDIA/apex/assets/9928596/37a53d37-fbfb-445b-8221-a487b40f69b6)

**Comment by laurenlong** [comment]
Can I ask what settings are needed to see this output? I set `. /trtexec --onnx=model_weights_sparse.onnx --saveEngine=model_weights_sparse.trt --sparsity=enable --fp16 >result-model_weights_sparse-fp16.txt 2>&1` . But I don't see a similar output. Thank you!

**Comment by Bobo-y** [comment]
> Can I ask what settings are needed to see this output? I set `. /trtexec --onnx=model_weights_sparse.onnx --saveEngine=model_weights_sparse.trt --sparsity=enable --fp16 >result-model_weights_sparse-fp16.txt 2>&1` . But I don't see a similar output. Thank you!

may be  use --verbose
