### ISSUE TITLE
bug: FastLayerNorm

### ISSUE THREAD

**Issue by KK666-AI** [NVIDIA/apex#1866]
`FastLayerNorm` is sensitive to input shape. If the input shape is `(64, 256, 768)`, it works well. however, if the input shape is `(64, 256, 256)`, it fails.

```

import torch
from apex.contrib.layer_norm.layer_norm import FastLayerNorm
x_shape =  (64, 256, 256)
layer_norm = FastLayerNorm(x_shape[-1]).cuda()
x = torch.randn(x_shape).cuda()
y = layer_norm(x)

```

![Image](https://github.com/user-attachments/assets/0d0a4305-f9c3-4874-b430-9df236523543)

**Comment by crcrpar** [comment]
It has a limited coverage of supported shapes as in https://github.com/NVIDIA/apex/blob/73375b3bbcb59a5d6ff43f2fafd00b9ecdbe0417/apex/contrib/test/layer_norm/test_fast_layer_norm.py#L209-L246

**Comment by KK666-AI** [comment]
ok. thanks for response. i closed this issue.
