### ISSUE TITLE
Training deadlock

### ISSUE THREAD

**Issue by rotabulo** [NVIDIA/apex#19]
There is an issue in the implementation of DistributedDataParallel that triggers a deadlock of processes.
Specifically, in the method `flat_dist_call`, there is a for loop over a dictionary with calls to collective operations (like broadcasting) in the body. Since the ordering of the dictionary's keys is random, we obtain non-matching calls to the collective operations, which induce a deadlock of the processes.
I have fixed this issue and created a pull request.

**Comment by csarofeen** [comment]
Closed via https://github.com/NVIDIA/apex/pull/18
