### ISSUE TITLE
About the Documentation Example

### ISSUE THREAD

**Issue by LcDog** [NVIDIA/apex#193]
Hello, 

In the Documentation [opt_levels and Properties](https://nvidia.github.io/apex/amp.html#opt-levels-and-properties), the Example shows that
```
# Declare model and optimizer as usual
model = torch.nn.Linear(D_in, D_out).cuda().half()
```

Then in the below line it is said that 

> Users should not manually cast their model or data to .half()

Also, in the [README file](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/README.md) of ImageNet demo, it is said that

> With the new Amp API you never need to explicitly convert your model, or the input data, to half().

BTW, in my test, using `half()` will raise RuntimeError. Is the Example wrong, or am I missing something? 

Thanks!

**Comment by mcarilli** [comment]
You're totally right.  The example is wrong, my mistake.  It should be 
```
# Declare model and optimizer as usual
model = torch.nn.Linear(D_in, D_out).cuda()
```

> Users should not manually cast their model or data to .half()
is correct.
