### ISSUE TITLE
optimizer has no attribute 'skip_step'

### ISSUE THREAD

**Issue by fcharras** [NVIDIA/apex#198]
Using amp (the version just before the API revamp), the training seems to be going fine until it randomly stops with an AttributeError: optimizer has no attribute 'skip_step'.

The error is not reliably reproducible, it will happen eventually if the training goes for enough epochs.

Will provide additional traceback and context if met again.

**Comment by mcarilli** [comment]
In general, I don't intend to support the version just before the revamp.  I only tried to make sure it worked so people would have some time to switch.  I strongly recommend you move to the new version:
https://nvidia.github.io/apex/amp.html#transition-guide-for-old-api-users
Grepping the new code, the only ways `skip_step` is used are:
```
apex$ grep -ir "skip_step"
amp/handle.py:                    def skip_step():
amp/handle.py:                    optimizer.step = skip_step
amp/handle.py:            def skip_step():
amp/handle.py:            optimizer.step = skip_step
```
In other words, I never attempt to get `skip_step` from an optimizer instance.  Also, optimizer is never given an attribute called `skip_step`.  I occasionally set `optimizer.step` to a thing called `skip_step`, but the actual name of the attribute remains `optimizer.step`.  Maybe switching to the new API will resolve your issue.

**Comment by fcharras** [comment]
I wasn't asking for additional support, anyway there is no versioning or tagged release, plus a recent, non backward compatible API change, so the repo is still in a very early stage right ?

I signaled a bug around `skip_step` that I happened to encounter because I think it can help putting the finger on something and help other users, I apologize for the lack of traceback and reproducibility, will complete the report whenever I get the occasion to do so.

**Comment by mcarilli** [comment]
Yes, the repo is in a fairly early stage.  It arose as a separate collection of research tools that I am trying to unify and stabilize.  The new API is the first major step in that direction.

Your issue may indicate a real bug under the hood that may remains in the new API, and I appreciate you bringing it to our attention.  My point is, maybe the bug is something that has been resolved by the new API changes.

**Comment by fcharras** [comment]
The issue seems not to occur with the new API, which is also much clearer, I suppose I was misusing the old one.
