### ISSUE TITLE
Follow the ImageNet example, and always "CUDA" out of memory

### ISSUE THREAD

**Issue by USTClj** [NVIDIA/apex#204]
I show my code in:
`
import os
import argparse
import time
import tqdm
import matplotlib
matplotlib.use("agg")
import matplotlib.pylab as plt
import cv2
import torch.cuda
import numpy as np
import torch.nn as nn
import torch.optim as optim
from config.config import GetConfig, COCOSourceConfig, TrainingOpt
from data.mydataset import MyDataset
from torch.utils.data import DataLoader
from models.posenet import PoseNet
from models.loss_model import MultiTaskLoss
import warnings

try:
    from apex.parallel import DistributedDataParallel as DDP
    from apex.fp16_utils import *
    from apex import amp, optimizers
    from apex.multi_tensor_apply import multi_tensor_applier
except ImportError:
    raise ImportError("Please install apex from https://www.github.com/nvidia/apex to run this example.")

os.environ['CUDA_VISIBLE_DEVICES'] = "0, 1, 2, 3"  # choose the available GPUs
warnings.filterwarnings("ignore")

parser = argparse.ArgumentParser(description='PoseNet Training')
parser.add_argument('--resume', '-r', action='store_true', default=False, help='resume from checkpoint')
parser.add_argument('--checkpoint_path', '-p',  default='checkpoints_parallel', help='save path')
parser.add_argument('--max_grad_norm', default=5, type=float,
                    help=("If the norm of the gradient vector exceeds this, "
                          "re-normalize it to have the norm equal to max_grad_norm"))
parser.add_argument("--local_rank", default=0, type=int)
parser.add_argument('--opt-level', type=str, default='O1')
parser.add_argument('--sync_bn', action='store_true', help='enabling apex sync BN.')  
parser.add_argument('--keep-batchnorm-fp32', type=str, default=None)

torch.backends.cudnn.benchmark = True 
use_cuda = torch.cuda.is_available()

args = parser.parse_args()

checkpoint_path = args.checkpoint_path
opt = TrainingOpt()
config = GetConfig(opt.config_name)
soureconfig = COCOSourceConfig(opt.hdf5_train_data)
train_data = MyDataset(config, soureconfig, shuffle=False, augment=True)  # shuffle in data loader

soureconfig_val = COCOSourceConfig(opt.hdf5_val_data)
val_data = MyDataset(config, soureconfig_val, shuffle=False, augment=True)  # shuffle in data loader

best_loss = float('inf')
start_epoch = 0 
posenet = PoseNet(opt.nstack, opt.hourglass_inp_dim, config.num_layers + config.offset_layers, bn=False)
optimizer = optim.SGD(posenet.parameters(), lr=opt.learning_rate, momentum=0.9, weight_decay=1e-4)

args.distributed = False
if 'WORLD_SIZE' in os.environ:
    args.distributed = int(os.environ['WORLD_SIZE']) > 1

args.gpu = 0
args.world_size = 1

if args.distributed:
    args.gpu = args.local_rank % torch.cuda.device_count()
    torch.cuda.set_device(args.gpu)
    torch.distributed.init_process_group(backend='nccl',
                                         init_method='env://')
    args.world_size = torch.distributed.get_world_size()

print('************ World Size of this process is: {} ****************'.format(args.world_size))
assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."

if args.sync_bn:
    import apex
    print("Using apex synced BN.")
    posenet = apex.parallel.convert_syncbn_model(posenet)

posenet.cuda()

model, optimizer = amp.initialize(posenet, optimizer,
                                  opt_level=args.opt_level,
                                  keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                  loss_scale=None  # Dynamic loss scaling is used by default.
                                  )

if args.distributed:
    model = DDP(model, delay_allreduce=True)

best_loss = float('inf')  # fixme

criterion = MultiTaskLoss(opt, config).cuda()

train_sampler = None
val_sampler = None

train_sampler = torch.utils.data.distributed.DistributedSampler(train_data)
val_sampler = torch.utils.data.distributed.DistributedSampler(val_data)

train_loader = torch.utils.data.DataLoader(train_data, batch_size=opt.batch_size, shuffle=(train_sampler is None),
                                           num_workers=16, pin_memory=True, sampler=train_sampler)

val_loader = torch.utils.data.DataLoader(val_data, batch_size=opt.batch_size, shuffle=False,
                                         num_workers=16, pin_memory=True, sampler=val_sampler)

scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.2, last_epoch=-1)   
for i in range(start_epoch):
    scheduler.step()

for param in posenet.parameters():
    if param.requires_grad:
        print('Parameters of network: Autograd')
        break

def train(epoch):
    print('\n ############################# Train phase, Epoch: {} #############################'.format(epoch))
    posenet.train()
    train_loss = 0
    scheduler.step()
    print('\nLearning rate at this epoch is: %0.9f\n' % optimizer.param_groups[0]['lr'])  # scheduler.get_lr()[0]

    for batch_idx, target_tuple in enumerate(train_loader):
        if use_cuda:
            target_tuple = [target_tensor.cuda(non_blocking=True) for target_tensor in target_tuple]

        images, mask_misses, heatmaps, offsets, mask_offsets = target_tuple
        # images = Variable(images)
        # loc_targets = Variable(loc_targets)
        # conf_targets = Variable(conf_targets)

        optimizer.zero_grad()  # zero the gradient buff
        output_tuple = model(images)
        loss = criterion(output_tuple, target_tuple[1:])

        if loss.item() > 1e6:
            print("\nLoss is abnormal, drop this batch !")
            loss.zero_()
            continue

        with amp.scale_loss(loss, optimizer) as scaled_loss:
            scaled_loss.backward()

        torch.nn.utils.clip_grad_norm(model.parameters(), args.max_grad_norm)
        optimizer.step()  # TODO：

        train_loss += loss.item() 
        print('########################### Epoch:', epoch, ', --  batch:',  batch_idx, '/', len(train_loader), ',   ',
              'Train loss: %.3f, accumulated average loss: %.3f ##############################' % (
                  loss.item(), train_loss / (batch_idx + 1)))

    global best_loss
    train_loss /= len(train_loader)
    if train_loss < best_loss:
        print('saving...')
        state = {
            # not posenet.state_dict(). then, we don't ge the "module" string to begin with
            'weights': posenet.module.state_dict(),
            'optimizer_weight': optimizer.state_dict(),
            'train_loss': train_loss,
            'epoch': epoch,
        }
        os.makedirs(checkpoint_path, exist_ok=True)
        logger = open(os.path.join('./' + checkpoint_path, 'log'), 'a+')
        logger.write('\ntrain_loss of epoch {} : {}'.format(epoch, train_loss))
        logger.flush()
        logger.close()
        torch.save(state, './' + checkpoint_path + '/PoseNet_' + str(epoch) + '_epoch.pth')
        best_loss = train_loss

if __name__ == '__main__':
    for epoch in range(start_epoch, start_epoch + 200):
        if args.distributed:
            train_sampler.set_epoch(epoch)
        train(epoch)
`

**Comment by USTClj** [comment]
For now, I just want to run the code which follows the Imagenet example using `python -m torch.distributed.launch --nproc_per_node=4 train_distributed.py
` and I failed. I have never used Apex package and distribution package. Could someone give me some advice? I want to make use of the 4 GPU on one machine.

**Comment by mcarilli** [comment]
Can you post the output of `nvidia-smi` to tell me what kind of GPUs they are and their memory capacities?

**Comment by USTClj** [comment]
Hi @mcarilli , thank you for your notice and reply. I have 4 2080Ti on my machine. 
`Sun Mar 17 09:47:43 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 27%   39C    P8    28W / 250W |    448MiB / 10988MiB |     22%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 27%   31C    P8     1W / 250W |      1MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 27%   32C    P8    21W / 250W |      1MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:83:00.0 Off |                  N/A |
| 27%   31C    P8     3W / 250W |      1MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
`

**Comment by USTClj** [comment]
My training code warped with Dataparallel of pytorch works fine. And I'm gonna to use the DPP and FP 16 training of Apex package.

**Comment by USTClj** [comment]
@mcarilli **Update:**
When I run the simple/distributed/distributed_data_parallel.py example, I can see that the load of each GPU is very unbalanced.

```   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 29%   44C    P2    83W / 250W |   1231MiB / 10988MiB |     21%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 27%   41C    P2    89W / 250W |    834MiB / 10989MiB |     41%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
| 27%   41C    P2    66W / 250W |    834MiB / 10989MiB |     15%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:83:00.0 Off |                  N/A |
| 27%   42C    P2    81W / 250W |    834MiB / 10989MiB |     39%      Defaul```

**Comment by mcarilli** [comment]
The batch sizes given in https://github.com/NVIDIA/apex/tree/master/examples/imagenet#example-commands assume that your GPU has at least 16GB of onboard memory.  You may have to reduce the batch size to run on your RTX 2080s, which have 11GB of onboard memory.  For example, try a batch size of 128 instead of 224 for opt_level O1 and O2.

**Comment by USTClj** [comment]
@mcarilli Thank you for your reply. Problem has already been solved. Forgive me for knowing nothing about distributed training before.

**Comment by chengxili** [comment]
> @mcarilli Thank you for your reply. Problem has already been solved. Forgive me for knowing nothing about distributed training before.

How did you solve it? I got this problem even with batch size=1
