### ISSUE TITLE
Error occurred when executing loss.backward() in pytorch with distributed training 

### ISSUE THREAD

**Issue by DancingSoul** [NVIDIA/apex#208]
```
Traceback (most recent call last):
  File "./pretraining/run_pretraining.py", line 440, in <module>
    main()
  File "./pretraining/run_pretraining.py", line 384, in main
    loss.backward()
  File "/data/anaconda/envs/bzheng_env/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/anaconda/envs/bzheng_env/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/data/anaconda/envs/bzheng_env/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 310, in overlapping_backward_epilogue
    "This probably indicates some buckets were not allreduced.")
RuntimeError: ('In epilogue, next_bucket (0) != num_buckets (1).  ', 'This probably indicates some buckets were not allreduced.')
```
This error occurred when executing loss.backward() in pytorch with distributed training.

It occurs even using only a single gpu while the program runs normally without distributed training.

Have anyone met the same problem with me?

The command I use to start the program is shown follows:
```
python -u -m torch.distributed.launch --nproc_per_node=1 ./pretraining/run_pretraining.py ******
```

**Comment by glample** [comment]
For now PyTorch distributed does not support the case where some parameters are not updated, and I think this is the issue you are facing here. Maybe check that you don't have parameters in your model that never appear in the forward path? Also something simple to avoid the issue can be to hack something like `loss = loss + 0 * sum([x.sum() for x in model.parameters()])` I do it sometimes it's ugly but it works.

**Comment by mcarilli** [comment]
@DancingSoul You may be able to work around by supplying `delay_allreduce=True` to the `apex.parallel.DistributedDataParallel` constructor.  In this case Apex DDP will wait until the end of the backward pass and allreduce all gradients that happened to be created, which means it can handle nondeterministic/different sets of gradients being created in each iteration, **as long as the set of gradients that are created each iteration is the same across all processes**.

If you want to try delay_allreduce=True, @glample's suggestion should work.  Another thing that may work is to make sure all the parameters that you DON'T intend to create gradients for are explicitly frozen (manually set requires_grad=False for all these non-updated params before the forward pass).

**Comment by DancingSoul** [comment]
@glample @mcarilli 
Thanks a lot, it solved my problem!
