### ISSUE TITLE
Nvidia apex arch linux installation

### ISSUE THREAD

**Issue by drapado** [NVIDIA/apex#220]
I've tried installing apex with CUDA and C++ extensions as the readme says, but it's not being installed in arch linux. Just the python-only build works.

I think the reason is that cuda and cudnn packages are not installed in arch linux in the same directory as in ubuntu.

Any suggestion on how can I solve it?

Thanks!

**Comment by mcarilli** [comment]
This is likely not an Apex issue, but an issue with pytorch cuda extensions in general.  Can you try the upstream extension tests?
```
git clone pytorch
cd pytorch/test/cpp_extensions
python setup.py install
```

**Comment by drapado** [comment]
Solved by using the AUR package
