### ISSUE TITLE
GPU usage in DistributedDataParallel?

### ISSUE THREAD

**Issue by dave-epstein** [NVIDIA/apex#222]
Hi,

When I try to run a model across 4 GPUs using the PyTorch launcher and Apex DDP, I see GPU usage like this: https://i.imgur.com/TFCemy8.png

The processes that were spun up on GPUs 1, 2, and 3 are using almost a GB each of space on GPU0. Is this expected behavior? If not, what are some possible culprits?

Thanks!

**Comment by dave-epstein** [comment]
I was actually loading some parameters onto a model before I set the CUDA current device - sorry about that. Please feel free to delete.

**Comment by dave-epstein** [comment]
Sorry - the problem was on my end here. I needed to pass map_location to torch.load calls after I set torch.cuda.current_device().

**Comment by mcarilli** [comment]
No, it's not expected.  There are a couple possible culprits:
1.  Forgetting to call set_device at the beginning of each process (see [this issue](https://github.com/NVIDIA/apex/issues/203#issuecomment-473082702), [relevant line in my simple example](https://github.com/NVIDIA/apex/blob/master/examples/simple/distributed/distributed_data_parallel.py#L22), and also the [torch.distributed.launch](https://pytorch.org/docs/stable/distributed.html#launch-utility) documentation under **Important notices**).
2.  Loading from a checkpointing that was saved from rank 0, and neglecting to add `map_location` to the `torch.load` call (see [here](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py#L177)).  Without `map_location`, loaded tensors are created on the device rank that matches the device they were originally saved from, so if the checkpoint was saved from rank 0, all processes that load the checkpoint will deserialize the loaded tensors onto device 0.  `map_location` can be used to tell each process to load its tensors onto its own device instead.

**Comment by mcarilli** [comment]
Aha, you were typing that just as i sent my comment.

**Comment by dave-epstein** [comment]
Thank you for the help - you were spot on with both problems!
