### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ibulu** [NVIDIA/apex#23]
I am really excited about trying this. But, every time I try installing, I am getting the following error:
torch.__version__  =  0.5.0a0+03e7953
Found CUDA_HOME =  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    CUDA_MAJOR = get_cuda_version()
  File "setup.py", line 85, in get_cuda_version
    re.compile('nvcc$').search)
  File "setup.py", line 38, in find
    return list(set(collection))
TypeError: 'NoneType' object is not iterable

**Comment by mcarilli** [comment]
Looks like you're on Windows.  I don't have access to a Windows machine with Pytorch right now, but I'll find one tomorrow to test the build. Typically, Linux is what we recommend, so if you have the option to run on a Linux machine, that should work right away.

**Comment by ibulu** [comment]
Thank you. I really appreciate that.

**Comment by mcarilli** [comment]
I admit I'm not an expert on Windows builds.  I'll have to ask some other people tomorrow.

In the meantime, if you want an immediate path forward, some of the utilities in Apex are Python-only.  For example, [FP16_Optimizer](https://github.com/NVIDIA/apex/tree/master/apex/fp16_utils) and [DistributedDataParallel](https://github.com/NVIDIA/apex/tree/master/apex/parallel) technically don't require building the C backend.  One item on my to-do list is creating a Python-only "apex-lite" install option. 

The necessary-and-sufficient set of Python files to use FP16_Optimizer is fp16_optimizer.py, fp16_util.py, and loss_scaler.py from the [fp16_utils](https://github.com/NVIDIA/apex/blob/master/apex/fp16_utils) directory.

The necessary-and-sufficient set of Python files to use apex DistributedDataParallel is distributed.py and multiproc.py from the [parallel](https://github.com/NVIDIA/apex/blob/master/apex/parallel) directory.

If you copy those files alongside your training script, you should be able to say e.g. `from fp16_optimizer import FP16_Optimizer` or `from distributed import DistributedDataParallel as DDP` and they should work without needing to run the setup.py.

Thank you for your interest in Apex and your feedback.  It's very helpful to know what issues people are encountering, especially at this early stage.

**Comment by ibulu** [comment]
Thanks. Really appreciate your suggestion. I will give it a try on a newly received titan V :-)

**Comment by mcarilli** [comment]
@ibulu When you installed pytorch from source, did you run the following lines
```
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"
...
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
```
before `python setup.py install?"  Apex needs that same environment to build, so you will also need to specify those lines before you build Apex.  If you installed Pytorch within a Conda environment from the command line, you'll also want to install Apex within that same Conda environment.

**Comment by ibulu** [comment]
I had a chance to try to install apex the same way I installed pytorch, but I am still getting the following error:

torch.__version__  =  0.5.0a0+03e7953
Found CUDA_HOME =  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    CUDA_MAJOR = get_cuda_version()
  File "setup.py", line 85, in get_cuda_version
    re.compile('nvcc$').search)
  File "setup.py", line 38, in find
    return list(set(collection))
TypeError: 'NoneType' object is not iterable


here are the steps I followed in more detail:
git clone --recursive https://github.com/NVIDIA/apex
cd apex
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
set MSSdk=1
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install

**Comment by mcarilli** [comment]
@ibulu Ok, give it a try now.  I was able to install on my machine with current top of tree [247349f](https://github.com/NVIDIA/apex/commit/247349f1de28ef94e863aa2b28bbb7adcd52c49b).  

Again, make sure you are running in the right Visual Studio and Anaconda environments.  Only the lines
```
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
```
are necessary to set up the Visual Studio environment, but if you installed Pytorch in an Anaconda enviroment, you need to install Apex in that same environment.

Moving forward, we intend to regard Windows support as experimental, so I still recommend using Linux if you can.

**Comment by ibulu** [comment]
wonderful :-) I confirm that I was able to install and import the library. Thank you very much!
