### ISSUE TITLE
RuntimeError: Found torch.FloatTensor, expected torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by che85** [NVIDIA/apex#230]
Hi there, 

I am just trying apex for the first time and running into the following error:

```
RuntimeError: Found param block_one.conv.0.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
```

Is there anything that I am missing or that I need to take care of?

**Comment by che85** [comment]
I think I fixed it. I didn't move the model to cuda by `model.cuda()`

**Comment by mcarilli** [comment]
Yes, amp requires that your model is cuda.  I should make those error messages clearer.
