### ISSUE TITLE
Optimizer not defined

### ISSUE THREAD

**Issue by HapeMask** [NVIDIA/apex#24]
https://github.com/NVIDIA/apex/blob/88effd5da483a1ce5ce98b6800943dcac2057f2d/apex/fp16_utils/fp16_optimizer.py#L187

I get a NameError at the line above trying to use FP16_Optimizer. Replacing this with ```self.optimizer = init_optimizer``` fixes the issue, is that correct?

**Comment by mcarilli** [comment]
Of course, I'll fix that right away.
