### ISSUE TITLE
Nan Loss with O3 opt_level setting

### ISSUE THREAD

**Issue by picagrad** [NVIDIA/apex#240]
Hi everyone, first off I gotta say amp has really helped me with some research and thanks to everyone involved!
I've been training a ResNet style network for dogs vs. cats.
Training was successful with all O0,O1,O2, but when I run it using O3 I'm getting nan loss.

I've put in some assert statements to check where the nan first appears, and it seems like it happens after the optimizer step. 

My network has some batch normalization layers and so I've used the flag keep_batchnorm_fp32 to ensure stability even with O3 "pure" floating point 16. Additionally, I've followed the instructions in the documentation and replaced the sigmoid and BCELoss with no sigmoid and BCEWithLogitsLoss.

Network definition:

```
class MyResNet(nn.Module):
	def __init__(self, feature_sizes, kernel_sizes,down_sample, res_split, res_merge, dct = False):
		super(MyResNet, self).__init__()
		conv = []
		bn = []
		pad = []
		prev_layer_dim = 3
		k = kernel_sizes[0]
		self.prepad = nn.ZeroPad2d(((k-1)//2,k//2,(k-1)//2,k//2))
		self.preconv = nn.Conv2d(prev_layer_dim, feature_sizes[0], k, stride = 2, padding = 0)
		self.prebn = nn.BatchNorm2d(feature_sizes[0])
		prev_layer_dim = feature_sizes[0]
		
		for f,k,d in zip(feature_sizes,kernel_sizes, down_sample):
			pad.append(nn.ZeroPad2d(((k-1)//2,k//2,(k-1)//2,k//2)))
			conv.append(nn.Conv2d(prev_layer_dim, f, k, stride = 1+d, padding = 0))
			bn.append(nn.BatchNorm2d(f))
			prev_layer_dim = f
	
		self.conv = nn.ModuleList(conv)
		self.bn = nn.ModuleList(bn)
		self.pad = nn.ModuleList(pad)
		
		self.depth = len(feature_sizes)
		self.rs = res_split
		self.mrg = res_merge
		self.final_layer = nn.Linear(prev_layer_dim, 1)

	def forward(self, x):
		x = self.prepad(x)
		x = self.preconv(x)
		x = self.prebn(x)
		x = F.leaky_relu(x,negative_slope = 0.2)
		
		for i in range(self.depth):	
			# print(i)
			x = self.pad[i](x)
			x = self.conv[i](x)
			x = self.bn[i](x)
			x = F.leaky_relu(x,negative_slope = 0.2)
			if self.rs[i]:
				s = x
			if self.mrg[i]:
				x+=s
		
		x = F.max_pool2d(x, x.size()[2:])
		x = x.squeeze(dim=-1)
		x = x.squeeze(dim=-1)
		x = self.final_layer(x)	
		if not half_precision:
			x = torch.sigmoid(x)
		return x

	def num_flat_features(self, x):
		size = x.size()[1:]  # all dimensions except the batch dimension
		num_features = 1
		for s in size:
			num_features *= s
		return num_features

```

Training and loss definition:

```
if half_precision:
	loss_fn = nn.BCEWithLogitsLoss()
else:
	loss_fn = nn.BCELoss()
optimizer = optimizer = optim.Adam(mynet.parameters(), lr = 0.001)

mynet, optimizer = amp.initialize(mynet, optimizer, opt_level = mixed_precision_class, keep_batchnorm_fp32 = True)
for epoch in range(epochs):
	total_loss = 0
	total_correct = 0
	for local_batch, local_labels in training_generator:
		for p in mynet.parameters():
			assert not torch.isnan(p.data).any(), 'found nan in weights before optimizer step'
		local_labels = local_labels.unsqueeze(-1)
		local_batch, local_labels = local_batch.to(device), local_labels.to(device)
		pred_fuzzy_lbl = mynet(local_batch)
		assert not torch.isnan(pred_fuzzy_lbl).any(), 'Found nan at network output'
		loss = loss_fn(pred_fuzzy_lbl,local_labels)
		assert not torch.isnan(pred_fuzzy_lbl).any(), 'Found nan at network loss'	
		total_loss += loss.item()
		pred_lbl  = ((pred_fuzzy_lbl >0.5)*1.0).float()
		current_correct = (pred_lbl == local_labels)
		total_correct += current_correct.sum().item()
		mynet.zero_grad()
		optimizer.zero_grad()
		with amp.scale_loss(loss, optimizer) as scaled_loss:
			scaled_loss.backward()
		for p in mynet.parameters():
			assert not torch.isnan(p.grad).any(), 'found nan in gradients'			
		optimizer.step()
		for p in mynet.parameters():
			assert not torch.isnan(p.data).any(), 'found nan in weights after opt step'
```

As mentioned above I'm getting the assertion error on the first batch after the optimizer step:

> AssertionError: found nan in weights after optimizer step

Any ideas, is this my mistake or a bug? I've followed all instructions given, and it runs perfectly for most "opt_level"s. 
Thanks!

**Comment by mcarilli** [comment]
Thanks!  It's likely not a mistake on your part, and hopefully not a bug.  O3 is not mixed precision:  by default, it is simply pure fp16 training.  Its purpose is to allow you to experiment with pure fp16, to provide a speed baseline against which O0, O1, O2 can be compared.  Specifying keep_batchnorm_fp32 will help somewhat with stability (and also with establishing a speed ceiling, because it enables cudnn batchnorm), but the rest of the network will still run in fp16, so I do not expect keep_batchnorm_fp32 is sufficient to guarantee stability in O3.

For end to end training,  the mixed precision modes (O1 and O2) are recommended.  The intent of these (O1 in particular) is to offer speed comparable to O3 with stability comparable to O0 (fp32 training).  So if O1 and O2 are working, that's great!  If you observe that O1 and O2 are working but O3 is unstable, then I'd regard this as a demonstration of exactly why O1 and O2 are helpful.

**Comment by picagrad** [comment]
Hi @mcarilli , thanks for your response.

While I understand your answer, I'm not sure how getting nan optimizer step is not a bug, I understand FP16 is less intended for end to end training, and I would understand if my issue was simply training not converging (as was shown here: https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/). 
However the issue here is getting nan step from the optimizer after the first batch, which suggests overflow/log0 etc. Can you explain why you think this is not a bug?

**Comment by mcarilli** [comment]
It's likely the params started to contain nans after the first step() because the first backward() created some gradients containing nans.  You can check the gradients after backward
```
loss.backward()
for param in model.parameters():
    print(param.grad.float().sum())
```
to see if any of those are infs before the call to step().

**Comment by github-mi** [comment]
The default value of eps in Apex is 1e-8,  it would be underflow when using FP16.
you can try to set the eps to larger value like 1e-5.

**Comment by siquike** [comment]
Where and how do you set this eps value?

**Comment by github-mi** [comment]
> Where and how do you set this eps value?

sorry, not in Apex. you should set eps in Adam.
