### ISSUE TITLE
[Windows] "<unnamed>::error" was referenced but not define in SharedMemory

### ISSUE THREAD

**Issue by mooncake4132** [NVIDIA/apex#246]
I'm compiling apex in Windows with:
```
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
and everything was well until nvcc throws an error on the following line:
https://github.com/NVIDIA/apex/blob/e9bbfa591af01168f308ce8e7149252a50a75300/csrc/layer_norm_cuda_kernel.cu#L243-L253
```
csrc/layer_norm_cuda_kernel.cu(249): error: function "<unnamed>::error" was referenced but not define
```
But the compiler is only generating double and float specialization SharedMemory, so I'm not sure why it's also compiling `SharedMemory <T>` and with what type T. I was able to work around the issue by changing the non-specialized SharedMemory into
```cpp
template <typename T>
struct SharedMemory;
```

I do want to mention that I know nothing about CUDA programming and very little about C/C++ programming so please let me know if I analyzed anything wrong. Was there a specific reason why SharedMemory is not left undefined? (in the way I worked around the issue). Maybe it was not supported in the previous versions of nvcc?

I'm using nvcc  v10:
```
> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
```
Are other people using nvcc v10.0 were able to successfully compile in Linux?

**Comment by mcarilli** [comment]
Having a default (unspecialized) fallback for the template be something that fails to compile is a C++ trick that @thorjohnsen used to make sure the template is never instantiated with anything other that T=float or T=double.  GCC only throws a warning (not an error) when it sees that the definition of the (hopefully-never-actually-instantiated, but lurking in wait) unspecialized fallback is ill-formed, but I guess your windows compiler is stricter (or maybe you could say dumber, too dumb to realize that the deliberately ill-formed fallback is never actually instantiated).  I think your workaround:
```
template <typename T>
struct SharedMemory;
```
(aka, having the unspecialized declaration, but no unspecialized definition, and only writing definitions for the float and double specializations) is reasonable.  I think this is legal C++ based on a cursory google search.  I'm going to test my Linux container builds and merge if it works.

**Comment by mcarilli** [comment]
reopen if the latest master still fails to build.

**Comment by mooncake4132** [comment]
Thanks for the quick turn-around and the explanation. I'm able to successfully build master now.
