### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lemonhu** [NVIDIA/apex#255]
Hi, the problem `Segmentation fault` occurs when I use apex for mixed precision training, the test script is as follows:
```
import torch
import apex

input = torch.rand(3, 10).cuda()
fln = apex.normalization.FusedLayerNorm(10).cuda()
fln(input)
```
Then I refer to the answer to issue #156 and try to solve this problem. When I execute the following commands in turn. Environment: `CUDA 10.0.30`, `torch-1.0.1.post2-cp37`
```
$ pip uninstall apex
$ cd apex_repo_dir
$ rm-rf build
$ python setup.py install --cuda_ext --cpp_ext
```
It does not work for me, looking forward to your reply.

**Comment by mcarilli** [comment]
`python setup.py install --cuda_ext --cpp_ext` is not the recommended install command anymore.  Try
```
$ pip uninstall apex
$ pip uninstall apex # repeat until you're sure it's gone, different install methods may create redundant installs
$ cd apex_repo_dir
$ rm -rf build # if "build" exists"
$ rm -rf apex.egg-info # if "apex.egg-info" exists
$  pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
I updated https://github.com/NVIDIA/apex/issues/156#issuecomment-465301976 to show the new command as well.

**Comment by lemonhu** [comment]
Thanks for your reply. However, when I follow your command, the following error occurs.

> (pytorch1.0) [root@Centos7 apex-master]# pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"
/root/anaconda3/envs/pytorch1.0/lib/python3.7/site-packages/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-2w_p6qi2
Created temporary directory: /tmp/pip-req-tracker-_ru2s5z_
Created requirements tracker '/tmp/pip-req-tracker-_ru2s5z_'
Created temporary directory: /tmp/pip-install-_iaayb0n
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-_ru2s5z_'
ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by lemonhu** [comment]
Thank you for your reply, I don't know why it still has the above problems in the environment of `gcc4.8.5`. However, when I upgrade the gcc environment to 4.9.2, re-clone the repository and follow your commands, it works for me.

**Comment by mcarilli** [comment]
I'm also not sure why gcc 4.8.5 fails, but thank you for the information, I'll remember this if future users have the same issue.
