### ISSUE TITLE
GPU memory stability switching between train/eval with AMP enabled

### ISSUE THREAD

**Issue by rwightman** [NVIDIA/apex#258]
Using a training script that's somewhere between the Imagenet example in this repo and the PyTorch example, I ran into an issue with GPU memory consumption switching between train and eval when AMP was enabled w/ O3.

The model was an SE-ResNet variant. I was using two processes, 1 RTX GPU per process, with APEX DDP. I had the training running with a batch size that gave me a margin that's usually fine. On finishing the last training batch and moving to the eval loop, there is a longish pause and then crash due to failed GPU memory alloc.

I reduced the batch size, several times, eventually had it running at 55% GPU memory during train. It still crashes OOM with a long pause moving to eval.

If I disable AMP with the same setup and set the batch size to hit 98% or so utilization everything works as usual, there is very little memory fluctuation moving between train/eval.

Any tips for debug or known issues?

Edit: Conda pytorch-1.0.1-post2 and CUDA10.

**Comment by mcarilli** [comment]
I haven't observed this symptom before but it sounds alarming.  In my own resnet example I haven't observed any OOMs when switching between train and eval.  Do you have a minimal repro?  Something that uses the imagenet dataset is fine.

By the way, O3 is not recommended for end to end training.  It is intended to be used only as a performance reference.  O1 is the best thing to try first for convergence runs, typically.

**Comment by rwightman** [comment]
I'll try to get a repro once my current task wraps up. Pretty sure there was a network architecture or hyper-param dependency because I did manage to train a different network without running into the problem last week.

Thanks for the O3 tip.

**Comment by rwightman** [comment]
I tried a few more things. 
* issue not specific to running in distributed mode
* issue happens in O1, O2, and O3 (didn't try others)
* issue does happen with other models
* issue can be prevented by removing my batch_size multiple on validation

For the last point, I've always employed a 4x multiplier on the batch sized used for validation (compared to train) to speed things along since there are no gradients being tracked. This as always worked for standard non AMP training, I've done it for years. Never an issue with memory exceeding the level at training.

However with AMP enabled, even when the batch size with multipler applied is well within the card's limits and under the training consumption (verified by running eval loop by itself), it fails on the transition from training -> validation loops

**Comment by mcarilli** [comment]
What this tells me is that the memory consumption for eval is somehow the same as for training, which means Amp may be mistakenly causing a graph to be built during eval as well.  Without Amp, what's the method you're using to ensure that a graph is not built during eval?  For example, are you running under a `with torch.no_grad()` context manager?  Maybe Amp is managing to sneak around that somehow.

A repro would be pretty interesting to see.

**Comment by rwightman** [comment]
This is my eval loop, running under a with CM

https://github.com/rwightman/pytorch-image-models/blob/master/train.py#L389

**Comment by windj007** [comment]
@rwightman @mcarilli  Have you solved the issue? I seem to face the same issue with AMP (5b29cc13999a64e231cfc6cbe4ee6f35a57d4451) and PyTorch 1.3: about 50% of memory used during training and OOM during the first forward pass on validation. Batch size == 1 any time.

**Comment by rwightman** [comment]
@windj007 I'd say the issue is 'better behaved' for me these days but I still run into problems with certain workloads (specific input size/batch sizes) that trigger an unexpected OOM during train/validation transitions, or at the end of validation with the one odd sized batch...

**Comment by andravin** [comment]
I reported the "memory leak" issue referenced above with:

- amp (master)
- pytorch 1.3
- pytorch-image-models project

It appears the problem actually has to do with the fact that amp requests very large memory allocations from pytorch, and this might not work well with the pytorch memory manager.

With amp enabled, and a batch size that uses ~60% of GPU memory during the first training epoch, and 4x the batch size during validation, I see total GPU memory use (as reported by nvidia-smi) grow each epoch during validation, until after several epochs the memory reaches nearly the total GPU memory capacity (16 GB). 

Then on the next validation this exception is thrown inside amp/wrap.py:wrapper:

>RuntimeError: CUDA out of memory. Tried to allocate 4.88 GiB (GPU 6; 15.75 GiB total capacity; 3.62 GiB already allocated; 3.67 GiB free; 7.39 GiB cached)

The requested memory size `4.88 GiB` seems rather large for a single allocation. The error message suggests that Pytorch is unable  to handle the large allocation despite the fact that free +  cached memory is more than twice the size of the request. 

But it amp instead requested many small allocations, this problem would not happen in the first place. 

Is amp trying to allocate a large workspace for all of its tensors? Would it not be better to let Pytorch's memory manager handle the allocations of individual tensors?

```
File "train.py", line 643, in <module>
    main()
  File "train.py", line 451, in main
    eval_metrics = validate(model, loader_eval, validate_loss_fn, args)
  File "train.py", line 597, in validate
    output = model(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/pytorch-image-models/timm/models/efficientnet.py", line 286, in forward
    x = self.forward_features(x)
  File "/home/ubuntu/github/pytorch-image-models/timm/models/efficientnet.py", line 279, in forward_features
    x = self.blocks(x)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/pytorch-image-models/timm/models/efficientnet_blocks.py", line 387, in forward
    x = self.conv_exp(x)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 4.88 GiB (GPU 6; 15.75 GiB total capacity; 3.62 GiB already allocated; 3.67 GiB free; 7.39 GiB cached)
```
