### ISSUE TITLE
error: class "at::Type" has no member "scalarType"

### ISSUE THREAD

**Issue by DinghaoZhang** [NVIDIA/apex#267]
I can't setup this, error is:
    csrc/type_shim.h(13): error: class "at::Type" has no member "scalarType"
    1 error detected in the compilation of "/tmp/tmpxft_00004318_00000000-6_multi_tensor_scale_kernel.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
who know how to fix it?

**Comment by ptrblck** [comment]
Which PyTorch version are you using?
You can check it with `python -c "import torch; print(torch.__version__)"`

In case your PyTorch version is older than `0.4`, you should update it using the install instructions given on the [PyTorch website](https://pytorch.org/get-started/locally/).

**Comment by Stonesjtu** [comment]
The master branch of pytorch  now  does not support cpp-extension due to a breaking change, you should check out to release version.

**Comment by ptrblck** [comment]
@Stonesjtu Could you post a link to the issue if possible?

**Comment by Stonesjtu** [comment]
@ptrblck Sure, Check this out : pytorch/pytorch:#17991.

**Comment by ptrblck** [comment]
Thanks for letting us know! :)
I'll take a look into this issue so that we can build again from PyTorch master.

**Comment by mcarilli** [comment]
Fix is in flight (https://github.com/NVIDIA/apex/pull/272), should be done in the next couple days.  We need to ensure backward compatibility with versions of Pytorch from 1.0 to present.
