### ISSUE TITLE
when do multi-process training (uses all visible GPU on the node) ,script crash

### ISSUE THREAD

**Issue by binbinmeng** [NVIDIA/apex#28]
>>python -m apex.parallel.multiproc main.py -a resnet50 --fp16 --b 128 --workers 4 /workspace/imagenet/
Traceback (most recent call last):
  File "main.py", line 466, in <module>
    main()
  File "main.py", line 117, in main
    rank=args.rank)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: more than one node have assigned same rank at /opt/pytorch/pytorch/torch/lib/THD/process_group/General.cpp:17

**Comment by mcarilli** [comment]
That's strange, it was working for me today.  Also, when you launch with apex.parallel.multiproc, the first thing that should be printed to the console is a list of the processes that are launched, something like
```
['main.py', '--arg1', ... , '--rank', '0']
['main.py', '--arg1', ... , '--rank', '1']
... 
```
Can you provide more information about your system?  How many GPUs are on the node?  Did you set CUDA_VISIBLE_DEVICES?  Setting CUDA_VISIBLE_DEVICES should not be necessary but it is helpful to know.

**Comment by binbinmeng** [comment]
1. in nv-docker pytorch container
2. 8xV100
3. all gpu can be seen in this container

>>>>root@58777ab95e8a:/workspace/apex/examples/imagenet# python -m apex.parallel.multiproc main.py -a resnet50 --fp16 --b 128 --workers 4 /workspace/imagenet/
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '0']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '1']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '2']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '3']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '4']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '5']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '6']
['main.py', '-a', 'resnet50', '--fp16', '--b', '128', '--workers', '4', '/workspace/imagenet/', '--world-size', '8', '--rank', '7']

**Comment by mcarilli** [comment]
This output looks normal:  apex.parallel.multiproc is detecting 8 gpus available, spawning 8 workers, and assigning them each a rank 0-7.  I also retried that same command today on a dgx1v, with 8 V100s, and it ran without any problems. 

There are few things I can think of to try:
1.  In main.py [here](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main.py#L108), you can add `print(args.rank, torch.cuda.device_count())` to make sure that each `main.py` is actually parsing the right value for its rank, and that each main.py actually sees all 8 gpus. 
2.  Are you using top-of-tree Apex?  If you're using, for example, something that came within our 18.05 or 18.06 container, there may be some errors that we've corrected in the most recent version.
3.  "/workspace/imagenet/" is a positional argument.  Maybe your `main.py` is somehow parsing this argument differently than mine, and it's messing up the subsequent parsing of rank.  Try `print(args.data)` [here](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main.py#L166) to make sure `main.py` is parsing "/workspace/imagenet/" correctly.
4.  As a sanity check, are you able to run [the simple Apex distributed example](https://github.com/NVIDIA/apex/tree/master/examples/FP16_Optimizer_simple/distributed_apex)?

**Comment by csarofeen** [comment]
I can't reproduce this error locally. I tried top of tree of Apex and PyTorch and am training fine with your command. Could you please try updating PyTorch and Apex and try again? If it reproduces could you try to provide any more information you think could be relevant?

**Comment by MarcelSimon** [comment]
I'm having the same issue. The simple apex distributed example works without problems, but the ImageNet example doesn't. Everything was working fine until recently, 

If I print the rank and the world size, then I get the following output:
```
$ python -m apex.parallel.multiproc main_fp16_optimizer.py --fp16 /asdtas
['main_fp16_optimizer.py', '--fp16', '/asdtas', '--world-size', '2', '--rank', '0']
['main_fp16_optimizer.py', '--fp16', '/asdtas', '--world-size', '2', '--rank', '1']
0 2
Traceback (most recent call last):
  File "main_fp16_optimizer.py", line 462, in <module>
    main()
  File "main_fp16_optimizer.py", line 119, in main
    rank=args.rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: more than one node have assigned same rank at /opt/conda/conda-bld/pytorch_1524590031827/work/torch/lib/THD/process_group/General.cpp:17
Traceback (most recent call last):
  File "main_fp16_optimizer.py", line 462, in <module>
    main()
  File "main_fp16_optimizer.py", line 119, in main
    rank=args.rank)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: more than one node have assigned same rank at /opt/conda/conda-bld/pytorch_1524590031827/work/torch/lib/THD/process_group/General.cpp:17
```
This error also occurs with older commits, not sure why it stopped working. Maybe something within pytorch changed? Let me know if there is anything I could try.

**Comment by MarcelSimon** [comment]
I think I identified the issue: I had to delete the file `sync.file` in my directory, then everything runs just fine as normal. I stumbled across this solution because `main_fp16_optimizer.py` ran fine in an empty directory, but didn't work in my main code directory. So I guess there was some old stuff in this file, which causes problems. Unfortunately, I didn't make a copy of the file, so I cannot provide anything here. But maybe it makes sense to delete the file on startup.

**Comment by mcarilli** [comment]
Ok, that makes sense.  In my tests, sync.file only exists very briefly (for the duration of `torch.distributed.init_process_group`) and then is automatically deleted.  I can only catch it being created by running `watch -n 0.1 ls` from another terminal while I launch the script.

I'm in the process of deprecating the Apex launcher script (`apex.parallel.multiproc`) and moving examples to use the official Pytorch launcher script (`torch.distributed.launch`).  The Pytorch launcher script also works fine with `apex.parallel.DistributedDataParallel`, it just requires changing the training scripts to parse for a different argument.  Also, crucially, `torch.distributed.launch` provides environment variables which are used instead of `sync.file` to initialize the process group, so hopefully this method will be more robust against your issue.

It is still very helpful to know what the root cause was, though, so I know it's not some deeper underlying problem with `apex.parallel.DistributedDataParallel`.  Thank you!

**Comment by mcarilli** [comment]
Examples have been moved to use `torch.distributed.launch`, so they no longer create `sync.file`.  `apex.parallel.multiproc` is still present, and any scripts that used it will continue to work, but I will add a deprecation warning soon.
