### ISSUE TITLE
Arch Build Issues: provide pypi installs?

### ISSUE THREAD

**Issue by jramapuram** [NVIDIA/apex#29]
Can't seem to compile apex on arch (even tried setting `CC` and `CXX` to gcc-5 / g++-5 ) : 
https://gist.github.com/jramapuram/d19b0e8a21d7a4586b366b9744b6e211

**Comment by mcarilli** [comment]
Apex is now a Python-only package for simplicity and robustness.  We're working on moving Apex's former C++ backend into Pytorch itself.  In the meantime, Amp, FP16_Optimizer, and apex.parallel.DistributedDataParallel continue to work, although Amp may exhibit mild (~2%) performance reduction.  This performance hit is temporary and will be reversed once the C++ backend is available for Amp to use through Pytorch core.

**Comment by jramapuram** [comment]
Great, thanks very much! Will give this a shot and report back. Looking forward to Amp integration in pytorch: will make fp16 training a whole lot easier. Any idea on the timeline for this? I can pull pytorch and compile it if the PR has been accepted into master.

**Comment by jramapuram** [comment]
This works perfectly now. pip install works; the build works as well. I had some issues with an AUR version of gcc-6 on arch causing the above conflicts. User error :)
