### ISSUE TITLE
"torch.nn.Model" object has no attribute 'named_buffers'

### ISSUE THREAD

**Issue by Wowoho** [NVIDIA/apex#290]
When I run apex.amp.initialize()
It tells me:
"torch.nn.Model" object has no attribute 'named_buffers'

**Comment by Wowoho** [comment]
x

**Comment by WrathOfGrapes** [comment]
@Wowoho Why did you close the issue?
Did you find any solution?

**Comment by ptrblck** [comment]
@WrathOfGrapes 
`named_buffers` was apparently indeed added after the `0.4.1` release.
Could you update PyTorch to the latest version as described in the [PyTorch website](https://pytorch.org/get-started/locally/) or do you need to use `0.4.1`?

**Comment by WrathOfGrapes** [comment]
@ptrblck 
I have a heavy project to adapt to pytorch 1.0, and I hoped I could avoid it.

I'm just confused, because the Apex documentation explicitly states that it supports pytorch >= 0.4.
