### ISSUE TITLE
module 'apex.amp' has no attribute 'initialize'?

### ISSUE THREAD

**Issue by xwjBupt** [NVIDIA/apex#296]
hi,this is my code,but it get an error shows:

AttributeError: module 'apex.amp' has no attribute 'initialize'

what  is the problem?thanks~
```
    from apex import amp
    model = build_detection_model(cfg)
    device = torch.device(cfg.MODEL.DEVICE)
    model.to(device)
    

    optimizer = make_optimizer(cfg, model)
    scheduler = make_lr_scheduler(cfg, optimizer)

    # Initialize mixed-precision training
    use_mixed_precision = cfg.DTYPE == "float16"
    amp_opt_level = 'O1' if use_mixed_precision else 'O0'
    model, optimizer = amp.initialize(model, optimizer, opt_level=amp_opt_level)
```

**Comment by miguelvr** [comment]
I got this error as well. I solved it by cloning and installing in the root path of my repo.

This should be addressed nevertheless

**Comment by ptrblck** [comment]
@xwjBupt How did you install apex? Did you build it from source?

@miguelvr Could you explain how you solved it? 
Did you build apex in another folder and had to move it to a specific location in order to work properly?

**Comment by miguelvr** [comment]
> @miguelvr Could you explain how you solved it?
> Did you build apex in another folder and had to move it to a specific location in order to work properly?

I initially cloned apex to the folder where I keep all my git project and installed it there, with a conda env activated. With this setup I couldn't run `from apex import amp` from anywhere except this projects folder.

To solve the issue I moved the apex folder into my the project folder I was running and without needing to install it again, it now worked.

**Comment by ptrblck** [comment]
Just to clarify, you can only import apex, if the apex folder is inside your current working directory?
If so, could you post some information about your setup (OS, Python version, CUDA version etc.) as I would like to try to reproduce this issue.

**Comment by xwjBupt** [comment]
hi @ptrblck, i reinstall the apex from source and problem solved

**Comment by zhixuanli** [comment]
I have reinstalled many times, this problem still remains.

OS: Ubuntu 16.04 LTS
Python: 3.6
CUDA: 9.0
Pytorch: 1.1.0 compiled with cuda 9.0
apex: 0.1, compiled under the above configuration.

The command of apex install :
```
git clone https://github.com/NVIDIA/apex.git && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

I'm trying to run my python code using 8 K80 GPUs and this problem occurred.
Running on a machine that has 4*2080ti is fine.

Except for copying the apex code directly into my project, is there any other good solution?

Thank you so much!

**Comment by henrymai** [comment]
I would suggest building and then mounting your code into a container, this will avoid any local machine configuration issues you might have (this is the main purpose of containers).

Here is an example Dockerfile for a docker container:
```
FROM nvcr.io/nvidia/pytorch:19.05-py3

RUN pip uninstall -y apex pytorch torchvision

RUN conda install -y pytorch torchvision cudatoolkit=10.0 -c pytorch

RUN git clone https://github.com/NVIDIA/apex.git && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

Note: this example is just a stripped version of my own private Dockerfile and I have not tested this stripped down version.

Then you can run the container with docker and mount your code in using the `-v` flag or if you want to avoid mounting your code, you can use Singularity: https://singularity.lbl.gov/ to run the docker container.

**Comment by zhzgithub** [comment]
use this install command,attention to add '--user':
`git clone https://github.com/NVIDIA/apex.git && cd apex && pip install --upgrade -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" . --user`

**Comment by Hannabrahman** [comment]
any solution fro this issue? I have tried putting it in the current working directory and also added ```--use``` when installing it, but still have the error.
