### ISSUE TITLE
TorchScript Support

### ISSUE THREAD

**Issue by justusschock** [NVIDIA/apex#308]
Does Apex support `torch.jit.ScriptModule`s, traced modules and `torch.jit.script`s? From my understanding the underlying operation, which is patched, should be the same. 

~~I'm mainly asking because a quick search showed me, that the [_initialize](https://github.com/NVIDIA/apex/blob/1c464b48472e32bdb752f77815502bffe0acd284/apex/amp/_initialize.py#L156) function only checks against `torch.nn.Module`~~

If it is supported, are there any limitations (besides the one coming with `TorchScript`?)

EDIT: I just realized, that the `ScriptModule` is actually a subclass of  `torch.nn.Module`, so instance checks work for them too. my question regarding the official support and limitations remains the same though.

**Comment by mcarilli** [comment]
Amp interaction with the JIT is under investigation.  Eventually, we'd like the JIT itself to natively support mixed precision training, but this is a long term (several-month) effort.
