### ISSUE TITLE
where is the definition of to_python_float()

### ISSUE THREAD

**Issue by un-knight** [NVIDIA/apex#311]
https://github.com/NVIDIA/apex/blob/4d325d2f25ec0c6a1e649ee2fee2170972f32c0a/examples/imagenet/main_amp.py#L352

I can't find the definition of `to_python_float()`

**Comment by ptrblck** [comment]
It's defined in [apex/fp16_utils/fp16util.py](https://github.com/NVIDIA/apex/blob/4d325d2f25ec0c6a1e649ee2fee2170972f32c0a/apex/fp16_utils/fp16util.py#L176).

**Comment by mcarilli** [comment]
`to_python_float` really isn't necessary at all.  I think that was legacy code from a long time ago that I've kept because it isn't broken at all (it does the right thing for pytorch 1.0).  I'll probably change those calls to simply use `.item()` at some point.

**Comment by un-knight** [comment]
I agree with you @mcarilli , and `item()` is exactly what I am using.
