### ISSUE TITLE
Is it possible to specify which GPUs to use

### ISSUE THREAD

**Issue by Msabih** [NVIDIA/apex#313]
Hi,

We have a use case where on a single machine, some GPUs are reserved for some tasks therefore we can only use certain GPUs for training. With DataParallel, its fairly easy to specify which GPUs to use however with DistributedDataParallel of apex, I am not able to find, how to specify this.

Could someone kindly help clarify this ?

**Comment by Msabih** [comment]
I figured out a way using CUDA_VISIBLE_DEVICES

**Comment by mcarilli** [comment]
Yes, see https://github.com/NVIDIA/apex/issues/162#issuecomment-466133930 and https://github.com/NVIDIA/apex/issues/162#issuecomment-466144252.  Bottom line, this should work:
launch job 1
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
python -m torch.distributed.launch --nproc_per_node=4 --master_port=2345 train1.py args...
```
launch job 2
```
export CUDA_VISIBLE_DEVICES=4,5,6,7
python -m torch.distributed.launch --nproc_per_node=4 --master_port=2345 train2.py args...
```

This approach should work with either `torch.nn.parallel.DistributedDataParallel` or `apex.parallel.DistributedDataParallel`.  The [simple distributed example](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed) shows both.  The only thing that must be changed to switch between them is the [DDP constructor call](https://github.com/NVIDIA/apex/blob/master/examples/simple/distributed/distributed_data_parallel.py#L46-L52).

**Comment by SharpCoiner** [comment]
But is there way to do it dynamically? I have a situation when at some time I want to train model with only few GPUs, when to switch to more or less of them.
