### ISSUE TITLE
Using --keep-batchnorm-fp32 with --opt-level O1 results in error

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/apex#320]
python main_amp.py -a resnet50 -j 20 -b 128 --opt-level O1 --keep-batchnorm-fp32 True /data/imagenet/images/

results in the following error:

`Traceback (most recent call last):
  File "main_amp.py", line 506, in <module>
    main()
  File "main_amp.py", line 153, in main
    loss_scale=args.loss_scale
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/frontend.py", line 333, in initialize
    _amp_state.opt_properties.keep_batchnorm_fp32 = keep_batchnorm_fp32
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/frontend.py", line 73, in __setattr__
    "keep_batchnorm_fp32 was {}".format(keep_batchnorm_fp32))
NameError: name 'keep_batchnorm_fp32' is not defined
`

Is it something expected?

**Comment by ptrblck** [comment]
Hi @vinhngx,

thanks for letting us know about this issue.
It seems `keep_batchnorm_fp32` is undefined in this particular line of code so the PR should fix this issue and raise a proper exception.

However, for your use case just skip the `--keep-batchnorm-fp32 True` argument, as `opt_level = 'O1'` automatically patches batchnorm functions to run in FP32.

Let me know, if removing this argument fixes your error.

**Comment by mcarilli** [comment]
> Is this something expected?
Yes, it should raise an error in such a case, because using keep_batchnorm_fp32 in conjunction with O1 doesn't make sense.  However, it should have raised our error with an explanation, not a generic Python error.  PR #321 fixed the error message.
