### ISSUE TITLE
Does Apex really support PyTorch 0.4.1?

### ISSUE THREAD

**Issue by WrathOfGrapes** [NVIDIA/apex#328]
In Readme.md it says:

> PyTorch 0.4 or newer.

But sample code [examples/simple/distributed](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed) goes down with error `AttributeError: 'Linear' object has no attribute 'named_buffers'`, because `named_buffers` method of torch.Module was introduced after 0.4.1 version.

Is there any build, that supports pytorch 0.4.1? If not, at least maybe the readme.md should be changed?

P.S.: I'm using apex with CUDA and C++ libraries, installed with command `pip install -v --no-cache-dir .`

**Comment by ptrblck** [comment]
Hi @WrathOfGrapes,

thanks for letting us know about this issue!
The `named_buffers()` call slipped in and creates the backward incompatibility.
I'll check what changes would be needed to successfully run with PyTorch `0.4` again.

**Comment by ptrblck** [comment]
I've pushed a quick fix to this branch:
https://github.com/ptrblck/apex/tree/pytorch04

Could you pull it and test your code with it?

**Comment by mcarilli** [comment]
Please reopen if the PR did not fix your issue.

**Comment by WrathOfGrapes** [comment]
@ptrblck Sorry for a late reply. Thank you, the fix solves problems with launching examples on PyTorch 0.4.1. Unfortunately there are some similar backward compatibility issues, when you try to add `apex.parallel.SyncBatchNorm` layer to your module.

Unfortunately, I don't have access to error logs right now, but they are caused by `apex.parallel.SyncBatchNorm` using post 0.4.0 pytorch functions.

**Comment by ptrblck** [comment]
@WrathOfGrapes thanks for the information.
I ran into an issue on PyTorch `0.4.1` where the output of `SyncBatchNorm` is suddenly `None`.
Do you encounter the same issue or a different one?

CC @jjsjann123

**Comment by WrathOfGrapes** [comment]
@ptrblck Unfortunately, I gave up on running my project with Apex on Pytorch 0.4.1 :(
I was getting a lot of errors during various stages of my training process. Some of them were related to SyncBatchNorm (but not your particular one).

**Comment by ptrblck** [comment]
@WrathOfGrapes Is your project working with apex on PyTorch 1.1 now or are you stuck somewhere porting your code?
Let us know, if we can be of any help getting apex to run.

**Comment by WrathOfGrapes** [comment]
@ptrblck Yeah, I tried migrating to PyTorch 1.1, but Apex was still problematic to integrate. I was getting some "IllegalMemoryAccess" and some other CUDA-level errors (that I couldn't find in issues).

I have a pretty big model (for Automatic Speech Recognition) with distributed training, batch-norms and a lot of other stuff, so it's too difficult to localize and report reproducible errors. So I decided to place Apex integration on hold for some time and temporarily switch to other tasks.

Thank you, @ptrblck , I really appreciate your support!

**Comment by ptrblck** [comment]
@WrathOfGrapes is the `IllegalMemoryAccess` error only thrown if you are using `amp` or always using your code in PyTorch 1.1 on a GPU?
In the latter case, you could try to run your code using
```
CUDA_LAUNCH_BLOCKING=1 python script.py args
```
and check, e.g. if no values are out of bounds.

In the former case, we would need to reproduce this issue in order to debug it, so let us know, if you find some time for debugging and we'll have a look at it.

**Comment by WrathOfGrapes** [comment]
@ptrblck The code runs fine without `amp`.

I'm hoping to find some time during this month to localize and summarize the issues for you.
