### ISSUE TITLE
'AmpOptimizerState' object has no attribute 'all_fp32_params'

### ISSUE THREAD

**Issue by thuwyh** [NVIDIA/apex#332]
I initialized the model and optimizer with amp
```
optimizer = Adam(filter(lambda p: p.requires_grad, model.parameters()), args.lr)
scheduler = ReduceLROnPlateau(optimizer, patience=1, factor=0.1, verbose=True, mode='max')
model, optimizer = amp.initialize(model, optimizer, opt_level="O1", verbosity=0)
```

and then I tried to add a group of params to the optimizer before training

```
optimizer.add_param_group({'params':unfreezed_params, 'lr':lr})
```

I got the following error
```
AttributeError: 'AmpOptimizerState' object has no attribute 'all_fp32_params'
```

System info:
Ubuntu 18.04, cuda 10.0.130, pytorch 1.1.0

**Comment by Tetratrio** [comment]
I have the same issue, just tried the newly added feature of adding new parameter groups to an optimizer. Fails for the tested optimization levels O1 and O2. Same error for me as well for O1 while O2 gives me:
```
AttributeError: 'AmpOptimizerState' object has no attribute 'fp16_groups'
```

installed apex without extensions.

System info:
Ubuntu 16.04, cuda 10.0.130, pytorch 1.1.0

**Comment by mcarilli** [comment]
I think I know what's going on.  Amp relies on some internal stash that has knowledge of the parameters.  Typically this is silently lazy-initialized by the backward context manager, or an initial call to optimizer.zero_grad().

I anticipated that people would only want to add param groups later on in training, after many steps had already been taken and the lazy stash initialization had taken place.  I will make sure add_param_group also implements initialization if necessary.

**Comment by Tetratrio** [comment]
Hey,

I have tried doing a couple of iterations of training before calling `add_param_group` but still get the same error.
I have also tried calling `zero_grad()` on all optimizers after the amp initialization call but that does not solve the problem.

```
  File "/home/as/workspaces/pyflash/pyflash/training/engine/gan.py", line 582, in _adjust_model
    optimizer.add_param_group({'params': params, **param_group_opts})
  File "/home/as/anaconda3/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 393, in new_add_param_group
    stash.all_fp32_params.append(param)
AttributeError: 'AmpOptimizerState' object has no attribute 'all_fp32_params'
```

`param_group_opts` is just `{'betas': (0, 0.99)}`. I set the learning for all param groups at a later stage.

**Comment by Tetratrio** [comment]
@thuwyh 
Quick workaround is to do the following:
```
optimizer = Adam(filter(lambda p: p.requires_grad, model.parameters()), args.lr)
scheduler = ReduceLROnPlateau(optimizer, patience=1, factor=0.1, verbose=True, mode='max')
model, optimizer = amp.initialize(model, optimizer, opt_level="O1", verbosity=0)
optimizer._lazy_init_maybe_master_weights()
```

**Comment by thuwyh** [comment]
@Tetratrio 
It works. Thank you!

**Comment by mcarilli** [comment]
I just pushed a fix that ensures `add_param_group` will call `_lazy_init_maybe_master_weights()` if it hasn't been called already.  _lazy_init_maybe_master_weights is only intended to be called once (and never manually from the script side) so if you reinstall Apex, you should remove your `_lazy_init` call and `add_param_group` by itself should work anywhere.
