### ISSUE TITLE
Windows 10 with anaconda, installation error 

### ISSUE THREAD

**Issue by Shiro-LK** [NVIDIA/apex#335]
Hi ,

I am trying to install apex on my windows 10.
I have installed currently anaconda with cuda 10 (cuda toolkit) and pytorch. That works well.
But when I launch the command  `pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .` I get an error about NVCC not found.
Is there a way to install apex on windows10 using anaconda ?
> Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
> Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
> Created temporary directory: C:\Users\Shiro\AppData\Local\Temp\pip-ephem-wheel-cache-lad1ick2
> Created temporary directory: C:\Users\Shiro\AppData\Local\Temp\pip-req-tracker-ntiu8rps
> Created requirements tracker 'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-tracker-ntiu8rps'
> Created temporary directory: C:\Users\Shiro\AppData\Local\Temp\pip-install-xc91fwpi
> Processing c:\users\shiro\apex
>   Created temporary directory: C:\Users\Shiro\AppData\Local\Temp\pip-req-build-fgj_ek8b
>   Added file:///C:/Users/Shiro/apex to build tracker 'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-tracker-ntiu8rps'
>     Running setup.py (path:C:\Users\Shiro\AppData\Local\Temp\pip-req-build-fgj_ek8b\setup.py) egg_info for package from file:///C:/Users/Shiro/apex
>     Running command python setup.py egg_info
>     torch.__version__  =  1.1.0
>     running egg_info
>     creating pip-egg-info\apex.egg-info
>     writing pip-egg-info\apex.egg-info\PKG-INFO
>     writing dependency_links to pip-egg-info\apex.egg-info\dependency_links.txt
>     writing top-level names to pip-egg-info\apex.egg-info\top_level.txt
>     writing manifest file 'pip-egg-info\apex.egg-info\SOURCES.txt'
>     reading manifest file 'pip-egg-info\apex.egg-info\SOURCES.txt'
>     writing manifest file 'pip-egg-info\apex.egg-info\SOURCES.txt'
>   Source in c:\users\shiro\appdata\local\temp\pip-req-build-fgj_ek8b has version 0.1, which satisfies requirement apex==0.1 from file:///C:/Users/Shiro/apex
>   Removed apex==0.1 from file:///C:/Users/Shiro/apex from build tracker 'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-tracker-ntiu8rps'
> Skipping bdist_wheel for apex, due to binaries being disabled for it.
> Installing collected packages: apex
>   Created temporary directory: C:\Users\Shiro\AppData\Local\Temp\pip-record-o0vdkzsy
>     Running command 'C:\Users\Shiro\Anaconda3\envs\DL-torch\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-build-fgj_ek8b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\Shiro\AppData\Local\Temp\pip-record-o0vdkzsy\install-record.txt' --single-version-externally-managed --compile
>     torch.__version__  =  1.1.0
>     Informationÿ: impossible de trouver des fichiers pour le(s) modŠle(s) sp‚cifi‚(s).
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Shiro\AppData\Local\Temp\pip-req-build-fgj_ek8b\setup.py", line 62, in <module>
>         raise RuntimeError("--cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.")
>     RuntimeError: --cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
>   Running setup.py install for apex ... error
> Cleaning up...
>   Removing source in C:\Users\Shiro\AppData\Local\Temp\pip-req-build-fgj_ek8b
> Removed build tracker 'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-tracker-ntiu8rps'
> ERROR: Command "'C:\Users\Shiro\Anaconda3\envs\DL-torch\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-build-fgj_ek8b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\Shiro\AppData\Local\Temp\pip-record-o0vdkzsy\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Shiro\AppData\Local\Temp\pip-req-build-fgj_ek8b\
> Exception information:
> Traceback (most recent call last):
>   File "C:\Users\Shiro\Anaconda3\envs\DL-torch\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
>     status = self.run(options, args)
>   File "C:\Users\Shiro\Anaconda3\envs\DL-torch\lib\site-packages\pip\_internal\commands\install.py", line 414, in run
>     use_user_site=options.use_user_site,
>   File "C:\Users\Shiro\Anaconda3\envs\DL-torch\lib\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_reqs
>     **kwargs
>   File "C:\Users\Shiro\Anaconda3\envs\DL-torch\lib\site-packages\pip\_internal\req\req_install.py", line 951, in install
>     spinner=spinner,
>   File "C:\Users\Shiro\Anaconda3\envs\DL-torch\lib\site-packages\pip\_internal\utils\misc.py", line 776, in call_subprocess
>     % (command_desc, proc.returncode, cwd))
> pip._internal.exceptions.InstallationError: Command "'C:\Users\Shiro\Anaconda3\envs\DL-torch\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Shiro\\AppData\\Local\\Temp\\pip-req-build-fgj_ek8b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\Shiro\AppData\Local\Temp\pip-record-o0vdkzsy\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Shiro\AppData\Local\Temp\pip-req-build-fgj_ek8b\
> Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
> Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect

**Comment by mcarilli** [comment]
This is probably not an Apex-specific issue, but rather, the Pytorch extension builder being unable to find nvcc.  Where is nvcc installed on your system?  Also, to determine if this error is Apex-specific or not, you can try building the Pytorch cpp extensions tests:
```
git clone https://github.com/pytorch/pytorch.git
cd pytorch/test/cpp_extensions
python setup.py install
```

**Comment by Shiro-LK** [comment]
Hi thanks for the response.
I finally found the issue, it seems that installing cuda with anaconda does not install nvcc. I install manually cuda and other thing without anaconda, then the installation of apex works.

Issue solved

**Comment by mcarilli** [comment]
Good to know, thanks!

**Comment by TeonaEcon** [comment]
Shiro-LK said: I install manually cuda and other thing without anaconda. "Other things" is too unspecific. I have installed CUDA without anaconda from here: https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal.
Then I retried installing apex, it did not work. What else should I have done for getting apex?

**Comment by Shiro-LK** [comment]
Hi,

sorry for the delay. Other things were about the Visual studio 2015 which seemed necessary.
But it does not seem to work with newer version (pytorch above 1.1). I am trying with pytorch 1.3.1 and I have some others error related to nvcc. I will try to install newer version of visual studio

**Comment by fandemisterling100** [comment]
> Hi thanks for the response.
> I finally found the issue, it seems that installing cuda with anaconda does not install nvcc. I install manually cuda and other thing without anaconda, then the installation of apex works.
> 
> Issue solved

Hi!! I'm having the same problem, could you explain to me how can I fix it?

**Comment by TotzkePaul** [comment]
I used conda forge to get apex installed and 'working'. 
https://anaconda.org/conda-forge/nvidia-apex

"Original ImportError was: ModuleNotFoundError("No module named 'amp_C')"

I'm still interested in getting it complied on Windows 10 for CUDA 10.2.
Is this possible right now for windows on the latest version? see https://gist.github.com/ax3l/9489132 

Is this the right way to install the toolkit in conda?
conda install -c anaconda cudatoolkit
