### ISSUE TITLE
Unable to install tensorflow in anaconda

### ISSUE THREAD

**Issue by Sanidhya-Tyagi** [NVIDIA/apex#338]

**Comment by mcarilli** [comment]
Apex is Pytorch-specific.  I'm not a Tensorflow guy so I'm not sure of the relevant documentation, but the following may be useful:
https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html#tensorflow-amp
https://devblogs.nvidia.com/nvidia-automatic-mixed-precision-tensorflow/
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/experimental/mixed_precision.py#L75-L112
