### ISSUE TITLE
What is the main difference between Adam and FusedAdam?

### ISSUE THREAD

**Issue by USTClj** [NVIDIA/apex#340]
Is it necessary to replace the Adam optimizer in pytorch if we use opt_level=o1 ?

**Comment by mcarilli** [comment]
With current apex master, `torch.optim.Adam` should work with any opt_level.

However, `apex.optimizers.FusedAdam` only works with opt_level O2.  I'm working on fixing this, it's turning out to be tricky haha

I'll ping this issue once that's done.

**Comment by hitvoice** [comment]
@mcarilli Is it fixed now?
