### ISSUE TITLE
Segmentation fault...

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA/apex#35]
Ubuntu 18.04.1
Cuda 9.2
C++ 7.3.0
Python 3.6.5

```
nvidia/apex$ python setup.py install
Segmentation fault (core dumped)
```

Cheers
Pei

**Comment by mcarilli** [comment]
Are you using the most recent version of Apex?  Top of tree apex is python-only, and the setup.py is extremely simple.  If that's segfaulting, it's a strange issue.

**Comment by wangdongxuking61** [comment]
> Ubuntu 18.04.1
> Cuda 9.2
> C++ 7.3.0
> Python 3.6.5
> 
> ```
> nvidia/apex$ python setup.py install
> Segmentation fault (core dumped)
> ```
> Cheers
> Pei

i have the same problem
try 'pip install --upgrade setuptools'
it helps for me

**Comment by layumi** [comment]
I successfully install the `apex` but face the `segmentation fault` when training.

So I check the installation again. I notice that I ignore the warning when installing apex. My bad.
Remember to update the gcc 4.x to gcc 5.x , which may also lead to `segmentation fault`

In a nutshell, the solution is 
`conda install -c psi4 gcc-5`

**Comment by patrick-g-zhang** [comment]
> I successfully install the `apex` but face the `segmentation fault` when training.
> 
> So I check the installation again. I notice that I ignore the warning when installing apex. My bad.
> Remember to update the gcc 4.x to gcc 5.x , which may also lead to `segmentation fault`
> 
> In a nutshell, the solution is
> `conda install -c psi4 gcc-5`

Thank you!

**Comment by ann22** [comment]
> I successfully install the `apex` but face the `segmentation fault` when training.
> 
> So I check the installation again. I notice that I ignore the warning when installing apex. My bad.
> Remember to update the gcc 4.x to gcc 5.x , which may also lead to `segmentation fault`
> 
> In a nutshell, the solution is
> `conda install -c psi4 gcc-5`

Does updating the gcc version affect other dependencies
