### ISSUE TITLE
AttributeError: module 'apex.amp' has no attribute 'initialize'

### ISSUE THREAD

**Issue by zhixuanli** [NVIDIA/apex#357]
After reading #296 
I have reinstalled many times, but this problem still remains.

Here's my code:
```
model, optimizer = apex.amp.initialize(model.cuda(), optimizer, opt_level=args.opt_level, keep_batchnorm_fp32=args.keep_batchnorm_fp32, loss_scale=args.loss_scale)
```

OS: Ubuntu 16.04 LTS
Python: 3.6
CUDA: 9.0
Pytorch: 1.1.0 compiled with cuda 9.0
apex: 0.1, compiled under the above configuration.

The command of apex install :
```
git clone https://github.com/NVIDIA/apex.git && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

I'm trying to run my python code using 8 K80 GPUs and this problem occurred.
Running on a machine that has 4*2080ti is fine.

Except for copying the apex code directly into my project, is there any other good solution?

Thank you so much!

**Comment by vince62s** [comment]
either you have to really uninstall, or add --upgrade in the pip install command.

**Comment by zhixuanli** [comment]
1. I have used the way to find all the files containing the name "apex" and delete them.
2. pip is the newest version.

Thanks for your help.

**Comment by zhixuanli** [comment]
The `__init__.py` in `~/anaconda3/envs/pytorch/lib/python3.6/site-packages/apex/amp` is like this:
```
from .amp import init, half_function, float_function, promote_function,\
    register_half_function, register_float_function, register_promote_function
```

But the correct version is:
```
from .amp import init, half_function, float_function, promote_function,\
    register_half_function, register_float_function, register_promote_function
from .handle import scale_loss, disable_casts
from .frontend import initialize
from ._amp_state import master_params, _amp_state

```

It's so strange.......

I'll try to uninstall again. @vince62s

**Comment by zhixuanli** [comment]
After two more times reinstall, this problem is solved....interesting
