### ISSUE TITLE
Prioritize Custom Batch Type "to" method

### ISSUE THREAD

**Issue by felix-schneider** [NVIDIA/apex#363]
`amp._initialize.applier` checks for a `to()` method of a custom batch type *last*, after checking for Mapping, Iterable, etc. This is a problem for custom batch types that are also iterable, such as those created by torchtext, as it will cause a new object to be created (in the case of torchtext resulting in a crash) rather than the custom `to()` method being called.

Solution: The check for the `to` method should be the first, not the last.

**Comment by mcarilli** [comment]
That's a good point but I don't think the `to` check should be first.  I think the 'to' check should be moved before the iterables, so it doesn't interfere with processing of vanilla Tensors.  For example, we don't want to accidentally convert incoming int tensors to half.
