### ISSUE TITLE
Commit/release compatible with pytorch 1.0.1.post2?

### ISSUE THREAD

**Issue by che85** [NVIDIA/apex#376]
Hi there, 
can you tell me with version of amp or which specific commit is known to work with pytorch 1.0.1.post2?

Thank you

**Comment by mcarilli** [comment]
The most recent master is almost always best across Pytorch versions.  Are you seeing a particular problem with the most recent master + pytorch 1.0.1.post2?

**Comment by che85** [comment]
No, I think it was again the issue that I compiled apex with gcc 4.8.5.

So  latest pytorch version should work with the latest apex?

**Comment by che85** [comment]
Comparing version pytorch 1.0.1.post2 with the most recent available version 1.1, would it worth updating to the current version? I am not sure if I want to risk it and maybe break things..

**Comment by mcarilli** [comment]
Yes, the latest Apex should work with the latest Pytorch.  Please reopen if you find any problems...

As for whether it's worth updating to 1.1, I don't know.  You can review [the release notes](https://github.com/pytorch/pytorch/releases) to see if there's anything in particular that helps your use case.  For me, one of the most interesting features of 1.1 is that `torch.nn.parallel.DistributedDataParallel` now supports modules where some of the parameters may be unused in a given iteration, so for 1.1+, imo there's no reason to use `apex.parallel.DistributedDataParallel` anymore (`torch.nn.parallel.DistributedDataParallel` should always be the default choice).

**Comment by che85** [comment]
I am not sure if it's related, but I am getting the following error after ~10 epochs:

```
[libprotobuf FATAL google/protobuf/wire_format.cc:829] CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?
```

**Comment by ptrblck** [comment]
Are you trying to store a checkpoint from multiple processes?
Have a look at [this example](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#save-and-load-checkpoints), where `rank` was used to only save the model from one process.
