### ISSUE TITLE
I do not think you need to preprocess train images to 256x256

### ISSUE THREAD

**Issue by tfboyd** [NVIDIA/apex#39]
"Train images are expected to be 256x256 jpegs."

The validation images are 256x256 I am pretty sure and is what the pytorch examples page says as does the code, but for PyTorch training you feed the training images raw from the imagenet downloaded unziped into folders with the category as the folder name.  The raw images from imagenet they are not preprocessed in anyway unlike with say mxnet and caffe2.  If they need to be 256x256 can you provide the script that handles that?

**Comment by mcarilli** [comment]
You're right, I believe that documentation is a holdover from a long-lost version of our example.  Our script should work with the ordinary (variably-sized) imagenet dataset.  I'll update the readme now.
