### ISSUE TITLE
I try the example when init init_process_group got an error

### ISSUE THREAD

**Issue by PistonY** [NVIDIA/apex#393]
https://github.com/NVIDIA/apex/blob/574fe2449cbe6ae4c8af53c6ecb1b5fc13877234/examples/imagenet/main_amp.py#L121

I got `ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set` this when I run it.

I use Pytorch 1.1.0 and Ubuntu 18.04.
How to solve it, thx.

**Comment by PistonY** [comment]
Is this you bug or Pytorch itself?

**Comment by PistonY** [comment]
And I tried to use `DataParallel` from Pytorch.
I use `amp.initialize` to init my model
```python
if args.dtype == 'float16':
    logger.info('Train with FP16.')
    model, optimizer = amp.initialize(model, optimizer, opt_level='O1')
```
But I found that it has the same memory cost with FP32.
Why does this happen?Must I use `DDP`?

**Comment by ptrblck** [comment]
Hi @PistonY,

how are you executing the script?
If you are running the distributed example in `main_amp.py`, note that you should call:
```python
python -m torch.distributed.launch --nproc_per_node=NUM_GPUS main_amp.py args...
```
as described in the [README](https://github.com/NVIDIA/apex/tree/574fe2449cbe6ae4c8af53c6ecb1b5fc13877234/examples/imagenet#distributed-training).

**Comment by PistonY** [comment]
Hello, distributed training meaning multiple servers and GPUs or one server with multiple GPUs? If I only have one server with 4 GPUs, What should I do?

**Comment by PistonY** [comment]
I've fixed this, thx @ptrblck .

**Comment by Hesene** [comment]
> I've fixed this, thx @ptrblck .

hi I meet a same problem about same memory cost with FP32. Could you share your solution?

**Comment by PistonY** [comment]
@Hesene use
```python
with amp.scale_loss(loss, optimizer) as scaled_loss:
     scaled_loss.backward()
optimizer.step()
```

**Comment by Hesene** [comment]
> @Hesene use
> 
> ```python
> with amp.scale_loss(loss, optimizer) as scaled_loss:
>      scaled_loss.backward()
> optimizer.step()
> ```

Thank you for your sharing, I do it, but get same result

**Comment by PistonY** [comment]
@Hesene it work with me.
This repo is awesome by the way @ptrblck,I got very good results on ImageNet. Thanks for doing this.

**Comment by Hesene** [comment]
> This repo is awesome by the way @ptrblck,I got very good results on ImageNet. Thanks for doing this.

OK, Thank you for your reply. I will try something else

**Comment by ptrblck** [comment]
@PistonY Thanks and I'll happily forward the appreciation to the whole team! :)

@Hesene Which `opt_level` and what kind of model are you using?

**Comment by Hesene** [comment]
> @PistonY Thanks and I'll happily forward the appreciation to the whole team! :)
> 
> @Hesene Which `opt_level` and what kind of model are you using?

I try O1 O2 and O3, but they only have a little change. My machine is 2*2080Ti, When I use single GPU to run the code, The memory will be reduced by half

**Comment by ptrblck** [comment]
Are you using our `DistributedDataParallel` approach ([link](https://github.com/NVIDIA/apex/tree/master/examples/simple/distributed)) or how do you parallelize your use case?

**Comment by drunkprogrammer** [comment]
Now I meet the same bug in torch 1.13.1 

`dist.init_process_group("nccl")
        rank = dist.get_rank()`   

   **ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set**

but it is not useful when I use the command
`python -m torch.distributed.launch --nproc_per_node=NUM_GPUS main_amp.py args...`

**Comment by drunkprogrammer** [comment]
> Now I meet the same bug in torch 1.13.1
> 
> `dist.init_process_group("nccl") rank = dist.get_rank()`
> 
> **ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set**
> 
> but it is not useful when I use the command `python -m torch.distributed.launch --nproc_per_node=NUM_GPUS main_amp.py args...`

Now maybe use 
`torchrun --standalone --nnodes=1 main.py
`
