### ISSUE TITLE
Where does apex.amp maintain master weights

### ISSUE THREAD

**Issue by un-knight** [NVIDIA/apex#395]
https://github.com/NVIDIA/apex/blob/574fe2449cbe6ae4c8af53c6ecb1b5fc13877234/apex/amp/_initialize.py#L186

In the step of initialization, I found amp just convert network parameters to `torch.float16` with the O2 configuration, so I want to know when and where will apex save the FP32 master weights?

**Comment by ptrblck** [comment]
Hi @un-knight,

the master weights are initialized in [lazy_init_with_master_weights](https://github.com/NVIDIA/apex/blob/1ccaaf4a8af9710bc0548ed68df05999bc48bec0/apex/amp/_process_optimizer.py#L13), which will be called in [prepare_backward_with_master_weights](https://github.com/NVIDIA/apex/blob/574fe2449cbe6ae4c8af53c6ecb1b5fc13877234/apex/amp/_process_optimizer.py#L80).

**Comment by un-knight** [comment]
Thanks a lot :)
