### ISSUE TITLE
Any update on GAN training?

### ISSUE THREAD

**Issue by ando-khachatryan** [NVIDIA/apex#397]
Hi, 
Thanks for the framework, it is very useful.
Is there any update on GANs? Has anyone succeeded in making them work? The documentation is vague, and the DCGAN example has had the status "coming soon" for several months.

**Comment by Jackerz312** [comment]
same question, i need an example for GANs please

**Comment by ptrblck** [comment]
We've merged the DCGAN example using `amp`:
https://github.com/NVIDIA/apex/tree/master/examples/dcgan

**Comment by ando-khachatryan** [comment]
Thanks a lot folks.
