### ISSUE TITLE
Update to new PyTorch Function API ("Legacy autograd function with non-static forward method is deprecated")

### ISSUE THREAD

**Issue by myleott** [NVIDIA/apex#401]
A new warning was added to pytorch recently: https://github.com/pytorch/pytorch/blob/fdfc676eb6c4d9f50496e564976fbe6d124e23a5/torch/csrc/autograd/python_function.cpp#L636-L638

This results in a lot of warning messages getting printed when using Apex Functions (e.g., FusedLayerNorm).

I've created a small PR to fix this for FusedLayerNorm (#400), but it should probably be done elsewhere too.

**Comment by ptrblck** [comment]
Thanks for the PR!
It looks like other `autograd.Functions` have been already written using the new style methods.
However, we'll run some tests internally and check, if we can spot more warnings.
