### ISSUE TITLE
FusedLayerNorm fails with batchsize >= 2**16

### ISSUE THREAD

**Issue by stephenroller** [NVIDIA/apex#411]
If the input tensor to FusedLayerNorm is >= 2**16, there appears to be an overflow and it causes catastrophically different results than the pytorch LayerNorm implementation. The following is an example of the worst and mean absolute differences for pytorch's implementation of LayerNorm and apex's, for a random input/weight/bias of the given batchsize:

```
$ python flntest.py --batchsize 65535
Worse case difference: 2.86102294921875e-06
Average case difference: 3.698113104633194e-08
```
That looks good -- differences between the two implementations are pretty close

However, if count overflows, all bets are off:
```
$ python flntest.py --batchsize 65536
Worse case difference: 14.040550231933594
Average case difference: 1.076439619064331
Failure
```

https://gist.github.com/stephenroller/ae87eef9d704fcf5797067f15a4b742e#file-flntest-py for the code to reproduce the test case.

**Comment by ngimel** [comment]
Thanks for reporting, we'll look into this. With current pytorch master I'm also getting an "invalid configuration error" from non-apex `layer_norm`.

**Comment by stephenroller** [comment]
Looks like y'all sorted this, marking as closed. Thanks!
