### ISSUE TITLE
scaled_loss.backward() returned an invalid gradient

### ISSUE THREAD

**Issue by iariav** [NVIDIA/apex#422]
Hi,
i'm trying to convert this Auto-Deeplab repository to use mixed precision - 
https://github.com/NoamRosenberg/AutoML

i use the new amp api as follows - 
        
        if args.cuda:
            self.model = self.model.cuda()

        if self.use_amp and args.cuda:
            self.model, [self.optimizer, self.architect_optimizer] = amp.initialize(
                self.model, [self.optimizer, self.architect_optimizer], opt_level="O1",
                keep_batchnorm_fp32=None, loss_scale="dynamic")

            print('cuda finished')`
and then during training i do - 

            output = self.model(image)

            loss = self.criterion(output, target)
            if self.use_amp:
                with amp.scale_loss(loss, self.optimizer) as scaled_loss:
                    scaled_loss.backward()
            else:
                loss.backward()`

if i use opt_level 01 i get the following error - 

> Traceback (most recent call last):
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 406, in <module>
    main()
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 399, in main
    trainer.training(epoch)
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 167, in training
    output = self.model(image)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ido/Deep/Pytorch/AutoML/auto_deeplab.py", line 186, in forward
    level4_new = self.cells[count] (None, self.level_4[-1], normalized_alphas)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ido/Deep/Pytorch/AutoML/cell_level_search.py", line 65, in forward
    s1 = self.preprocess1(s1)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ido/Deep/Pytorch/AutoML/operations.py", line 26, in forward
    return self.op(x)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: expected scalar type Half but found Float

and if i set opt_level "02" or "03" i get the following error (regardless if i set keep_batchnorm_fp32 to True\False) - 

> Traceback (most recent call last):
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 406, in <module>
    main()
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 399, in main
    trainer.training(epoch)
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 171, in training
    scaled_loss.backward()
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function MulBackward0 returned an invalid gradient at index 0 - expected type torch.cuda.FloatTensor but got torch.cuda.HalfTensor

i suspect it has something to do with the batchnorm but i have no idea what exactly. i read all the issues regarding bn in this repository but found no fix. any chance someone can take a look?

### env:
pytorch 1.1.0
cuda 10.0.130
cudnn 7501
GPU - Titan rtx
currently i didn't try running on multiple GPUs so no use of DataParallel.

### things i've tried:

- i've checked that torch.backends.cudnn.enabled returns True.
- i reinstalled pytorch+apex and it didn't change.
- tried applying the function fix_bn() suggested in one of the issues.
- if i run in opt_level "00" the code is running OK

thanks a lot in advance!

**Comment by iariav** [comment]
just a bit more info that might shed some light on this - 
when i added this bit of code (after initializing amp) - 

        for module in self.model.modules():
            if isinstance(module, torch.nn.modules.batchnorm._BatchNorm):
                # Hack to fix BN fprop without affine transformation
                if module.weight is None:
                    module.weight = torch.nn.Parameter(torch.ones(module.running_var.shape, dtype=module.running_var.dtype,
                                                            device=module.running_var.device), requires_grad=False)
                if module.bias is None:
                    module.bias = torch.nn.Parameter(torch.zeros(module.running_var.shape, dtype=module.running_var.dtype,
                                                           device=module.running_var.device), requires_grad=False)`

i was able to run successfully with opt_level "01".
opt_level "02" and "03" still give the same error as above.

**Comment by ptrblck** [comment]
Hi @iariav,

thanks for the information!
Could you try to manipulate the BN parameters before initializing `amp` and run the code again?

**Comment by iariav** [comment]
@ptrblck tnx.
i tried as you suggested to move that bit of code to before the amp.initialize but i still get the same outcome. opt level "01" works, but opt_level "02" and "03" still give the error:

> Traceback (most recent call last):
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 417, in <module>
    main()
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 410, in main
    trainer.training(epoch)
  File "/home/ido/Deep/Pytorch/AutoML/train_autodeeplab.py", line 182, in training
    scaled_loss.backward()
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/anaconda3/envs/pytorch_deeplab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function MulBackward0 returned an invalid gradient at index 0 - expected type torch.cuda.FloatTensor but got torch.cuda.HalfTensor

**Comment by ptrblck** [comment]
Thanks for the information.
If you would like to ignore the affine parameters in BN layers, you could also pass `affine=False` while creating these layers.
However, the actual error you are seeing, might be related to [this PR](https://github.com/pytorch/pytorch/pull/22750). 

We are trying to get the PR merged as soon as possible.

**Comment by iariav** [comment]
thanks again.
indeed, the PR you referenced looks very much related to my issue. 
i hope it'll solve it.
i might try to merge the changes locally tomorrow and see if the issue is fixed..

will keep you posted.

**Comment by iariav** [comment]
update - 
i merged the changes from the PR you mentioned locally and build pytorch from source (before that i worked with pytorch installed via pip) and i still get the same error massage when trying to run with opt_level 02\03 (01 runs fine).
i build pytorch in a fresh conda env, and there were no errors during installation so i don't think it's an installation problem. after building from source my pytorch version is now 1.3.0a0+7d20736 (plus the changes from the PR)

**Comment by ptrblck** [comment]
@iariav Thanks for rebuilding PyTorch with the PR! 
We'll try to reproduce this issue.

I assume you've added the mentioned code snippets in `train_autodeeplab.py`?
Do you have a current fork we could use as a baseline for debugging?

**Comment by iariav** [comment]
i had to make some other minor changes other then adding these code snippets (for instance i removed the Architect class and implemented the arch_optimizer in the main script. 
i'll make a fork and update.

**Comment by iariav** [comment]
Hi @ptrblck ,
please have a look in this fork - 
https://github.com/iariav/AutoML

i ran train_autodeeplab.py with the following parameters:
--backbone=xception
--out-stride=16
--dataset=cityscapes
--gpu-ids=0
--resize=512
--base_size=320
--crop_size=320
--batch-size=1
--filter_multiplier=4
--workers=8

i did not try running on multi-gpu atm, i ran on a single GPU.

thanks so much for spending the time to have a look at this!

**Comment by iariav** [comment]
update - 
while preparing the fork in the previous massage i also merged some changes made in the original repository (https://github.com/NoamRosenberg/AutoML). apparently, these changes somehow solved the issue and i can now run (after my own changes as well) in all opt_level.

note that it now runs on both the pytorch version built from source (with the PR changes) and on a pytorch version installed via pip (version 1.1, without PR changes).

it might be interesting to see what changes exactly were made to the architecture that solved this issue..

closing since my issue is solved for now
thanks for all the help.

**Comment by ptrblck** [comment]
That's good to hear @iariav! Please reopen, if you encounter this issue again.
