### ISSUE TITLE
How can I train with multi-GPU?

### ISSUE THREAD

**Issue by tzm1003306213** [NVIDIA/apex#443]
I run the example codes, but it only use one gpu.

**Comment by ptrblck** [comment]
Hi @tzm1003306213,

could you post the command you are using to run the script?
What does `nvidia-smi` show while the script is being executed?

**Comment by tzm1003306213** [comment]
Hi @ptrblck,

The script I was running: https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py

I run the script with default parameters.

nvidia-smi:
|   0  TITAN Xp            Off  | 00000000:19:00.0 Off |                  N/A |
| 55%   84C    P2   231W / 250W |  11747MiB / 12196MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:1A:00.0 Off |                  N/A |
| 23%   41C    P8     9W / 250W |     10MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN Xp            Off  | 00000000:67:00.0 Off |                  N/A |
| 23%   36C    P8     8W / 250W |     10MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN Xp            Off  | 00000000:68:00.0 Off |                  N/A |
| 23%   37C    P8    16W / 250W |     10MiB / 12192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     21933      C   python                                     11735MiB |
+-----------------------------------------------------------------------------+

> Hi @tzm1003306213,
> 
> could you post the command you are using to run the script?
> What does `nvidia-smi` show while the script is being executed?

**Comment by ptrblck** [comment]
The example is using DALI, so pinging @klecki.

**Comment by klecki** [comment]
Hi, 
you can read more on how to use this example in DALI docs: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/pytorch/resnet50/pytorch-resnet50.html

You should be using this command to start it (`torch.distributed.launch` for distributed training):
```
python -m torch.distributed.launch --nproc_per_node=NUM_GPUS main.py -a resnet50 --dali_cpu --fp16 --b 128 --static-loss-scale 128.0 --workers 4 --lr=0.4 ./
```

where `NUM_GPUS` specifies the number of GPUs you want to use in your training.

**Comment by tzm1003306213** [comment]
Thanks for the help!
