### ISSUE TITLE
PyTorch warnings: Tensor.data<T>() is deprecated.

### ISSUE THREAD

**Issue by tomrunia** [NVIDIA/apex#456]
After building both PyTorch and Apex from their master branches, my training script throws PyTorch C++ warnings at every training step. All warnings disappear when disabling Apex during training. Installing the official release of PyTorch 1.2 also seems to work without warnings.

```
/usr/local/lib/python3.5/dist-packages/torch/include/ATen/core/Tensor.h:297: UserWarning: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
  TORCH_WARN("Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.");
```

**PyTorch from master:** `f622ec8084c1778c6943474796efa52e9b9cf695`
**Apex from master:** `78c38db467c378759b4278a4ca8547763da5c91d`
**CUDA Toolkit:** 10.1
**CuDNN:** 7.1

**Comment by mcarilli** [comment]
This looks annoying, I'll try to repro and fix.

In general we've learned it's annoying to ask users to install a repo separate from Pytorch, especially one that relies on extension builds.  I've been focused on getting Amp upstream, to avoid all this in the future. https://github.com/pytorch/pytorch/issues/25081.

**Comment by mcarilli** [comment]
Should be fixed now, please reopen if it still shows deprecation warnings at either compile time or runtime.
