### ISSUE TITLE
FusedNovoGrad crashing after resume

### ISSUE THREAD

**Issue by rwightman** [NVIDIA/apex#458]
I'm having trouble resuming training w/ FusedNovoGrad optimizer when resuming from a checkpoint. I've tested resume with FusedSGD and FusedAdam in my comparisons and they have no problems.

The training is being done on 2 GPUs with apex DDP. Running w/ AMP mixed precision in O1. 

I'm currently trying w/ DDP and no AMP to see if it's mixed-prec specific. The error dump is off my scroll buffer right now so I'll cut and paste later.

The crash happens on first training steps after the resume. I was originally loading optimizer state dict and model state dict before applying AMP. After seeing the new checkpointing code and recomendations all state_dict, including the new AMP state_dict are now loaded after amp.initialize.

Apex being used is master as of today, installed in a fresh conda env with Pytorch 1.2.

**Comment by mcarilli** [comment]
@FDecaYed have you observed this?

**Comment by rwightman** [comment]
The crash is the same without AMP enabled (both initial train and resume done without amp)

```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272271120/work/torch/csrc/cuda/Module.cpp line=159 error=77 : an illegal memory access was encountered
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272271120/work/torch/csrc/cuda/Module.cpp line=159 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 354, in main
    use_amp=use_amp, model_ema=model_ema)
  File "train.py", line 427, in train_epoch
    torch.cuda.synchronize()
  File "/home/blah/.conda/envs/pytorch-12/lib/python3.7/site-packages/torch/cuda/__init__.py", line 381, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1565272271120/work/torch/csrc/cuda/Module.cpp:159
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 354, in main
    use_amp=use_amp, model_ema=model_ema)
  File "train.py", line 427, in train_epoch
    torch.cuda.synchronize()
  File "/home/blah/.conda/envs/pytorch-12/lib/python3.7/site-packages/torch/cuda/__init__.py", line 381, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1565272271120/work/torch/csrc/cuda/Module.cpp:159
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1565272271120/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /opt/conda/conda-bld/pytorch_1565272271120/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error
Traceback (most recent call last):
  File "/home/blah/.conda/envs/pytorch-12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/blah/.conda/envs/pytorch-12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/blah/.conda/envs/pytorch-12/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/blah/.conda/envs/pytorch-12/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
```

**Comment by FDecaYed** [comment]
I figured it out. 
`exp_avg_sq` is stored in `param_groups` rather than `state`. and torch.optim by default only move tensors in `state` to correct device. In this case with DDP, every worker will load `exp_avg_sq` onto same device rather than their own.
It can be fixed in 2 ways:
- overwrite load_state_dict() to move them properly
- store them as a list of scalar tensor, rather than single tensor, in state

@mcarilli thought?

**Comment by mcarilli** [comment]
I agree the first fix seems fine.

However, in general, it's always good practice to have every process use `map_location` when calling `torch.load` to ensure that each process deserializes saved tensors onto its own device (see https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py#L179).  Subsequent `load_state_dict` calls (be they model, optimizer, or whatever) should then only ever see tensors on this process's device, and you may find that the novograd issue goes away.

In fact, without `map_location`, _every_ process that loads from a checkpoint will initially deserialize tensors onto whatever device they were saved from.  This could result in, say, processes 1-7 all creating a spurious cuda context on device 0, which can impact memory and performance.  I would argue that `map_location` is the right answer here, and changing Novograd itself is just a failsafe.

**Comment by FDecaYed** [comment]
Merge or reject as you wish
https://github.com/NVIDIA/apex/pull/459

**Comment by rwightman** [comment]
> In fact, without `map_location`, _every_ process that loads from a checkpoint will initially deserialize tensors onto whatever device they were saved from. This could result in, say, processes 1-7 all creating a spurious cuda context on device 0, which can impact memory and performance. I would argue that
> 
> ```
> checkpoint = torch.load(args.resume, map_location = lambda storage, loc: storage.cuda(args.gpu))
> ```

I do map the location to avoid surprises on resume/load, but I've been remapping to CPU, making sure the model is on the correct device, and assuming load_state_dict for model, optimizer, etc would take care of the rest based on the device the model params are currently on. This has allowed a reasonable amount of flexibility in changing when restoring and possibly changing the specifics of devices, etc. It has worked without any noticible issues up until this specific case. 

Curious if you're aware of specific situations where that approach could break?

**Comment by rwightman** [comment]
I see the workaround is merged, tx! That machine is currently busy for another day or so, will try it sometime this weekend.

**Comment by rwightman** [comment]
Seems to be fine now.
