### ISSUE TITLE
Clueless halt while GPU is still running!

### ISSUE THREAD

**Issue by donnyyou** [NVIDIA/apex#463]
While I use the distributed training, the training process encounters clueless halt. The GPU-Memory and GPU-Util (90%-100%) of all GPUs are normal with no pid being killed!!!

**Comment by donnyyou** [comment]
I have tried three times. They all magically halt at 94300 iterations,

**Comment by ptrblck** [comment]
Is this issue `apex` specific or are you seeing it with DDP in Pytorch?
In the latter case, let's continue the discussion in the forum: https://discuss.pytorch.org/t/clueless-halt-while-gpu-is-still-running/54947

**Comment by jessemelpolio** [comment]
Met the same problem.

**Comment by ptrblck** [comment]
@jessemelpolio Could you provide an executable code snippet, it this issue is `apex` related?
If not, I would suggest to continue the discussion in the linked thread or open an issue in PyTorch (and link it here), please.

**Comment by jessemelpolio** [comment]
I am not quite sure where the problem is, but I think it could be more related to PyTorch. Surely we could move there to further discussions.

**Comment by donnyyou** [comment]
https://github.com/donnyyou/torchcv/blob/561ef4e662fff1b9b47060bb08842408a205e689/runner/tools/runner_helper.py#L31
https://github.com/donnyyou/torchcv/blob/561ef4e662fff1b9b47060bb08842408a205e689/runner/seg/fcn_segmentor.py#L72

**Comment by donnyyou** [comment]
![image](https://user-images.githubusercontent.com/23111956/64117465-da875900-cdc7-11e9-8254-69f90b2feb35.png)
![image](https://user-images.githubusercontent.com/23111956/64117525-f854be00-cdc7-11e9-8d40-33fb76213fb1.png)
clueless halt at the same iteration without any pid being killed! No error occurred and all gpus are still running as showed below.
![image](https://user-images.githubusercontent.com/23111956/64117806-b9733800-cdc8-11e9-9fe1-18b6e4d5c19b.png)

**Comment by ptrblck** [comment]
@donnyyou Do you see this issue also with [`torch.nn.parallel.DistributedDataParallel`](https://pytorch.org/docs/stable/nn.html?highlight=distributeddataparallel#torch.nn.parallel.DistributedDataParallel)?

**Comment by donnyyou** [comment]
I will try any possible combination to localize the problem. And update it soon!

**Comment by donnyyou** [comment]
When I disable SyncBN, it works well! Is there any bugs with SyncBN? @ptrblck
![image](https://user-images.githubusercontent.com/23111956/64250572-1138ad00-cf49-11e9-8879-327f65bf4bd2.png)

**Comment by donnyyou** [comment]
Same as this issue: https://github.com/NVIDIA/apex/issues/105, and the latest version of apex hasn't resolved it. @ptrblck
