### ISSUE TITLE
Keep certain modules as FP32

### ISSUE THREAD

**Issue by yaysummeriscoming** [NVIDIA/apex#464]
I'm currently using the old fp16_optimizer API & looking to migrate to the new AMP API.  One requirement of mine is the ability to keep certain modules as float.  Unfortunately when I look at the migration guide, I see this feature has been under construction for a while:

https://nvidia.github.io/apex/advanced.html#forcing-particular-layers-functions-to-a-desired-type

Is there a workaround available?

**Comment by ptrblck** [comment]
Hi @yaysummeriscoming,
would [function annotations](https://github.com/NVIDIA/apex/tree/master/apex/amp#function-annotation) work for your use case?

**Comment by yaysummeriscoming** [comment]
Thanks, that looks to be it.  Is it possible to update the documentation?
