### ISSUE TITLE
 File "setup.py", line 5, in <module>     from pip._internal import main as pipmain ImportError: No module named 'pip._internal'

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/apex#472]
```
 File "setup.py", line 5, in <module>
    from pip._internal import main as pipmain
ImportError: No module named 'pip._internal'

```

**Comment by ptrblck** [comment]
Could you try to update `pip` as described [here](https://stackoverflow.com/questions/49940813/pip-no-module-named-internal)?

**Comment by jinfagang** [comment]
I don't know why, after uninstall python3-pip, it has no problem now.

**Comment by jinfagang** [comment]
My bad, today I got this issue too on another computer..... I don't why only happens on apex. But uninstall python3-pip does not help (well, sometimes .... ).

The solution is using easy_install to install pip from scratch.

And the root reason for this is may because pip installed from apt too old....
