### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._internal'

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/apex#479]
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from pip._internal import main as pipmain
ModuleNotFoundError: No module named 'pip._internal'

**Comment by ptrblck** [comment]
Double post: https://github.com/NVIDIA/apex/issues/472#issuecomment-527920072

Could you try to apply the last solution (or update `pip`)?
