### ISSUE TITLE
atex/amex?

### ISSUE THREAD

**Issue by eric-haibin-lin** [NVIDIA/apex#50]
Will there be an Tensorflow/MXNet extension of all these awesome work?

**Comment by mcarilli** [comment]
I've heard my colleagues who work on Tensorflow mentioning they had a mixed precision optimizer.  I'm not sure about MXNet.  I'll ask around on Monday.

**Comment by eric-haibin-lin** [comment]
Any update?

**Comment by cliffwoolley** [comment]
Thanks for you feedback and request!  We don't have any announcements to make at this time, however.

Best,
Cliff
