### ISSUE TITLE
It is correct at fp16_optimizer.py and fused_adam.py

### ISSUE THREAD

**Issue by hibiki12y** [NVIDIA/apex#509]
Hello, I've read fp16 from this poster(https://devblogs.nvidia.com/apex-pytorch-easy-mixed-precision-training/) and try it. but i'v get always runtime error : 'FusedAdam has been updated.  Simply initialize it identically to torch.optim.Adam, and call step() with no arguments.'
and I've check optimizer both optimizer code fp16_optimizer.py and fused_adam.py.
In fp16_optimizer.py, 

`        
self.optimizer.step(grads=[[g] for g in grads_groups_flat],
                            output_params=[[p] for p in self.fp16_groups_flat],
                            scale=self.cur_scale,
                            grad_norms=norm_groups)
`

send some parametert to fused adam but, in fused_adam.py

`
        if any(p is not None for p in [grads, output_params, scale, grad_norms]):
            raise RuntimeError('FusedAdam has been updated.  Simply initialize it identically to torch.optim.Adam, and call step() with no arguments.')
`

all parameter must be None.

fp16 optimizer can not use adam?

**Comment by mcarilli** [comment]
That post is almost a year out of date.  FP16_Optimizer should no longer be used in scripts, nor is it used internally by Amp.  In general, the best guidance is to follow the API documentation:
https://nvidia.github.io/apex/amp.html
For FusedAdam in particular, see:
https://nvidia.github.io/apex/optimizers.html#apex.optimizers.FusedAdam
