### ISSUE TITLE
apex installation error

### ISSUE THREAD

**Issue by DangerousY** [NVIDIA/apex#512]
I meet with this error，what i need to do to solve this problem.
ERROR: Command errored out with exit status 1: /home/zyx/anaconda3/envs/HRNet/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h8mo4ntf/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h8mo4ntf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-q1yr4coq/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

And then there are many sentence like this
....
....
Found link https://files.pythonhosted.org/packages/00/9e/4c83a0950d8bdec0b4ca72afd2f9cea92d08eb7c1a768363f2ea458d08b4/pip-19.2.3.tar.gz#sha256=e7a31f147974362e6c82d84b91c7f2bdf57e4d3163d3d454e6c3e71944d67135 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 19.2.3
Given no hashes to check 127 links for project 'pip': discarding no candidates

**Comment by NealHappy** [comment]
I meet the same error, may you introduce how did you solve this problem? Many thanks!

**Comment by DNGros** [comment]
Also had this issue (looks like this this issue is a dup of #498). I posted my fix of a least one version of the error there. https://github.com/NVIDIA/apex/issues/498#issuecomment-538644739 . The tl;dr is make sure you have install of cuda with nvcc on your path.
