### ISSUE TITLE
RuntimeError: storage has wrong size

### ISSUE THREAD

**Issue by sofzh** [NVIDIA/apex#515]
hey, guys, when using apex with pytorch 1.0, I trained model successfully in multiple GPUs( titanX ), but error occurs when I load the best model I saved in training process. 

I find that , some model could be loaded successfully while some others could not.
In the code , I use " apex.parallel.convert_syncbn_model and apex.parallel.DistributedDataParallel( DDP ) " to use multiple GPUs

The error is :
RuntimeError: storage has wrong size: expected -4721614612255084527 got 1

I think it means that  the model I save before is not right. But how to solve it? and any suggestions are welcomed!

Thank u very much!

**Comment by ptrblck** [comment]
Hi @sofzh,

this error is usually thrown, if multiple processes write to the same checkpoint file (and thus might not be directly related to `apex`).
If you are using DDP, you should make sure that only one rank creates the checkpoint file.
Have a look at the [`ImageNet example` from PyTorch](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L252).

**Comment by sofzh** [comment]
> Hi @sofzh,
> 
> this error is usually thrown, if multiple processes write to the same checkpoint file (and thus might not be directly related to `apex`).
> If you are using DDP, you should make sure that only one rank creates the checkpoint file.
> Have a look at the [`ImageNet example` from PyTorch](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L252).

thx~
