### ISSUE TITLE
Error checking compiler version for cl.exe

### ISSUE THREAD

**Issue by fiyero** [NVIDIA/apex#521]
H:\Anaconda3\envs\main\lib\site-packages\torch\utils\cpp_extension.py:189: UserWarning: Error checking compiler version for cl: [WinError 2] 系統找不到指定的檔案。

Sorry this is likely not related to apex but pytorch and visual studio c++ compiler.
I have searched a lot of time but failed to get a solution.
I think someone who tried to install apex may have the same problem, hope someone can share how to fix it.

I have already install VS 2017 and 2019, and select the related C++ library.
Pytorch 1.2.0
cuda 9.2

Thanks so much

**Comment by ptrblck** [comment]
Hi @fiyero,

are you able to successfully build extensions as suggested in [this post](https://github.com/NVIDIA/apex/issues/253#issuecomment-481307196)?

**Comment by fiyero** [comment]
> Hi @fiyero,
> 
> are you able to successfully build extensions as suggested in [this post](https://github.com/NVIDIA/apex/issues/253#issuecomment-481307196)?

I follow the methods but got error 
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

has been googled for a whole day still cant figure out the solution...

**Comment by fiyero** [comment]
well......wanna cry
can explain but after downgrading to python 3.6 + VS studio 2017 work for me

**Comment by biteyou** [comment]
I accounted the similary erro when under windows10 , running " python setup.py build" in command line , I append "path" variable the path of my "cl.exe" according to https://blog.csdn.net/discoverer100/article/details/101626615
then another erro raised, furtunately, the new erro was just an endoing erro (中文编码GBK和UTF-8)，referring this easy fixed them. https://blog.csdn.net/tanmx219/article/details/100829920?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task

**Comment by blind-bird** [comment]
Add the environment variables of vs and restart the client. I didn’t restart so I kept reporting errors

**Comment by spiceedge** [comment]
For anyone having this error, you have to download VS Build Tools (=The Visual Studio installer) and make sure to download the MSVC >v14.x c++ build tools (preferably 'latest'). _**Make sure to find the correct path of your cl.exe**_. You may believe you have the right path, but be wrong (happened to me like 4x). 
Delete any other MSVC installations you may have, to make sure you find the right one that you just downloaded - If you need them again, you can keep them noted down to reinstall after finding the cl.exe of this installation.
Then add the full path of the cl.exe file to Path in the System's Environment variables.
Restart VSCode or VStudio and test your project again.
If it works, you may reinstall any MSVC installations you had. _**If the fix doesn't work**_, I have to say that - as long as the error message is what is provided above - you are likely _mistaken_. This fix _**does**_ work. If it doesn't for you, you have done something wrong. Check the cl.exe location and **system** path env var again.
