### ISSUE TITLE
Fail to install apex

### ISSUE THREAD

**Issue by Bigwode** [NVIDIA/apex#526]
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-x_zo1ieu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-x_zo1ieu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open
)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-03t77ab4/install-record.txt --single-version-externally-managed --compile Check the logs
 for full command output.

**Comment by 421psh** [comment]
same problem

**Comment by BramVanroy** [comment]
You didn't provide the full error trace so it's hard to debug. It might be a simple small version mismatch in which case you can comment out the version check in setup.py.
