### ISSUE TITLE
"torch.distributed.launch" vs "torch.multiprocessing.spawn"

### ISSUE THREAD

**Issue by vgoklani** [NVIDIA/apex#549]
Hey there, I just wanted to confirm that launching a distributed training job via:

    python -m torch.distributed.launch --nproc_per_node=NUM_GPUS main_amp.py args...

is in-fact equivalent to using this directly in the training code:

    torch.multiprocessing.spawn(train_function, nprocs=args.number_gpus, args=(args,))

when using apex.parallel.DistributedDataParallel

Thanks!

**Comment by BramVanroy** [comment]
What about the (environment) variables? They're probably the most important thing about the launch utility. Getting the world size and local rank. On top of that, the launch utility works on top of existing scripts which makes it useful in the sense that the scripts need minimal changes, and still work as before in single-process mode. I rather use the utility than meddling in my own code too much.

**Comment by vgoklani** [comment]
I just use this:

    parser.add_argument('--nodes', default=1, type=int, metavar='N', help='')
    parser.add_argument('--number-gpus', default=2, type=int, help='number of gpus per node')
    parser.add_argument('--gpu-rank', default=0, type=int, help='ranking within the nodes')
    parser.add_argument('--inference-checkpoint', type=str, help='inference checkpoint')
    args = parser.parse_args()

    args.world_size = args.number_gpus * args.nodes

and then of course put this in my train_function:

    if args.number_gpus > 1:
        rank = args.gpu_rank * args.number_gpus + gpu
        torch.distributed.init_process_group(
            backend='nccl',
            init_method='env://',
            world_size=args.world_size,
            rank=rank)

But I just want to confirm that apex DDP is able to launch separate processes per GPU when using 

    torch.multiprocessing.spawn(train_function, nprocs=args.number_gpus, args=(args,))

**Comment by mcarilli** [comment]
Apex DDP doesn't "launch" anything, it just attaches allreduce hooks to the parameters.  If `init_process_group` followed by `model=DDP(model)` occur within train_function (in other words, within the subprocesses created by the spawn) then the allreduces should work the same way they do when using the launcher wrapper.

That being said, I highly recommend using the native `torch.nn.parallel.DistributedDataParallel.` Apex DDP had advantages over `torch.nn.parallel.DistributedDataParallel` in the past, but these days, `torch.nn.parallel.DistributedDataParallel` is excellent.  Apex DDP exists mostly to support some internal use cases that require outlandish features.  Apex DDP and torch DDP are [drop-in replacements for each other aside from some constructor arguments](https://github.com/NVIDIA/apex/blob/master/examples/simple/distributed/distributed_data_parallel.py#L48-L52).

**Comment by EricKani** [comment]
> I just use this:
> 
> ```
> parser.add_argument('--nodes', default=1, type=int, metavar='N', help='')
> parser.add_argument('--number-gpus', default=2, type=int, help='number of gpus per node')
> parser.add_argument('--gpu-rank', default=0, type=int, help='ranking within the nodes')
> args = parser.parse_args()
> 
> args.world_size = args.number_gpus * args.nodes
> ```
> 
> and
> 
> ```
> os.environ['MASTER_ADDR'] = '127.0.0.1'
> os.environ['MASTER_PORT'] = '29500'
> ```
> 
> and then of course put this in my train_function (which accepts both "gpu" and "args"):
> 
> ```
> if args.number_gpus > 1:
>     rank = args.gpu_rank * args.number_gpus + gpu
>     torch.distributed.init_process_group(
>         backend='nccl',
>         init_method='env://',
>         world_size=args.world_size,
>         rank=rank)
> ```
> 
> But I just want to confirm that apex DDP is able to launch separate processes per GPU when using
> 
> ```
> torch.multiprocessing.spawn(train_function, nprocs=args.number_gpus, args=(args,))
> ```
> 
> When I use the above, both my GPUs are training at 100% utilization, but it's not clear to me whether the setup is correct and they are in fact doing the all-reduce correctly. I need to validate each of the individual steps. But I do see two CPU threads running at 100%.

Hi~

What will happen if we only set "init_method"( init_method='env://',) but do not set "world_size" explicitly. 
I thought there are two ways to init "init_process_group" function, either setting ("init_method", ) or ("world_size", "rank",). 

Thanks.
