### ISSUE TITLE
TypeError: Class advice impossible in Python3. 

### ISSUE THREAD

**Issue by antgr** [NVIDIA/apex#551]
I installed apex with pip3 install apex --user
but now trying to run the code of this repo: https://github.com/namisan/mt-dnn
I have problem with apex:
python3 train.py --data-dir ner/ --init_checkpoint mt_dnn_models/bert_model_base_uncased.pt -train_dataset ner --test_dataset ner --task_def experiments/ner/ner_task_def.yml
Traceback (most recent call last):
File "train.py", line 10, in
from pytorch_pretrained_bert.modeling import BertConfig
File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/init.py", line 7, in
from .modeling import (BertConfig, BertModel, BertForPreTraining,
File "/home/user/.local/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling.py", line 218, in
from apex.normalization.fused_layer_norm import FusedLayerNorm as BertLayerNorm
File "/home/user/.local/lib/python3.7/site-packages/apex/init.py", line 18, in
from apex.interfaces import (ApexImplementation,
File "/home/user/.local/lib/python3.7/site-packages/apex/interfaces.py", line 10, in
class ApexImplementation(object):
File "/home/user/.local/lib/python3.7/site-packages/apex/interfaces.py", line 14, in ApexImplementation
implements(IApex)
File "/usr/lib64/python3.7/site-packages/zope/interface/declarations.py", line 483, in implements
raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3. Use the @Implementer class decorator instead.

I have the following version of APEX
pip3 show apex
Name: apex
Version: 0.9.10.dev0
and
 NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1  

Could you assist? Trying to install the latest version of apex I have problem with the installation

**Comment by venergiac** [comment]
same error

```
pip3 show apex
Name: apex
Version: 0.9.10.dev0
Summary: Pyramid toolkit to add Velruse, Flash Messages,CSRF, ReCaptcha and Sessions
Home-page: http://thesoftwarestudio.com/apex/
Author: Chris Davies
Author-email: user@domain.com
License: MIT
Location: /usr/local/lib/python3.6/dist-packages
Requires: pyramid-mailer, cryptacular, velruse, requests, wtforms, wtforms-recaptcha, zope.sqlalchemy, pyramid
Required-by:


```

on 
`nvcr.io/nvidia/tensorflow:20.03-tf2-py3`

how to replicate 
```
pip install apex
from apex import amp
```

**Comment by venergiac** [comment]
you installed a wrong package

to solve the issue

pip uninstall apex
pip install torch
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

**Comment by antgr** [comment]
Thanks lets close it. I do not remember this case anymore. I think that I didn't install it because in that specific gpu, the apex would not do anything extra as I had been informed .
