### ISSUE TITLE
window10 pytorch1.2 error C3203: “templated_iterator”:

### ISSUE THREAD

**Issue by zgq91** [NVIDIA/apex#560]
Hi:
   my system environment is window10 64bit  vs2015 pytorch1.2 cuda10.0;The following error occurs when executing a “python setup.py install --cuda_ext --cpp_ext” command：
d:/Anaconda3/lib/site-packages/torch/include\c10/util/flat_hash_map.h(1379): error C3203: “templated_iterator”:A specialized class template cannot be used as a template variable, which belongs to the template parameter "_Ty1" and should be of type real

**Comment by shazhongcheng** [comment]
i also meet it. so sad……
How to deal with it？
