### ISSUE TITLE
I meet  a  confused  thing  here ,  amp.intialize  can't  convert  all  the nn.Module  to  half

### ISSUE THREAD

**Issue by heartInsert** [NVIDIA/apex#569]
First ,  I  initialize  ` model_A  `  inside   `model_B  `,   and  call  `model_A  `in  `model_B.forward()  `

Then  I  call the ` model_B, optimizer = amp.initialize(model_B , optimizer, opt_level=O2)`,

If  I  run   ` output=model_B(data)` ,   my  computer  will  give  me  a    error  `Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same`

Did  someone  encounter  the  same thing with  me ?

**Comment by Stonesjtu** [comment]
You should check if your data object has a `to` method.

**Comment by heartInsert** [comment]
It's  very  intersting  that  ,  `opt_level=O1 ` and ` opt_level=O2`  seems  implemented   in    different  way ,  and    `opt_level=O1 `  will  involve  outside  tensor  ,  and   `opt_level=O2 `  will  not  involve  outside  tensor . Due  to  this  issue    https://github.com/NVIDIA/apex/issues/501  .

So  I decied  to  change  the   `opt_level=O2`   to ` opt_level=O1`  ,  it  worked  .
I  hope  this   could  help  others  who  meet  the  same thing   with  me  , but   if  the  official   could  tips   this  in  README.md ,  it  would  be better.

**Comment by heartInsert** [comment]
> You should check if your data object has a `to` method.

just   data.cuda()
