### ISSUE TITLE
Error when amp_handle.amp.init() 

### ISSUE THREAD

**Issue by LightToYang** [NVIDIA/apex#57]
I used the following code 
```
import torch
from apex import amp
amp_handle = amp.init()
```
 and "Floating point exception (core dumped)" occured

**Comment by mcarilli** [comment]
Are you using one of the upstream containers?  CUDNN 7.1.4 is known to cause this issue, and it's possible you're using a container that has 7.1.4 installed.

**Comment by LightToYang** [comment]
My environment is CUDA 9.2, CUDNN 7.3.2, and my gpu is 2080ti with Turing architeture. And I  tried it in nvcr.io/nvidia/pytorch:18.09-py3 whose environment is CUDA 9.2, CUDNN 7.3.2, and it works fine. Will the reason be that the CUDA 9.2 does not support Turing architeture?
