### ISSUE TITLE
Installation issue: "module error no callable..."

### ISSUE THREAD

**Issue by MrHuff** [NVIDIA/apex#588]
Hi!

Thank you for a great library, it's my favorite one for GPU training! Specs:

1. Pytorch 1.3
2. cuda 10.1
3. Python 3.7.5
4. GCC 7.1.0

I get an installation error:

/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py:283: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-gffnau1r
Created temporary directory: /tmp/pip-req-tracker-o692a44_
Created requirements tracker '/tmp/pip-req-tracker-o692a44_'
Created temporary directory: /tmp/pip-install-xa81sz3r
Processing /homes/rhu/phd_projects/apex
  Created temporary directory: /tmp/pip-req-build-sk3j71ng
  Added file:///homes/rhu/phd_projects/apex to build tracker '/tmp/pip-req-tracker-o692a44_'
    Running setup.py (path:/tmp/pip-req-build-sk3j71ng/setup.py) egg_info for package from file:///homes/rhu/phd_projects/apex
    Running command python setup.py egg_info
    torch.__version__  =  1.3.0
    running egg_info
    creating /tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info
    writing /tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info/top_level.txt
    writing manifest file '/tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-req-build-sk3j71ng/pip-egg-info/apex.egg-info/SOURCES.txt'
    /tmp/pip-req-build-sk3j71ng/setup.py:43: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
  Source in /tmp/pip-req-build-sk3j71ng has version 0.1, which satisfies requirement apex==0.1 from file:///homes/rhu/phd_projects/apex
  Removed apex==0.1 from file:///homes/rhu/phd_projects/apex from build tracker '/tmp/pip-req-tracker-o692a44_'
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
  Created temporary directory: /tmp/pip-record-8xydoycg
    Running command /homes/rhu/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-sk3j71ng/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-sk3j71ng/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --pyprof --cpp_ext --cuda_ext install --record /tmp/pip-record-8xydoycg/install-record.txt --single-version-externally-managed --compile
    torch.__version__  =  1.3.0
    **Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-sk3j71ng/setup.py", line 37, in <module>
        pipmain(["install"] + required_packages)
    TypeError: 'module' object is not callable
    Running setup.py install for apex ... error**
Cleaning up...
  Removing source in /tmp/pip-req-build-sk3j71ng
Removed build tracker '/tmp/pip-req-tracker-o692a44_'
ERROR: Command errored out with exit status 1: /homes/rhu/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-sk3j71ng/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-sk3j71ng/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --pyprof --cpp_ext --cuda_ext install --record /tmp/pip-record-8xydoycg/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 888, in install
    cwd=self.unpacked_source_directory,
  File "/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/homes/rhu/miniconda3/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /homes/rhu/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-sk3j71ng/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-sk3j71ng/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --pyprof --cpp_ext --cuda_ext install --record /tmp/pip-record-8xydoycg/install-record.txt --single-version-externally-managed --compile Check the logs for full command output

I don't really know how to fix the 

  **Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-sk3j71ng/setup.py", line 37, in <module>
        pipmain(["install"] + required_packages)
    TypeError: 'module' object is not callable
    Running setup.py install for apex ... error**

I would appreciate any help!

Thank you!

Best regards,
Robert

**Comment by panaali** [comment]
I have the same problem. Thanks

**Comment by mcarilli** [comment]
I think this is an artifact of how the Pyprof install interacts with the latest versions of pip.  We're still deciding the best way to solve this.  In the meantime, if you don't want to use Pyprof, omit the --pyprof argument from the options which should unblock you.  Pyprof is not necessary to use the core features of Apex (automatic mixed precision and fused optimizers).

**Comment by MrHuff** [comment]
Hi everyone!

Thank you for the prompt reply @mcarilli. To clarify I used the regular command:

`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
`
when installing. I inferred that the pip version was the issue per your post, and consequently tried downgrading pip to version 18.0 and now its installing properly. 

Thank you!

Best regards,
Robert
