### ISSUE TITLE
Out of memory when saving the state_dict()

### ISSUE THREAD

**Issue by benywon** [NVIDIA/apex#589]
My code looks like:
...
model = model.cuda()
model, optimizer = amp.initialize(model,
                                  optimizer,
                                  opt_level="O2",
                                  keep_batchnorm_fp32=False,
                                  loss_scale='dynamic',
                                  verbosity=0)
model = apex.parallel.DistributedDataParallel(model)
...
state_dict=model.module.state_dict()
torch.save(state_dict, f)
the codes run during training ,but when i tried to save the state dict, OOM problem is occurred during I call state_dict=model.module.state_dict(). It occurs the out of memory error! Can anyone help me?

**Comment by benywon** [comment]
The error is :
File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 695, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 695, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 2 more times]
  File "/usr/local/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 697, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/usr/local/python3/lib/python3.6/site-packages/apex/amp/_initialize.py", line 141, in __call__
    param = param.to(torch.float32)
RuntimeError: CUDA out of memory.

**Comment by mcarilli** [comment]
Try using O1 instead of O2.  You should always prefer O1.  O2 is a relic from our initial experiments with mixed precision that (we discovered) is much more prone to failures.  The upstream integration will be exclusively O1-like under the hood (https://github.com/pytorch/pytorch/issues/25081).  Please reopen if O1 doesn't work for some reason.

**Comment by benywon** [comment]
> Try using O1 instead of O2. You should always prefer O1. O2 is a relic from our initial experiments with mixed precision that (we discovered) is much more prone to failures. The upstream integration will be exclusively O1-like under the hood ([pytorch/pytorch#25081](https://github.com/pytorch/pytorch/issues/25081)). Please reopen if O1 doesn't work for some reason.

Thanks!!!!The problem has been solved!!!
