### ISSUE TITLE
Training freezes at DDP(model, delay_allreduce=True) part

### ISSUE THREAD

**Issue by Riveryoon** [NVIDIA/apex#591]
Actually I solved the issue.
It was due to my environment

**Comment by mcarilli** [comment]
Glad you solved it, but at the moment, I recommend using native DDP (torch.nn.parallel.DistributedDataParallel) over apex DDP.  Apex DDP survives to support internal use cases.  Torch native DDP is a drop in replacement aside from some constructor arguments, see https://github.com/NVIDIA/apex/blob/master/examples/simple/distributed/distributed_data_parallel.py#L48-L52.
