### ISSUE TITLE
Memory increase migrating from F16_optimizer to AMP

### ISSUE THREAD

**Issue by SeanNaren** [NVIDIA/apex#600]
Hey guys!

We've noted a memory increase when moving from f16_optimizer to AMP as suggested by the warning messages which leads us to OOM issues on the GPU when running our audio training. 

The implementation is similar to whats found in the train.py [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/train.py) however we've opted to use FusedAdam. FusedAdam + F16_optimizer works for our training parameters, however using AMP with O1 or O2 leads to a memory crash further in training. Any ideas as to why and how to solve this?

**Comment by mcarilli** [comment]
The old FP16_Optimizer created flattened master parameters, which was a minor performance/memory optimization at the cost of flexibility (it wasn't possible to partially freeze any portion of the network between iterations, which is something the current code can handle).  The memory hit from non-flattened parameters should not be too significant.  Can you try a slightly smaller batch size?

**Comment by SeanNaren** [comment]
Thanks @mcarilli ! To test this could we manually flatten the parameters somewhere in the code?

**Comment by SeanNaren** [comment]
Hey, so we checked our code and it seems we don't flatten parameters by default in the F16_optimizer script? Could you point to where this flattening happened?
