### ISSUE TITLE
pybind11 related error when compiling apex on ubuntu 18.04

### ISSUE THREAD

**Issue by ginobilinie** [NVIDIA/apex#604]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/torch/include -I/usr/lib/python3/dist-packages/torch/include/torch/csrc/api/include -I/usr/lib/python3/dist-packages/torch/include/TH -I/usr/lib/python3/dist-packages/torch/include/THC -I/usr/include/python3.6m -c csrc/flatten_unflatten.cpp -o build/temp.linux-x86_64-3.6/csrc/flatten_unflatten.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=apex_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    csrc/flatten_unflatten.cpp:15:16: error: expected constructor, destructor, or type conversion before ‘(’ token
     PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
                    ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-1vgnzs21
Removed build tracker '/tmp/pip-req-tracker-ulfz4dqv'
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1vgnzs21/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1vgnzs21/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-1kui2of3/install-record.txt --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.

environment
pytorch 1.2
cuda 10.0

I have tried:
sudo apt-get install python3-pybind11

sadly, it doesnot work for me.

**Comment by ginobilinie** [comment]
Any suggestions?

**Comment by mcarilli** [comment]
This doesn't seem related to Apex.  Can you compile pytorch extensions on your system?  If you have the pytorch repo directory downloaded, try going to `pytorch/test/cpp_extensions` and run `python setup.py install` there.  Otherwise, you can try a Python-only install of Apex, via `pip install -v --no-cache-dir ./`.

**Comment by ginobilinie** [comment]
Thanks, i'll try your method. I think the issue is from pybind11.

**Comment by ptrblck** [comment]
Closing this issue.
@ginobilinie Please reopen, if you think `apex` is creating this error.
