### ISSUE TITLE
some problems with "!python setup.py install --cuda_ext --cpp_ext"!!!!!

### ISSUE THREAD

**Issue by ssguaishou** [NVIDIA/apex#607]
`torch.__version__  =  1.3.1+cu100
/content/apex/setup.py:43: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
  warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
from /usr/local/cuda/bin

running install
running bdist_egg
running egg_info
creating apex.egg-info
writing apex.egg-info/PKG-INFO
writing dependency_links to apex.egg-info/dependency_links.txt
writing top-level names to apex.egg-info/top_level.txt
writing manifest file 'apex.egg-info/SOURCES.txt'
reading manifest file 'apex.egg-info/SOURCES.txt'
writing manifest file 'apex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'apex_C' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/csrc
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/include/python3.6m -c csrc/flatten_unflatten.cpp -o build/temp.linux-x86_64-3.6/csrc/flatten_unflatten.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=apex_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
x86_64-linux-gnu-gcc: error: csrc/flatten_unflatten.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
what's wrong with the GCC? I can't find the flatten_uinflatten.cpp
please help me

**Comment by mcarilli** [comment]
It should be part of the repo, in csrc.  gcc is looking for csrc/flatten_unflatten.cpp, which should be correct, assuming you are running setup.py from the top level of the repo directory itself.

**Comment by ssguaishou** [comment]
> It should be part of the repo, in csrc. gcc is looking for csrc/flatten_unflatten.cpp, which should be correct, assuming you are running setup.py from the top level of the repo directory itself.

u should be right, i'll try again ,thx

**Comment by ptrblck** [comment]
Closing this issue.
@ssguaishou Please reopen, if you still have trouble installing `apex`.

**Comment by DominikFilipiak** [comment]
> It should be part of the repo, in csrc. gcc is looking for csrc/flatten_unflatten.cpp, which should be correct, assuming you are running setup.py from the top level of the repo directory itself.

It was exactly the thing in my case. 
Instead of doing
```bash
python ${PROJECT_DIR}/apex/setup.py install --cpp_ext --cuda_ext
```
had to do
```bash
cd ${PROJECT_DIR}/apex/ && python setup.py install --cpp_ext --cuda_ext
```
Thanks!
