### ISSUE TITLE
I meet a Big BUG

### ISSUE THREAD

**Issue by shoutOutYangJie** [NVIDIA/apex#629]
I use your DDP
> from apex.parallel import DistributedDataParallel as DDP

and Pytorch 
> CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 train.py 

So there is two processes running my train.py.

For saveing checkpoint, I found some checkpoings can be load for resuming, but Others can't. The error is shown as following.
> Traceback (most recent call last):
  File "aaa.py", line 5, in <module>
    checkpoint = torch.load(model_path)
  File "/home/yj/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/yj/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 620, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -9223011547364714763 got 256

and If I just use one GPU with cmd line 
> CUDA_VISIBLE_DEVICES=3 python aaa.py 

The error is shown:
> RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

I guess Both This two processes will save their checkpoints with same file name, which breaks file writing stream.  How to solve it.

**Comment by mcarilli** [comment]
I don't think this has to do with DDP.  Generally, you should save checkpoints only from rank 0, as shown here:
https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py#L247-L256
and when loading, have each process load onto the current device using map_location, as shown here:
https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py#L121-L126
https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py#L179

Please reopen if this doesn't work.

**Comment by shoutOutYangJie** [comment]
thank you, it works for me

------------------ Original ------------------
