### ISSUE TITLE
DDP prefixes state_dict with `module.*`

### ISSUE THREAD

**Issue by vfdev-5** [NVIDIA/apex#647]
Hi, it's a bug or feature, the issue is that when model is wrapped with DDP its state dict keys are prefixed with `module.` and thus saved model can not then loaded into non-wrapped original model (to perform inference without apex).

```python
from apex.parallel import DistributedDataParallel as DDP
import torch.distributed as dist
from torchvision.models.resnet import resnet18

import os 
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "2222"
dist.init_process_group("nccl", init_method="env://", world_size=1, rank=0)
model = resnet18(pretrained=False).to('cuda')
sd = model.state_dict()
print("Original keys :", list(sd.keys())[:5])
model = DDP(model, delay_allreduce=True)
sd = model.state_dict()
print("DDP keys :", list(sd.keys())[:5])
```
gives
```
Original keys : ['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var']
DDP keys : ['module.conv1.weight', 'module.bn1.weight', 'module.bn1.bias', 'module.bn1.running_mean', 'module.bn1.running_var']
```

Thanks

**Comment by mcarilli** [comment]
This is the same behavior as Pytorch's native DDP (`torch.nn.parallel.DistributedDataParallel`).  Also, I recommend using `torch.nn.parallel.DistributedDataParallel` rather than the apex version.  The apex version exists mainly to support internal use cases and the native version is more future-proof.

**Comment by vfdev-5** [comment]
Thanks for explanation @mcarilli  !
