### ISSUE TITLE
Can  I   install  this  apex  in  conda  directly  with  cudatoolkit  inside  ?

### ISSUE THREAD

**Issue by heartInsert** [NVIDIA/apex#648]
If   I   run   this   command     `conda   installl  pytorch   torchvision   cudatoolkit=10.0  `,  it  will  be  very  convenient  that  I  don't  need  to  install  cuda  and  cudnn  in  ` './home/'` again . 

But   I   don't  think  `  apex-pytorch`  could  recogize    `cuda`    in  conda  .

Did   someone  have   tested  about  it ?

**Comment by JiangTanZJU** [comment]
Have you ever find the way to use conda cudatoolkit to install apex?
I meet the same problem. I use ubuntu server in my lab, and it's system cuda version is 9.0.
However, my pytorch version should be 10.0.
If you find the way, could you tell me？

**Comment by rudvlf0413** [comment]
I think this function is very convenient too.
