### ISSUE TITLE
patch_forward function bug

### ISSUE THREAD

**Issue by h6197627** [NVIDIA/apex#659]
Using DataParallel model is not compatible with patch_forward function from **_initialize.py**
It is not only problem of DataParallel + O2 which uses patch_forward (and has multiple open issues), but also and DataParallel + O1 + cast_model_outputs which also uses patch_forward.
I debugged AMP model convertion and found that the problem arises because patched forward function (function object) always uses forward method from closure which comes from master GPU models. This means that all forwards will go through master replica and consequently will cause weights/input device mismatch.
Unfortunately I am not sure how it should be fixed

**Comment by mcarilli** [comment]
RIght now I'm working hard on native Pytorch support for mixed precision which will accommodate DistributedDataParallel, DataParallel, and model parallel training, targeting the 1.5 release. Apex as a source for mixed precision is not a future-proof path, it's annoying for people to install something separate. If Apex helps, that's great, but the sooner we get something that's packaged and tested as a native component of Pytorch, the better. If Apex does not work for you currently, my best advice is to wait for the upstream support. See #269 (comment).
