### ISSUE TITLE
PR #657 breaks contrib FP16_Optimizer

### ISSUE THREAD

**Issue by francoishernandez** [NVIDIA/apex#703]
Hi there,
It looks like #657 is breaking `apex.contrib.optimizers.FP16_Optimizer`. The `fp32_groups_flat` attribute is removed but is still used in the definition of `state_dict()`:
https://github.com/NVIDIA/apex/blob/2ca894da7be755711cbbdf56c74bb7904bfd8417/apex/contrib/optimizers/fp16_optimizer.py#L199
and `load_state_dict()`:
https://github.com/NVIDIA/apex/blob/2ca894da7be755711cbbdf56c74bb7904bfd8417/apex/contrib/optimizers/fp16_optimizer.py#L241

cc @vince62s @kexinyu @mcarilli

**Comment by vince62s** [comment]
Just changing these fp32_groups_flat to fp32_groups seems to fix this.

**Comment by kexinyu** [comment]
Thanks for bringing this up! Just created a PR for this https://github.com/NVIDIA/apex/pull/704.
