### ISSUE TITLE
Does apex.parallel.SyncBatchNorm support torch.nn.parallel.DistributedDataParallel?

### ISSUE THREAD

**Issue by DKandrew** [NVIDIA/apex#709]
In the apex document of SyncBatchNorm, it says "apex.parallel.SyncBatchNorm is designed to work with DistributedDataParallel." This sentence is kind of ambiguous, does it support only apex.parallel.DistributedDataParallel, or does it also support torch.nn.parallel.DistributedDataParallel? 

Similarily, as mentioned in issue #75 , apex is designed to be compatible with pytorch. Does it means we can use Pytorch's SyncBatchNorm in apex.parallel.DistributedDataParallel as well? 

Update (2/7/2020)
I found this sentence in the [example folder](https://github.com/NVIDIA/apex/tree/master/examples/imagenet), which implies that we can use pytorch's API or apex's API simultaneously. Can anyone confirm this? 
"The choice of DDP wrapper (Torch or Apex) is orthogonal to the use of Amp and other Apex tools. It is safe to use apex.amp with either torch.nn.parallel.DistributedDataParallel or apex.parallel.DistributedDataParallel"

**Comment by ptrblck** [comment]
`apex` modules should work with the PyTorch implementations.
However, since PyTorch ships with DDP as well as `SyncBatchNorm` you could just use the upstream implementations.

**Comment by DKandrew** [comment]
Thanks for your answer! Eventually, I used the PyTorch's implementation.
