### ISSUE TITLE
Errors during compilation 

### ISSUE THREAD

**Issue by alonhazan** [NVIDIA/apex#71]
When trying to run compilation, using: "python setup.py install --cuda_ext --cpp_ext" , at the first stage, errors for missing pytorch libraries are thrown: `c10, ATen, torch/extension.h.` This part is possibly fixed by adding manually these files from pytorch repo. 
The next issue is:
```
"/.../lib/python3.6/site-packages/torch/lib/include/ATen/Error.h:105:0: note: this is the location of the previous definition
#define AT_CHECK(cond, ...) \
^
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
```
No information about the error is available, even when using strace on the compilation command.
environment details:
gcc/g++ : 4.8.5
cuda 9, pytorch 0.4.1 (tested also with 0.4.0), python3.6.
OS: RHEL7.4 , using conda environment
arch: ppc64 (PowerAI 9)

Same issues confirmed on x86_64 - intel

**Comment by mcarilli** [comment]
The pytorch C++ extension API is unstable and not officially supported prior to 1.0.

If you don't need the cpp extension functionality, you can do
```
python setup.py install
``` 
for a Python-only install which should work fine for all Pytorch versions from 0.4 to present.

If you do need the cpp extension functionality, you'll have to use pytorch 1.0.
