### ISSUE TITLE
the behavior--data Truncate of apex DDP is different with pytorch's

### ISSUE THREAD

**Issue by lijiayu0725** [NVIDIA/apex#710]
My setting is:
batchsize=16
num_gpu=8
loading data with pytorch buildin DataSet and DataLoader.

when I run the pytorch buildin DistributedDataParallel, and check the input x of the forward function, each gpu has batch 2, that's right.
But when I replace it to the apex version DDP, the batchsize in the forward function is 16, seems not to truncate the data with the num_gpu automaticlly. when I set DataLoader's batch_size to 16 // 8, everything is ok. But why?

**Comment by ptrblck** [comment]
You might be using the PyTorch `nn.DistributedDataParallel` implementation with single-process-multi-gpu mode, which will be similar to `nn.DataParallel`.

The recommended way is to use single-process-single-gpu.
Have a look at the [docs](https://pytorch.org/docs/stable/nn.html#distributeddataparallel) for more information.
