### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kandalto** [NVIDIA/apex#751]
Hello,

Installing with these commands:

$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

throws this error:

ERROR: Command errored out with exit status 1: /home/kapp/anaconda3/envs/simpletransformers/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gk39ttw9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gk39ttw9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-785wxkd8/install-record.txt --single-version-externally-managed --compile --install-headers /home/kapp/anaconda3/envs/simpletransformers/include/python3.8/apex Check the logs for full command output.

torch version 1.4
cuda version 10.0

torch.cuda.is_available()
returns True

Thanks!

**Comment by Lornatang** [comment]
@kandalto 
Please provide detailed installation log

**Comment by kandalto** [comment]
SOLVED: by downgrading pytorch to 1.2.0. Not sure what caused the problem.
