### ISSUE TITLE
Is instance norm supported?

### ISSUE THREAD

**Issue by tinghuiz** [NVIDIA/apex#81]
I got the following error when `nn.InstanceNorm2d` is used in the network:

`RuntimeError: Expected object of type torch.cuda.HalfTensor but found type torch.cuda.FloatTensor for argument #4 'running_mean'`

Any suggestion on how to get around this?

**Comment by mcarilli** [comment]
Can you provide some more information?  What Apex tools are you using, and what Pytorch version?

**Comment by tinghuiz** [comment]
Never mind. It works with instance norm. Apex was not set up properly on my end. Thanks for the reply and great work!
