### ISSUE TITLE
Apex DDP vs Pytorch DDP

### ISSUE THREAD

**Issue by kleingeo** [NVIDIA/apex#824]
I understand that the `apex.parallel.DistributedDataParallel` is supposed to essentially a drop-in for the `torch.nn.parallel.DistributedDataParallel`, but are all the requirements to set-up the `apex.parallel.DistributedDataParallel` the same as the normal Pytorch version? Is it possible to show an explicit difference between setting up the one vs the other?

**Comment by mcarilli** [comment]
There is https://github.com/NVIDIA/apex/blob/cf50dc7c031295360c246a72ac03d22cdbb96354/examples/simple/distributed/distributed_data_parallel.py#L48-L52
but these days, just use torch.nn.parallel.DistributedDataParallel.  apex DDP remains to support some networks that still rely on it.
