### ISSUE TITLE
FP16_Optimizer has no way to "retain_graph=True"

### ISSUE THREAD

**Issue by tstandley** [NVIDIA/apex#85]
I need to call "backward" multiple times, but when I do, I get:
`RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.`

Of course, when I try to pass 

`self.optimizer.backward(loss,retain_graph=True)`

I get:
`TypeError: backward() got an unexpected keyword argument 'retain_graph'`

**Comment by tstandley** [comment]
I should add that:
```
optimizer.backward(loss1, update_master_grads=False)
optimizer.backward(loss2, update_master_grads=False)
optimizer.update_master_grads()
```
also results in:
`RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.`

**Comment by mcarilli** [comment]
Sorry for the delayed response, I lost track of this.  I'll add the option to forward retain_graph=True to optimizer.backward(loss).

**Comment by jshanna100** [comment]
ping

**Comment by mcarilli** [comment]
I've added the option and [updated the docs](https://nvidia.github.io/apex/fp16_utils.html#apex.fp16_utils.FP16_Optimizer.backward).  I had to think about it and test it to convince myself it didn't break any mixed precision control flow, but from the recipe's perspective I guess it's no different from accumulating gradients via multiple losses.  With that in mind I do recommend using `update_master_grads=False` in conjunction, as you noted:
```
optimizer.backward(loss1, update_master_grads=False, retain_graph=True)
# reusing loss1, but tearing down its graph this time:
optimizer.backward(loss1, update_master_grads=False)
optimizer.update_master_grads()
```
Using `update_master_grads` this way should be a performance optimization but not essential for correctness. 

Let me know if this works for you.

**Comment by jshanna100** [comment]
Works for me, thanks!
