### ISSUE TITLE
apex.contrib.multihead_attn  generate different output with the same input

### ISSUE THREAD

**Issue by benywon** [NVIDIA/apex#882]
Recently, I use the EncdecMultiheadAttn module to train a language generation model. However, during inference, for the same input, the output of the multihead_attn is different every run, although the difference is minor, it still results in a different generation.

The official nn.MultiheadAttention did not have the issue.

Anyone can help?

**Comment by kevinstephano** [comment]
Given this is inference, I would expect the randomization to be turned off and the only other difference to be slight floating point differences.  Did you explicitly set the knob to turn `training` off?

**Comment by benywon** [comment]
> Given this is inference, I would expect the randomization to be turned off and the only other difference to be slight floating point differences. Did you explicitly set the knob to turn `training` off?

Thank you, it seems that explicitly setting the is_training=self.training solves the problem!

**Comment by kevinstephano** [comment]
That's great!  Glad to hear there was not a bug.
