### ISSUE TITLE
How to use torch.svd() with half precision?

### ISSUE THREAD

**Issue by halostorm** [NVIDIA/apex#887]
I use fp16 in my net, but it seems torch.svd() doesn't support half precision ?

`RuntimeError: "svd_cuda" not implemented for 'Half'`

**Comment by ptrblck** [comment]
`torch.svd` calls into MAGMA for CUDA tensors, which doesn't implement this operation for FP16 most likely due to the numerical precision needed for these linear algebra methods.

Closing this issue, as it's a valid limitation by MAGMA.

**Comment by halostorm** [comment]
Got! Thank you very much!





------------------ Original ------------------
