### ISSUE TITLE
Merged PR #925 breaks CPU-Only installs

### ISSUE THREAD

**Issue by aatifjiwani** [NVIDIA/apex#931]
While running a Github CD job, it attempted to install Apex, but failed with the following traceback: 

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-f1vgc77y/setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-f1vgc77y/setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

It seems that cuda_dir is None, which is intuitively expected when installing Apex on a CPU only machine. But even when installing on a CPU only machine, the setup is still looking for the Nvidia Cross-Compilers. 

The most recent commit as of 8/4/2020 (hash: 5b53121a2124d...) adds this line into setup, which breaks the install. 

The corresponding line within the current release of Apex:
https://github.com/NVIDIA/apex/blob/5b53121a2124d70dad0fd4f462d1392d06573ca9/setup.py#L14

**Comment by matthaeusheer** [comment]
I can confirm this issue.

**Comment by Raghava14** [comment]
I am facing the same issue as well but in my case I am facing the issue when trying to install apex in a GPU machine.

**Comment by wangzifu1994** [comment]
same here

**Comment by aatifjiwani** [comment]
> I am facing the same issue as well but in my case I am facing the issue when trying to install apex in a GPU machine. Was anyone able to fix it ?

@Raghava14 The fix that we were able to make was install Apex using the commit before the one that broke the installation. Obviously this is not good in the long run but its a fine temporary fix

**Comment by ptrblck** [comment]
Thanks for reporting this issue. The `get_cuda_bare_metal_version` has to be moved inside the MHA code. 
I'll provide a fix tomorrow for it.

**Comment by qhaas** [comment]
Seeing this with CentOS 8.2 with default python3(.6).

Would be helpful to have tags with snapshots that were known to be relatively stable.  Always get nervous when cloning master.

**Comment by mcarilli** [comment]
Please do not consider the fix an endorsement of Apex as a future-proof source of mixed precision.  [torch.cuda.amp](https://github.com/NVIDIA/apex/issues/818) is the truth.  It's much easier to use.  The modularity and flexibility makes it almost fun.

**Comment by vince62s** [comment]
Even if torch.cuda.amp must be the ground truth :)  if we need fusedadam, Apex is still required, and  can confirm #937 does not fix the issue. Needs to be reopen.

**Comment by monk1337** [comment]
Is there any fix for this issue? I am still facing the same issue while installing apex from source code.
