### ISSUE TITLE
 VC version 14.1 not installed.  

### ISSUE THREAD

**Issue by SungmanHong** [NVIDIA/apex#935]
Hi, I installed torch, cuda in latest version and installed NVIDIA CUDA DRIVER and python 3.6 and visual studio 2019 and C++ package. I checked my torch uses GPU successfully by CUDA.

But I can't install apex, it has error message below...

It seems that visual studio version dismatch... it is right?

PS D:\ocr_kor-master\ocr_kor-master```
> pip install apex
Collecting apex
  Using cached apex-0.9.10dev.tar.gz (36 kB)
Collecting cryptacular
  Using cached cryptacular-1.5.5.tar.gz (39 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\owner\appdata\local\programs\python\python36\python.exe' 'c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\owner\AppData\Local\Temp\tmpide13jcc'
         cwd: C:\Users\owner\AppData\Local\Temp\pip-install-ty49_csq\cryptacular
    Complete output (244 lines):
    scons: Reading SConscript files ...
    C:\Users\owner\AppData\Local\Temp\pip-build-env-ho4qo696\overlay\Lib\site-packages\_distutils_hack\__init__.py:19: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
      "Distutils was imported before Setuptools. This usage is discouraged "

    scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
     Installed versions are: ['14.2']
    File "C:\Users\owner\AppData\Local\Temp\pip-install-ty49_csq\cryptacular\SConstruct", line 30, in <module>

    scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
     Installed versions are: ['14.2']
    File "C:\Users\owner\AppData\Local\Temp\pip-install-ty49_csq\cryptacular\SConstruct", line 30, in <module>
    {'_ldflags': {('executable', False): ['/nologo',
                                          '/INCREMENTAL:NO',
                                          '/LTCG',
                                          '/MANIFEST:EMBED,ID=1'],
                  ('executable', True): ['/nologo',
                                         '/INCREMENTAL:NO',
                                         '/LTCG',
                                         '/DEBUG:FULL',
                                         '/MANIFEST:EMBED,ID=1'],
                  ('executable', None): ['/nologo',
                                         '/INCREMENTAL:NO',
                                         '/LTCG',
                                         '/MANIFEST:EMBED,ID=1'],
                  ('shared_library', False): ['/nologo',
                                              '/INCREMENTAL:NO',
                                              '/LTCG'],
                  ('shared_library', None): ['/nologo', '/INCREMENTAL:NO', '/LTCG'],
                  ('shared_library', True): ['/nologo',
                                             '/INCREMENTAL:NO',
                                             '/LTCG',
                                             '/DEBUG:FULL'],
                  ('shared_object', False): ['/nologo',
                                             '/INCREMENTAL:NO',
                                             '/LTCG',
                                             '/DLL',
                                             '/MANIFEST:EMBED,ID=2',
                                             '/MANIFESTUAC:NO'],
                  ('shared_object', None): ['/nologo',
                                            '/INCREMENTAL:NO',
                                            '/LTCG',
                                            '/DLL',
                                            '/MANIFEST:EMBED,ID=2',
                                            '/MANIFESTUAC:NO'],
                  ('shared_object', True): ['/nologo',
                                            '/INCREMENTAL:NO',
                                            '/LTCG',
                                            '/DEBUG:FULL',
                                            '/DLL',
                                            '/MANIFEST:EMBED,ID=2',
                                            '/MANIFESTUAC:NO']},
     '_paths': 'C:\\Program Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\\\Extensions\\Microsoft\\IntelliCode\\CLI;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x86;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\VC\\VCPackages;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team '
               'Explorer;C:\\Program Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn;C:\\Program '
               'Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team '
               'Tools\\Performance Tools\\x64;C:\\Program Files (x86)\\Microsoft '
               'Visual Studio\\2019\\Community\\Team Tools\\Performance '
               'Tools;C:\\Program Files (x86)\\Microsoft Visual '
               'Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\\\x64;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\;C:\\Program '
               'Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 '
               'Tools\\;C:\\Program Files (x86)\\Windows '
               'Kits\\10\\bin\\10.0.18362.0\\x86;C:\\Program Files (x86)\\Windows '
               'Kits\\10\\bin\\x86;C:\\Program Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\\\MSBuild\\Current\\Bin;C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\;C:\\Program Files '
               '(x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\Tools\\;c:\\users\\owner\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pywin32_system32;C:\\Users\\owner\\AppData\\Local\\Temp\\pip-build-env-ho4qo696\\overlay\\Scripts;C:\\Users\\owner\\AppData\\Local\\Temp\\pip-build-env-ho4qo696\\normal\\Scripts;c:\\users\\owner\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pywin32_system32;C:\\Program '
               'Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\bin;C:\\Program '
               'Files\\NVIDIA GPU Computing '
               'Toolkit\\CUDA\\v11.0\\libnvvp;;;;C:\\Program Files '
               '(x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS '
               'Client\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program '
               'Files (x86)\\Intel\\Intel(R) Management Engine '
               'Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management '
               'Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) '
               'Management Engine Components\\IPT;C:\\Program '
               'Files\\Intel\\Intel(R) Management Engine '
               'Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program '
               'Files\\Git\\cmd;C:\\Program Files\\GTK2-Runtime '
               'Win64\\bin;C:\\Program Files\\GTK3-Runtime Win64\\bin;C:\\Program '
               'Files (x86)\\GTK2-Runtime\\bin;C:\\Program Files\\Microsoft VS '
               'Code\\bin;C:\\Program Files\\PuTTY\\;C:\\Program '
               'Files\\CMake\\bin;C:\\Program Files\\NVIDIA Corporation\\Nsight '
               'Compute 2020.1.2\\;C:\\Program Files (x86)\\NVIDIA '
               'Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA '
               'Corporation\\NVIDIA NvDLISR;C:\\Program Files\\MySQL\\MySQL Shell '
               '8.0\\bin\\;C:\\Users\\owner\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\;C:\\Users\\owner\\AppData\\Local\\Programs\\Python\\Python36\\;C:\\Users\\owner\\Anaconda3;C:\\Users\\owner\\Anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\owner\\Anaconda3\\Library\\usr\\bin;C:\\Users\\owner\\Anaconda3\\Library\\bin;C:\\Users\\owner\\Anaconda3\\Scripts;C:\\Users\\owner\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\owner\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\owner\\AppData\\Local\\Programs\\Microsoft '
               'VS Code\\bin;C:\\Program Files '
               '(x86)\\Graphviz2.38\\bin;C:\\Users\\owner\\Untitled '
               'Folder;C:\\Program Files (x86)\\Graphviz2.38\\bin\\;C:\\Program '
               'Files\\GTK3-Runtime Win64\\bin;C:\\Program Files\\GTK3-Runtime '
               'Win64\\bin\\;C:\\Program Files\\JetBrains\\PyCharm Community '
               'Edition 2019.3.2\\bin;;C:\\Program '
               'Files\\Bandizip\\;"C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin";C:\\Program '
               'Files\\JetBrains\\PyCharm '
               '2019.3.3\\bin;;D:\\cygwin64;D:\\Users\\owner\\Downloads;C:\\pypy3.6-v7.3.1-win32;C:\\Program '
               'Files\\gs\\gs9.52\\bin;"C:\\Program '
               'Files\\gs\\gs9.52\\bin\\;";C:\\Program '
               'Files\\gs\\gs9.52\\bin\\;;C:\\Program Files (x86)\\Microsoft '
               'Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program '
               'Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja',
     '_vcruntime_redist': 'C:\\Program Files (x86)\\Microsoft Visual '
                          'Studio\\2019\\Community\\VC\\Auxiliary\\Build\\..\\..\\redist\\MSVC\\14.27.29016\\onecore\\x64\\Microsoft.VC142.CRT\\vcruntime140.dll',
     'cc': 'C:\\Program Files (x86)\\Microsoft Visual '
           'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe',
     'compile_options': ['/nologo', '/Ox', '/W3', '/GL', '/DNDEBUG', '/MD'],
     'compile_options_debug': ['/nologo', '/Od', '/MDd', '/Zi', '/W3', '/D_DEBUG'],
     'dry_run': 0,
     'force': None,
     'include_dirs': ['c:\\users\\owner\\appdata\\local\\programs\\python\\python36\\include',
                      'c:\\users\\owner\\appdata\\local\\programs\\python\\python36\\include',
                      'C:\\Program Files (x86)\\Microsoft Visual '
                      'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\ATLMFC\\include',
                      'C:\\Program Files (x86)\\Microsoft Visual '
                      'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\include',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\NETFXSDK\\4.8\\include\\um',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\include\\10.0.18362.0\\ucrt',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\include\\10.0.18362.0\\shared',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\include\\10.0.18362.0\\um',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\include\\10.0.18362.0\\winrt',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\include\\10.0.18362.0\\cppwinrt'],
     'initialized': True,
     'ldflags_exe': ['/nologo', '/INCREMENTAL:NO', '/LTCG', '/MANIFEST:EMBED,ID=1'],
     'ldflags_exe_debug': ['/nologo',
                           '/INCREMENTAL:NO',
                           '/LTCG',
                           '/DEBUG:FULL',
                           '/MANIFEST:EMBED,ID=1'],
     'ldflags_shared': ['/nologo',
                        '/INCREMENTAL:NO',
                        '/LTCG',
                        '/DLL',
                        '/MANIFEST:EMBED,ID=2',
                        '/MANIFESTUAC:NO'],
     'ldflags_shared_debug': ['/nologo',
                              '/INCREMENTAL:NO',
                              '/LTCG',
                              '/DEBUG:FULL',
                              '/DLL',
                              '/MANIFEST:EMBED,ID=2',
                              '/MANIFESTUAC:NO'],
     'ldflags_static': ['/nologo', '/INCREMENTAL:NO', '/LTCG'],
     'ldflags_static_debug': ['/nologo', '/INCREMENTAL:NO', '/LTCG', '/DEBUG:FULL'],
     'lib': 'C:\\Program Files (x86)\\Microsoft Visual '
            'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\lib.exe',
     'libraries': [],
     'library_dirs': ['c:\\users\\owner\\appdata\\local\\programs\\python\\python36\\libs',
                      'c:\\users\\owner\\appdata\\local\\programs\\python\\python36\\PCbuild\\amd64',
                      'C:\\Program Files (x86)\\Microsoft Visual '
                      'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\ATLMFC\\lib\\x64',
                      'C:\\Program Files (x86)\\Microsoft Visual '
                      'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\lib\\x64',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\NETFXSDK\\4.8\\lib\\um\\x64',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\lib\\10.0.18362.0\\ucrt\\x64',
                      'C:\\Program Files (x86)\\Windows '
                      'Kits\\10\\lib\\10.0.18362.0\\um\\x64'],
     'linker': 'C:\\Program Files (x86)\\Microsoft Visual '
               'Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\link.exe',
     'macros': [],
     'mc': 'C:\\Program Files (x86)\\Windows '
           'Kits\\10\\bin\\10.0.18362.0\\x86\\mc.exe',
     'mt': 'C:\\Program Files (x86)\\Windows '
           'Kits\\10\\bin\\10.0.18362.0\\x86\\mt.exe',
     'objects': [],
     'output_dir': None,
     'plat_name': None,
     'preprocess_options': None,
     'rc': 'C:\\Program Files (x86)\\Windows '
           'Kits\\10\\bin\\10.0.18362.0\\x86\\rc.exe',
     'runtime_library_dirs': [],
     'spawn': <function no_build_ext.build_extension.<locals>.noop_spawn at 0x00000273DCD8CF28>,
     'verbose': None}
    scons: done reading SConscript files.
    scons: Building targets ...
    Install file: "cryptacular\__init__.py" as "build\wheel\cryptacular\__init__.py"
    Install file: "cryptacular\bcrypt\__init__.py" as "build\wheel\cryptacular\bcrypt\__init__.py"
    Install file: "cryptacular\bcrypt\test_bcrypt.py" as "build\wheel\cryptacular\bcrypt\test_bcrypt.py"
    Install file: "cryptacular\core\__init__.py" as "build\wheel\cryptacular\core\__init__.py"
    Install file: "cryptacular\core\test_core.py" as "build\wheel\cryptacular\core\test_core.py"
    Install file: "cryptacular\crypt\__init__.py" as "build\wheel\cryptacular\crypt\__init__.py"
    Install file: "cryptacular\crypt\test_crypt.py" as "build\wheel\cryptacular\crypt\test_crypt.py"
    Install file: "cryptacular\pbkdf2\__init__.py" as "build\wheel\cryptacular\pbkdf2\__init__.py"
    Install file: "cryptacular\pbkdf2\test_pbkdf2.py" as "build\wheel\cryptacular\pbkdf2\test_pbkdf2.py"
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe" /Focrypt_blowfish-1.2\crypt_blowfish.obj /c crypt_blowfish-1.2\crypt_blowfish.c /nologo /Ox /W3 /GL /DNDEBUG /MD /nologo -D__SKIP_GNU /DNO_BF_ASM /DPy_LIMITED_API=0x03030000 /Icrypt_blowfish-1.2 /IC:\Users\owner\AppData\Local\programs\python\python36\include /IC:\Users\owner\AppData\Local\programs\python\python36\include "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt"
    crypt_blowfish.c
    crypt_blowfish-1.2\crypt_blowfish.c(898): warning C4244: '=': 'unsigned long'에서 'char'(으)로 변환하면서 데이터가 손실될 수 있습니다.
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe" /Focrypt_blowfish-1.2\crypt_gensalt.obj /c crypt_blowfish-1.2\crypt_gensalt.c /nologo /Ox /W3 /GL /DNDEBUG /MD /nologo -D__SKIP_GNU /DNO_BF_ASM /DPy_LIMITED_API=0x03030000 /Icrypt_blowfish-1.2 /IC:\Users\owner\AppData\Local\programs\python\python36\include /IC:\Users\owner\AppData\Local\programs\python\python36\include "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt"
    crypt_gensalt.c
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe" /Focrypt_blowfish-1.2\wrapper.obj /c crypt_blowfish-1.2\wrapper.c /nologo /Ox /W3 /GL /DNDEBUG /MD /nologo -D__SKIP_GNU /DNO_BF_ASM /DPy_LIMITED_API=0x03030000 /Icrypt_blowfish-1.2 /IC:\Users\owner\AppData\Local\programs\python\python36\include /IC:\Users\owner\AppData\Local\programs\python\python36\include "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt"
    wrapper.c
    crypt_blowfish-1.2\wrapper.c(245): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe" /Focryptacular\bcrypt\_bcrypt.obj /c cryptacular\bcrypt\_bcrypt.c /nologo /Ox /W3 /GL /DNDEBUG /MD /nologo -D__SKIP_GNU /DNO_BF_ASM /DPy_LIMITED_API=0x03030000 /Icrypt_blowfish-1.2 /IC:\Users\owner\AppData\Local\programs\python\python36\include /IC:\Users\owner\AppData\Local\programs\python\python36\include "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include" "/IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt"
    _bcrypt.c
    cryptacular\bcrypt\_bcrypt.c(79): warning C4244: '함수': 'const Py_ssize_t'에서 'int'(으)로 변환하면서 데이터가 손실될 수 있습 니다.
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /out:cryptacular\bcrypt\_bcrypt.pyd /implib:cryptacular\bcrypt\_bcrypt.lib /LIBPATH:C:\Users\owner\AppData\Local\programs\python\python36\libs /LIBPATH:C:\Users\owner\AppData\Local\programs\python\python36\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" crypt_blowfish-1.2\crypt_blowfish.obj crypt_blowfish-1.2\crypt_gensalt.obj crypt_blowfish-1.2\wrapper.obj cryptacular\bcrypt\_bcrypt.obj
       cryptacular\bcrypt\_bcrypt.lib 라이브러리 및 cryptacular\bcrypt\_bcrypt.exp 개체를 생성하고 있습니다.
    코드를 생성하고 있습니다.
    코드를 생성했습니다.
    LINK : fatal error LNK1158: 'rc.exe'을(를) 실행할 수 없습니다.
    scons: *** [cryptacular\bcrypt\_bcrypt.pyd] Error 1158
    scons: building terminated because of errors.
    Traceback (most recent call last):
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'enscons.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 131, in prepare_metadata_for_build_wheel
        config_settings)
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 164, in _get_wheel_metadata_from_wheel
        with ZipFile(whl_file) as zipf:
      File "c:\users\owner\appdata\local\programs\python\python36\lib\zipfile.py", line 1113, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\owner\\AppData\\Local\\Temp\\pip-modern-metadata-vuqh2rqb\\cryptacular-1.5.5-cp36-abi3-win_amd64.whl'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\owner\appdata\local\programs\python\python36\python.exe' 'c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\owner\AppData\Local\Temp\tmpide13jcc' Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.2.1 is available.
You should consider upgrading via the 'c:\users\owner\appdata\local\programs\python\python36\python.exe -m pip install --upgrade pip' command.
PS D:\ocr_kor-master\ocr_kor-master>

```

**Comment by SungmanHong** [comment]
I don't know why BUT it solves the intall error


REF : https://github.com/NVIDIA/apex/issues/905


I have the same problem with:
torch: 1.5.1
torch.version.cuda: 10.1

my install process:

git clone https://github.com/NVIDIA/apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex

RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries. Pytorch binaries were compiled with Cuda 10.1. In some cases, a minor-version mismatch will not cause later errors: https://github.com/NVIDIA/apex/pull/323#discussion_r287021798. You can try commenting out this check (at your own risk). Running setup.py install for apex ... error

**Comment by ReinierKoops** [comment]
Another way to approach this could be by installing VC 2017 build tools, because Visual Studio code build tools 2017 == 14.1
You can try via this link: https://visualstudio.microsoft.com/vs/older-downloads/ and then go to 2017 section.

**Comment by SungmanHong** [comment]
Thanks, 
In case of CUDA 14.1, VC 2017 is correct 

also I found new things. my CUDA version of maximum supported is not correct of my GPU spec.
some GPU dose not support latest CUDA version. so I installed CUDA 10.1 and it works.
