### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda' 

### ISSUE THREAD

**Issue by ajesujoba** [NVIDIA/apex#954]
I was trying to run a NMT model in fairseq but I got the `ModuleNotFoundError: No module named 'fused_layer_norm_cuda' `. Find the output below: 

![fused_layer](https://user-images.githubusercontent.com/12751379/91452059-708c7d00-e87e-11ea-8c59-701fbba86efd.PNG)

Using `nvcc --version ` gives:
![nvidia](https://user-images.githubusercontent.com/12751379/91452205-9f0a5800-e87e-11ea-95e2-8ac4f76ee05e.PNG)

I have tried the instructions [here](https://github.com/NVIDIA/apex#quick-start), but I am still getting the `ModuleNotFoundError: No module named 'fused_layer_norm_cuda'`. What can I do?

**Comment by saurabh-kataria** [comment]
I just installed apex like this and error disappeared: `python setup.py install --cuda_ext --cpp_ext`

**Comment by Pinging-ZJU** [comment]
I solve this problem by rolling back the code version to the old one.

**Comment by cs-wangfeng** [comment]
> I just installed apex like this and error disappeared: `python setup.py install --cuda_ext --cpp_ext`

I used your method and get this error info:
```
The detected CUDA version (12.2) mismatches the version that was used to compile
PyTorch (11.1). Please make sure to use the same CUDA versions.
```
