### ISSUE TITLE
csrc/multi_tensor_apply.cuh:5:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory

### ISSUE THREAD

**Issue by super233** [NVIDIA/apex#976]
I installed apex by using `pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`, and encountered error `csrc/multi_tensor_apply.cuh:5:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory`, is there anyone has the corresponding solution or some useful information？

## Version Info:
- Pytorch: 1.0
- CUDA: 10.0
- GCC: 7.4.0

## Error Info:
    In file included from csrc/multi_tensor_sgd_kernel.cu:5:0:
    csrc/multi_tensor_apply.cuh:5:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory
     #include <c10/cuda/CUDAGuard.h>
              ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /root/miniconda3/envs/meike/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-le_w9es0/install-record.txt --single-version-externally-managed --compile --install-headers /root/miniconda3/envs/meike/include/python3.7m/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 852, in install
    req_description=str(self.req),
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 406, in run
    pycompile=options.compile,
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 277, in runner
    spinner=spinner,
  File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /root/miniconda3/envs/meike/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-le_w9es0/install-record.txt --single-version-externally-managed --compile --install-headers /root/miniconda3/envs/meike/include/python3.7m/apex Check the logs for full command output.

**Comment by PhillipRSmith** [comment]
I am also having the same issue as above, does anyone know what the issue could be?

**Comment by guyii54** [comment]
> I installed apex by using `pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`, and encountered error `csrc/multi_tensor_apply.cuh:5:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory`, is there anyone has the corresponding solution or some useful information？
> 
> ## Version Info:
> * Pytorch: 1.0
> * CUDA: 10.0
> * GCC: 7.4.0
> 
> ## Error Info:
> ```
> In file included from csrc/multi_tensor_sgd_kernel.cu:5:0:
> csrc/multi_tensor_apply.cuh:5:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory
>  #include <c10/cuda/CUDAGuard.h>
>           ^~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
> Running setup.py install for apex ... error
> ```
> 
> ERROR: Command errored out with exit status 1: /root/miniconda3/envs/meike/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"'; **file**='"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-le_w9es0/install-record.txt --single-version-externally-managed --compile --install-headers /root/miniconda3/envs/meike/include/python3.7m/apex Check the logs for full command output.
> Exception information:
> Traceback (most recent call last):
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 852, in install
> req_description=str(self.req),
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
> raise LegacyInstallFailure
> pip._internal.operations.install.legacy.LegacyInstallFailure
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
> status = self.run(options, args)
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
> return func(self, options, args)
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 406, in run
> pycompile=options.compile,
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/req/**init**.py", line 90, in install_given_reqs
> pycompile=pycompile,
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 856, in install
> six.reraise(*exc.parent)
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_vendor/six.py", line 703, in reraise
> raise value
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 76, in install
> cwd=unpacked_source_directory,
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 277, in runner
> spinner=spinner,
> File "/root/miniconda3/envs/meike/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
> raise InstallationError(exc_msg)
> pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /root/miniconda3/envs/meike/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"'; **file**='"'"'/tmp/pip-req-build-ter90v6q/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-le_w9es0/install-record.txt --single-version-externally-managed --compile --install-headers /root/miniconda3/envs/meike/include/python3.7m/apex Check the logs for full command output.

I have also met this issue, could you tell me how to fix it? thx a lot~

**Comment by Shualite** [comment]
@PhillipRSmith @guyii54 Please change your pytorch version from 1.0 to 1.1. And you may be miss another problem, which can be seen in https://github.com/NVIDIA/apex/issues/944#issue-679857757

**Comment by incredible-john** [comment]
> @PhillipRSmith @guyii54 Please change your pytorch version from 1.0 to 1.1. And you may be miss another problem, which can be seen in [#944 (comment)](https://github.com/NVIDIA/apex/issues/944#issue-679857757)

checkout the #944 issue
and follow the instruction: checkout the apex to an early branch
and it work for me! the apex compiles successfully, i am working on pytorch=1.0.0
