### ISSUE TITLE
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./ error

### ISSUE THREAD

**Issue by wcy1122** [NVIDIA/apex#983]
/home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip/_internal/commands/install.py:235: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 20.2.4 from /home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-cm6n55ax
Created temporary directory: /tmp/pip-req-tracker-g0sq7xp8
Initialized build tracking at /tmp/pip-req-tracker-g0sq7xp8
Created build tracker: /tmp/pip-req-tracker-g0sq7xp8
Entered build tracker: /tmp/pip-req-tracker-g0sq7xp8
Created temporary directory: /tmp/pip-install-lnex2_jx
Processing /home/chengyao/Documents/wetectron
  Created temporary directory: /tmp/pip-req-build-54_pn488
  Added file:///home/chengyao/Documents/wetectron to build tracker '/tmp/pip-req-tracker-g0sq7xp8'
    Running setup.py (path:/tmp/pip-req-build-54_pn488/setup.py) egg_info for package from file:///home/chengyao/Documents/wetectron
    Created temporary directory: /tmp/pip-pip-egg-info-_0a843i8
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info
    writing /tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-_0a843i8/wetectron.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-54_pn488 has version 1.0, which satisfies requirement wetectron==1.0 from file:///home/chengyao/Documents/wetectron
  Removed wetectron==1.0 from file:///home/chengyao/Documents/wetectron from build tracker '/tmp/pip-req-tracker-g0sq7xp8'
Skipping wheel build for wetectron, due to binaries being disabled for it.
Installing collected packages: wetectron
  Created temporary directory: /tmp/pip-record-l4av_mud
    Running command /home/chengyao/anaconda3/envs/wetectron/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-54_pn488/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-54_pn488/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-l4av_mud/install-record.txt --single-version-externally-managed --compile --install-headers /home/chengyao/anaconda3/envs/wetectron/include/python3.7m/wetectron
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --cpp_ext not recognized
    Running setup.py install for wetectron ... error
ERROR: Command errored out with exit status 1: /home/chengyao/anaconda3/envs/wetectron/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-54_pn488/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-54_pn488/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-l4av_mud/install-record.txt --single-version-externally-managed --compile --install-headers /home/chengyao/anaconda3/envs/wetectron/include/python3.7m/wetectron Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 852, in install
    req_description=str(self.req),
  File "/home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

**Comment by wcy1122** [comment]
I don't know why, but I successfully install apex by avoid using tmux.

**Comment by Kittywyk** [comment]
> I don't know why, but I successfully install apex by avoid using tmux.

Hi, I'm a greenhand. And I met the same error as you.
Could u pls tell me how to avoid tmux to successfullt install apex?
Thanks.
