### ISSUE TITLE
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable WORLD_SIZE expected, but not set

### ISSUE THREAD

**Issue by yuanfuqiang456** [NVIDIA/apex#99]
when I used thid library ,an error occur ,that ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable WORLD_SIZE expected, but not set.I saw the example in this project ,and give a number ,the code is "torch.distributed.init_process_group(backend='nccl',
                                     init_method='env://', world_size=2)",but it did not work,can you help me?

**Comment by ngimel** [comment]
As the error message says, WORLD_SIZE should be an environment variable, not function argument. If you are using torch launcher (`-m torch.distributed.launch`) it will be set for you. https://pytorch.org/docs/stable/distributed.html#environment-variable-initialization

**Comment by fingertap** [comment]
What if I want to wrap the model in a class? After instantiating a model, I want to place it in a infinite loop, waiting for incoming data to make inference.

**Comment by NguyenCongPhucBK** [comment]
I get error when I train with only a GPU in colab.
Can I train model with only a GPU in Colab ?
![image](https://user-images.githubusercontent.com/80568515/128892053-bf552fb3-140f-455d-af02-3229aabb83f4.png)
![image](https://user-images.githubusercontent.com/80568515/128892154-45e2ce46-5923-4bc0-bfbf-78bb606ccb1b.png)

**Comment by santoshbs** [comment]
I am facing the same error as @NguyenCongPhucBK .

**Comment by aaaaaannie** [comment]
I am facing the same error as @NguyenCongPhucBK .
