### ISSUE TITLE
[contrib/ASP] `enable_sparsity` method does not exist

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/apex#991]
In the sample code (or test) for ASP, it uses `enable_sparsity` method.
But the method  does not exist on class ASP.

References
- [apex/contrib/sparsity/test](https://github.com/NVIDIA/apex/tree/master/apex/contrib/sparsity/test)

Error message is follows.

```
Traceback (most recent call last):
  File "checkpointing_test_part1.py", line 94, in <module>
    main(args)
  File "checkpointing_test_part1.py", line 58, in main
    ASP.enable_sparsity()
AttributeError: type object 'ASP' has no attribute 'enable_sparsity'
```

p.s.
I comment out ASP.enable_sparsity() and test program works fine.
If I switch `enable_sparsity` to `compute_sparse_masks`, Then I hit another problem `reshape_2d` does not exist.

**Comment by ChongyuNVIDIA** [comment]
This issue is already fixed in https://github.com/NVIDIA/apex/commit/89edb8196546187247c487a0494f7b6767ff0dc5.

**Comment by Triple-L** [comment]
Anyone know where to find the definition of reshape_2d and reshape_2d_inv ?
