### ISSUE TITLE
Is there any plan to have a release version of APEX?

### ISSUE THREAD

**Issue by zgc-sx** [NVIDIA/apex#999]
Hello, 
Is there any plan to have a release version of APEX?

Thanks!

**Comment by mcarilli** [comment]
No.  The release plan is Pytorch itself.  We're gradually moving everything useful from Apex into Pytorch.  torch.cuda.amp is now better than apex amp.  torch.nn.parallel.DistributedDataParallel is now better than apex DDP.  Fused optimizers with greatly reduced CPU overhead ([torch.optim._multi_tensor](https://github.com/pytorch/pytorch/tree/master/torch/optim/_multi_tensor)) were added by @izdeby in 1.7, although not yet documented, it's still under discussion when they'll be turned on by default.  @xwang233 is porting apex.parallel.SyncBatchNorm's channels last kernels to torch.nn.SyncBatchNorm, after which torch.nn.SyncBatchNorm will be better for all cases.

**Comment by zgc-sx** [comment]
OK, thanks for your reply.
